"""
Django settings for business project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import logging
import os
import sys
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Directory that contains content such as templates media and static & DB
CONTENT_DIR = BASE_DIR / "content"
IN_RAILWAY = os.environ.get("RAILWAY_ENVIRONMENT", False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "tgvhbjbvfdr5^asuiklfugulvb#$%^YHBNKI&tgvhbjbvfdr5^"
)


# STORAGE_PATH = CONTENT_DIR

# SECURITY: must stay env-driven. Hardcoding True (56bfbef1) exposed source files +
# debug tracebacks on prod for 2 days (found in 2026-06-10 SEO/security audit).
DEBUG = os.environ.get("DJANGO_DEBUG") == "1"

# True while the test runner is driving. Anything that reaches the outside world
# — SMS, email, paid APIs — must check this. Without it, running the suite texts
# real phones: the farm-out decline tests alone fire several sends per run.
TESTING = "test" in sys.argv or "pytest" in sys.modules


ALLOWED_HOSTS = [
    "graysontowncar.com",
    "www.graysontowncar.com",
    "localhost",
    "127.0.0.1",
    # Direct (non-Cloudflare) Railway domain — Stripe webhooks deliver here so the
    # signed payload can't be touched by the CDN. The old
    # grayson-towncar-production.up.railway.app domain is dead (railway fallback 404).
    "web-production-f70c.up.railway.app",
]


# Application definition
# Native and third-party apps
NATIVE_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
]

THIRD_PARTY_APPS = [
    "widget_tweaks",
    "import_export",
    "crispy_forms",
    "crispy_bootstrap5",
    "storages",
    "ckeditor",
    "ckeditor_uploader",
    "django_celery_beat",
    "simple_history",
]

if DEBUG:
    THIRD_PARTY_APPS += ["debug_toolbar"]

OUR_APPS = [
    "rates",
    "reservations.apps.ReservationsConfig",
    "users",
    "services",
    "blog",
    "payment",
    "drivers",
    "dispatching",
    "ghl_integration",
    "ops.apps.OpsConfig",
]

# After DEbuyg toolbar
INSTALLED_APPS = NATIVE_APPS + THIRD_PARTY_APPS + OUR_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Cap DB query time for web requests before any view (incl. the session query) runs.
    "reservations.middleware.StatementTimeoutMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "reservations.middleware.SlowRequestMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "reservations.middleware.ThreadLocalMiddleware",  # For audit logging
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ops.middleware.StaffActivityMiddleware",
]

if DEBUG:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    # Debug toolbar is OFF by default locally — it captures a Python stacktrace per SQL query and
    # re-renders all panels on every HTML response, which makes query-heavy pages (capacity
    # planner, dispatch boards) crawl. Opt back in for a session with ENABLE_DEBUG_TOOLBAR=1.
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: os.environ.get("ENABLE_DEBUG_TOOLBAR") == "1",
        # DEBUG is hardcoded True, so the toolbar is always in INSTALLED_APPS; without
        # this, `manage.py test` (which forces DEBUG=False) aborts on debug_toolbar.E001.
        "IS_RUNNING_TESTS": False,
    }
ROOT_URLCONF = "business.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [CONTENT_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ops.context_processors.pending_task_count",
                "ops.context_processors.timeclock_status",
                "ops.context_processors.critical_disruption_count",
                "drivers.context_processors.pending_timeoff_count",
                "drivers.context_processors.webpush_public_key",
            ],
        },
    },
]

WSGI_APPLICATION = "business.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# NOTE: the local read-only prod path (USE_PROD_RO / PROD_RO_DATABASE_URL) was
# removed — local development now runs entirely off the SQLite copy of prod, so
# there is no code path that connects a local machine to the production DB.
# Production on Railway still connects via RAILWAY_ENVIRONMENT / PGHOST below.
if os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("PGHOST"):
    # Use Railway PostgreSQL via DATABASE_URL
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ.get("DATABASE_URL"),
            # Persistent connections capped at 60s (was 600s). With 3 workers x 4
            # threads each pinning a connection for up to CONN_MAX_AGE, plus
            # background threads, 600s let idle connections pile up against
            # Postgres max_connections=100 (saturation outage 2026-07-18). 60s keeps
            # some connection reuse while releasing idle ones ~10x faster.
            conn_max_age=60,
            conn_health_checks=True,
        )
    }
else:
    # SQLite settings for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(CONTENT_DIR, "db.sqlite3"),
        }
    }


# Cache
# Use Redis if REDIS_URL is set (production), otherwise LocMemCache (dev)
_redis_url = os.environ.get("REDIS_URL")
if _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# Sessions: the django_session statement-timeout 500s came from
# SESSION_SAVE_EVERY_REQUEST=True (see below) UPDATE-ing a session row on EVERY
# request, not from the DB backend itself. That per-request write is forced OFF
# below, so a row is written only when the session DATA changes (login, etc.).
# The DB backend is then fine and stays SECURE: sessions are server-side and
# revocable (real logout), no ~4KB cookie limit, not client-readable. No Redis
# needed. When REDIS_URL is set later, the cache backend is used (no DB session
# I/O at all).
if _redis_url:
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    SESSION_ENGINE = "django.contrib.sessions.backends.db"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = CONTENT_DIR / "staticfiles"
STATIC_URL = "/static/"

STATICFILES_DIRS = [CONTENT_DIR / "static"]


# Stripe Settings
STRIPE_PUBLIC_KEY = os.environ.get("STRIPE_PUBLIC_KEY", "")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")

# Cloudflare Turnstile — bot challenge on the public forms.
#
# The site key is public (it ships in the page source), so it defaults to the
# widget already created in the Cloudflare dashboard and needs no deploy config.
# The secret must come from the environment as TURNSTILE_SECRET and is never
# committed. Until the secret is set, no widget renders and no verification
# runs, so local dev and CI are untouched. See users/turnstile.py.
TURNSTILE_SITE_KEY = os.environ.get(
    "TURNSTILE_SITE_KEY", "0x4AAAAAAEJZq0L0oCv3EMUW"
)
TURNSTILE_SECRET = os.environ.get("TURNSTILE_SECRET", "")

# NTFY Settings
NTFY_TOPIC = os.environ.get("NTFY_TOPIC", "grayson-leads")
NTFY_DRIVER_TOPIC = os.environ.get("NTFY_DRIVER_TOPIC", "grayson-driver-noti")
NTFY_DISPATCH_ALERT_TOPIC = os.environ.get("NTFY_DISPATCH_ALERT_TOPIC", "grayson-dispatch-alerts")
NTFY_SERVER = os.environ.get("NTFY_SERVER", "https://ntfy.sh")
# ntfy removed 2026-07-18 — senders in reservations/utils.py are hard no-ops now;
# this stays False so nothing re-enables it via env. (Kept for reference only.)
NTFY_ENABLED = False

# AeroAPI Settings
AEROAPI_KEY = os.environ.get("AEROAPI_KEY", "")
AEROAPI_BASE_URL = "https://aeroapi.flightaware.com/aeroapi"

# Samsara fleet telematics (Phase 1: read-only live vehicle visibility).
# Everything Samsara is gated behind this token — when empty, the integration
# is completely inert (no API calls, no DB writes, no UI changes).
SAMSARA_API_TOKEN = os.environ.get("SAMSARA_API_TOKEN", "")
SAMSARA_BASE_URL = os.environ.get("SAMSARA_BASE_URL", "https://api.samsara.com")

# Web Push (driver portal notifications). Gated behind the VAPID keys — when
# empty, push is completely inert (no subscribe UI, no sends). Generate a pair
# with py_vapid and set the same values on Railway to enable in prod.
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get("WEBPUSH_VAPID_PRIVATE_KEY", "")
WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get("WEBPUSH_VAPID_PUBLIC_KEY", "")
WEBPUSH_VAPID_CLAIMS_EMAIL = os.environ.get(
    "WEBPUSH_VAPID_CLAIMS_EMAIL", "reservations@graysontowncar.com"
)
# PAUSED by default (founder call, 2026-06-11): the bell / subscriptions / test
# notification stay live so devices can enroll, but AUTOMATIC schedule-change
# notifications (new/removed/retimed/cancelled trip) don't send until this is
# flipped to "true". Founder wants it on only after his sandbox work lands.
WEBPUSH_AUTO_NOTICES = os.environ.get("WEBPUSH_AUTO_NOTICES", "False").lower() == "true"

# Google Maps (Distance Matrix API for driver route preview)
GOOGLE_MAPS_API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY", "")

# Twilio (next-day confirmation SMS)
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = os.environ.get("TWILIO_PHONE_NUMBER", "")

# Founders who get SMS alerts on every new driver time-off request.
# Env override (comma-separated) takes precedence so prod doesn't need a code change.
TIMEOFF_NOTIFY_PHONES = [
    p.strip() for p in os.environ.get(
        "TIMEOFF_NOTIFY_PHONES",
        "+14078200072,+14076339901",
    ).split(",") if p.strip()
]

# Who gets a text when an operator declines a farmed-out job. Empty by default:
# the decline still unassigns the leg and raises a KEOI flag on the board, so
# nothing is lost without it. Set FARMOUT_NOTIFY_PHONES to switch texting on.
FARMOUT_NOTIFY_PHONES = [
    p.strip() for p in os.environ.get("FARMOUT_NOTIFY_PHONES", "").split(",") if p.strip()
]

# ── Early-morning driver wake-up checks ──────────────────────────────────
# Drivers whose FIRST pickup of the day is before WAKEUP_EARLY_CUTOFF_HOUR
# get a wake-up text with a tap-to-confirm link (T-90), then a phone call
# (T-55, or T-90 when the first job is a far/cruise run — the driver has to
# leave home much earlier), and if still unconfirmed the owners get
# called + texted (T-50). Founder-set ladder 2026-06-11.
# Master switch defaults OFF: the local DB carries REAL driver phone
# numbers, so a dev runserver with Twilio creds must never place 4 AM calls.
WAKEUP_CHECKS_ENABLED = os.environ.get("WAKEUP_CHECKS_ENABLED", "False").lower() == "true"
WAKEUP_EARLY_CUTOFF_HOUR = int(os.environ.get("WAKEUP_EARLY_CUTOFF_HOUR", "7"))
WAKEUP_SMS_LEAD_MIN = int(os.environ.get("WAKEUP_SMS_LEAD_MIN", "90"))
WAKEUP_CALL_LEAD_MIN = int(os.environ.get("WAKEUP_CALL_LEAD_MIN", "55"))
WAKEUP_CALL_LEAD_FAR_MIN = int(os.environ.get("WAKEUP_CALL_LEAD_FAR_MIN", "90"))
WAKEUP_ESCALATE_LEAD_MIN = int(os.environ.get("WAKEUP_ESCALATE_LEAD_MIN", "50"))
# Voice for every spoken line (wake-up call, owner alert, keypress replies).
# Twilio <Say> voice id — generative tier sounds the most human. Empty string
# falls back to Twilio's basic default voice.
WAKEUP_VOICE = os.environ.get("WAKEUP_VOICE", "Polly.Joanna-Generative")
# categorize_location() buckets that mark the first job far/cruise (earlier
# call): Port Canaveral = cruise transfer, SFB = Sanford, 'Other' = the
# far/odd catch-all (Tampa, Melbourne, ...). Over-matching is safe — the
# call just comes earlier.
WAKEUP_FAR_CATEGORIES = [
    c.strip() for c in os.environ.get(
        "WAKEUP_FAR_CATEGORIES", "Port Canaveral Area,SFB Terminal,Other"
    ).split(",") if c.strip()
]
# A check created late (leg assigned/retimed inside the window) still ramps
# SMS → call → owners with at least this many minutes between steps, instead
# of firing all three at once.
WAKEUP_MIN_STEP_GAP_MIN = int(os.environ.get("WAKEUP_MIN_STEP_GAP_MIN", "10"))
# Who gets the escalation call/text. Defaults to the time-off founder list.
WAKEUP_NOTIFY_PHONES = [
    p.strip() for p in os.environ.get("WAKEUP_NOTIFY_PHONES", "").split(",") if p.strip()
] or TIMEOFF_NOTIFY_PHONES

# Who gets a text when a driver uploads a permit/DOT-card photo through the
# self-service My Documents page. Those two have no OCR, so this is the ONLY
# signal that a scan is sitting in S3 waiting for staff to transcribe it —
# without it the driver-facing "the office will fill in the details" promise
# has nothing behind it. Defaults to the time-off founder list.
DOCUMENT_UPLOAD_NOTIFY_PHONES = [
    p.strip() for p in os.environ.get("DOCUMENT_UPLOAD_NOTIFY_PHONES", "").split(",") if p.strip()
] or TIMEOFF_NOTIFY_PHONES

# GoHighLevel Settings
GHL_API_KEY = os.environ.get("GHL_API_KEY", "")
GHL_LOCATION_ID = os.environ.get("GHL_LOCATION_ID", "")

# Base URL used when building absolute links from background contexts
# (no incoming request). Used by flight-verification emails and the unpaid
# payment-reminder engine to produce Stripe checkout links.
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "https://www.graysontowncar.com").rstrip("/")

# Scheduled tasks are handled by ghl_integration.scheduler (background thread).
# No Celery required — the scheduler runs batch_send_unsent_leads and
# process_follow_up_batch every 30 minutes automatically.

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Crispy forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django Toolbar
INTERNAL_IPS = [
    "127.0.0.1",
]

# EMAIL Setting
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = 'Grayson Towncar <reservations@graysontowncar.com>'
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", 18000))

CSRF_TRUSTED_ORIGINS = [
    "https://grayson-towncar-production.up.railway.app",
    "https://*.railway.app",
    "https://*.app",
    "https://graysontowncar.com",
    "https://www.graysontowncar.com",
    ]

# strip(): a stray newline/space/quote pasted into the Railway variable makes every
# webhook signature check fail with "No signatures found matching the expected signature".
STRIPE_WEBHOOK_SECRET = (
    os.environ.get("STRIPE_WEBHOOK_SECRET", "").strip().strip("\"'").strip()
)

SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 31536000  # 1 year — required for the preload flag below to be valid
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# AWS Configurations
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME"),
            "region_name": os.getenv("AWS_S3_REGION_NAME", "us-east-1"),
            "custom_domain": "media.graysontowncar.com",
            "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
            "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# .env is loaded above, so real AWS credentials are live during `manage.py test`
# too. Without this, ANY test that saves a FileField — a driver's licence scan,
# a vehicle photo — uploads its fixture into the production media bucket and
# leaves it there. Keep test files in memory instead.
if TESTING:
    STORAGES["default"] = {"BACKEND": "django.core.files.storage.InMemoryStorage"}

DATE_FORMAT = "Y-m-d"
TIME_FORMAT = "g:i A"  # 12-hour format with AM/PM
DATETIME_FORMAT = "Y-m-d g:i A"
SHORT_DATE_FORMAT = "m/d/Y"
SHORT_DATETIME_FORMAT = "m/d/Y g:i A"
TIME_ZONE = "America/New_York"
USE_I18N = False
USE_TZ = True
USE_L10N = False
ADMIN_DATETIME_FORMAT = "g:i A"
ADMIN_DATE_FORMAT = "m/d/Y"  #
ADMIN_TIME_FORMAT = "g:i A"

# ── Session settings ──
# Keep drivers and staff logged in for 90 days
SESSION_COOKIE_AGE = 60 * 60 * 24 * 90  # 90 days in seconds
# Was True (rolling expiry), but that UPDATE-d a django_session row on EVERY
# request and hit the web statement_timeout under load -> SessionInterrupted 500s
# (outage 2026-07-18). OFF: expiry counts from the last session write instead of
# last activity; with a 90-day age that is plenty for drivers/staff.
SESSION_SAVE_EVERY_REQUEST = False        # was True — see note (2026-07-18)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False   # Persist across browser restarts

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_JQUERY_URL = "https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"

# Simple email configuration - no Celery needed for 40-80 emails/day

CKEDITOR_CONFIGS = {
    "default": {
        "skin": "moono-lisa",
        "toolbar": "full",
        "height": 300,
        "width": "100%",
    },
    "awesome_ckeditor": {
        "toolbar": "Custom",
        "toolbar_Custom": [
            ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript"],
            ["NumberedList", "BulletedList", "-", "Outdent", "Indent", "Blockquote"],
            ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"],
            ["Link", "Unlink", "Anchor"],
            ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe"],
            ["Styles", "Format", "Font", "FontSize"],
            ["TextColor", "BGColor"],
            ["Maximize", "ShowBlocks", "Source"],
        ],
        "filebrowserBrowseUrl": "/ckeditor/browse/",
        "filebrowserUploadUrl": "/ckeditor/upload/",
        "extraPlugins": ",".join(
            [
                "uploadimage",
                "autolink",
                "image2",
                "autoembed",
                "embedsemantic",
                "autogrow",
                "widget",
                "lineutils",
                "dialog",
                "dialogui",
                "elementspath",
            ]
        ),
        "height": 400,
        "width": "100%",
    },
}

JAZZMIN_SETTINGS = {
    "default_theme_mode": "light",
    "changeform_format": "single",
    "show_ui_builder": True,
    "custom_css": "admin/admin_overrides.css",
    "hide_models": ["reservations.Leg"],
    "custom_links": {
        "reservations": [
            {
                "name": "Today's Trips",
                "url": "/admin/reservations/reservation/?pickup_date__gte=today",
                "icon": "fa fa-calendar-day",
            }
        ],
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-navy",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "simplex",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-outline-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

# Mismatch threshold (minutes) used by the flight refresh review summary to
# decide when pickup vs flight arrival is "off enough" to flag.
FLIGHT_REVIEW_MISMATCH_THRESHOLD_MINUTES = 30

# Split-stream logging: INFO/WARNING -> stdout, ERROR/CRITICAL -> stderr.
# Railway derives severity from the stream, so a bare StreamHandler (stderr)
# tags every line severity=error and nothing is filterable/alertable.
# All app loggers (perf, dispatching.*, payment.*, django.*) propagate to root.
# Do NOT call logging.basicConfig() in modules — it stacks a second root
# handler on stderr and undoes this split.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "below_error": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: record.levelno < logging.ERROR,
        },
    },
    "formatters": {
        "console": {"format": "%(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "filters": ["below_error"],
            "formatter": "console",
        },
        "stderr": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
            "level": "ERROR",
            "formatter": "console",
        },
    },
    "root": {"handlers": ["stdout", "stderr"], "level": "INFO"},
}
