# Generated by Django 5.1.4 on 2025-04-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("agency_name", models.CharField(max_length=200)),
                (
                    "agency_website",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("google", "Google Search"),
                            ("social_media", "Social Media"),
                            ("referral", "Referral from another Agent"),
                            ("client", "Client Recommendation"),
                            ("conference", "Industry Conference"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=60,
                    ),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
