# Generated by Django 5.1.4 on 2025-05-08 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_newslettersignup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsLetterSignup",
        ),
    ]
