# Generated by Django 5.1.4 on 2025-05-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_delete_newslettersignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
