# Generated by Django 5.1.4 on 2025-05-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriptionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("email", models.EmailField(max_length=254)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="users_newsl_ip_addr_417296_idx",
                    )
                ],
            },
        ),
    ]
