# Generated by Django 5.1.4 on 2025-05-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_travelagent"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelagent",
            name="agency_email",
            field=models.EmailField(
                blank=True,
                help_text="Your agency's email address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelagent",
            name="agent_name",
            field=models.CharField(
                default="john", help_text="Your full name", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travelagent",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="travelagent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="travelagent",
            name="payment_info",
            field=models.CharField(
                default="john",
                help_text="Enter your payment information (e.g., PayPal email, Venmo username, Cash App $username, Zelle email/phone, or bank details)",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
