# Generated by Django 5.1.4 on 2025-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_travelagent_agency_email_travelagent_agent_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelagent",
            name="agent_name",
            field=models.CharField(
                blank=True, help_text="Your full name", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="travelagent",
            name="payment_info",
            field=models.CharField(
                blank=True,
                help_text="Enter your payment information (e.g., PayPal email, Venmo username, Cash App $username, Zelle email/phone, or bank details)",
                max_length=200,
                null=True,
            ),
        ),
    ]
