# Generated by Django 5.1.4 on 2025-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_travelagent_agent_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelagent",
            name="agency_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
