# Generated by Django 5.1.4 on 2025-05-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0031_reservation_commission_paid_and_more"),
        ("users", "0014_alter_travelagent_agency_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelagent",
            name="agency_email",
        ),
        migrations.AlterField(
            model_name="travelagent",
            name="payment_info",
            field=models.CharField(
                blank=True,
                help_text="Preferred Way to Get Paid & Information - Paypal/Zelle/CashApp/Bank Info etc.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CommissionPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payout_period_start", models.DateField()),
                ("payout_period_end", models.DateField()),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.travelagent",
                    ),
                ),
                ("reservations", models.ManyToManyField(to="reservations.reservation")),
            ],
        ),
    ]
