# Generated by Django 5.1.4 on 2025-05-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_travelagent_last_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="travelagent",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("venmo", "Venmo"),
                    ("zelle", "Zelle"),
                    ("cashapp", "Cash App"),
                    ("bank", "Bank Transfer"),
                    ("check", "Check"),
                    ("other", "Other"),
                ],
                help_text="Select your preferred payment method",
                max_length=20,
                null=True,
            ),
        ),
    ]
