# Generated by Django 5.1.4 on 2025-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_commissionpayout_created_at_contactusform_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelagent",
            name="unpaid_commissions",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
