# Generated by Django 5.1.4 on 2025-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_travelagent_unpaid_commissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commissionpayout",
            name="created_at",
        ),
        migrations.AddField(
            model_name="travelagent",
            name="pending_commissions",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
