# Generated by Django 5.1.4 on 2025-05-16 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_remove_commissionpayout_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelagent",
            name="total_earned_commission",
        ),
    ]
