# Generated by Django 5.1.4 on 2025-05-19 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_travelagent_total_earned_commission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("payment_info", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paypal", "PayPal"),
                            ("venmo", "Venmo"),
                            ("zelle", "Zelle"),
                            ("cashapp", "Cash App"),
                            ("bank", "Bank Transfer"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="agency_logos/"),
                ),
                (
                    "total_paid_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total commission paid to this agency across all agents",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "head",
                    models.ForeignKey(
                        help_text="User who manages this agency and can see all agents' data",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_agency",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
            },
        ),
        migrations.AddField(
            model_name="travelagent",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="users.agency",
            ),
        ),
    ]
