# Generated by Django 5.1.4 on 2025-05-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_agencycommissionpayout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency", "Agency"),
                    ("paypal", "PayPal"),
                    ("venmo", "Venmo"),
                    ("zelle", "Zelle"),
                    ("cashapp", "Cash App"),
                    ("bank", "Bank Transfer"),
                    ("check", "Check"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="travelagent",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency", "Agency"),
                    ("paypal", "PayPal"),
                    ("venmo", "Venmo"),
                    ("zelle", "Zelle"),
                    ("cashapp", "Cash App"),
                    ("bank", "Bank Transfer"),
                    ("check", "Check"),
                    ("other", "Other"),
                ],
                help_text="Select your preferred payment method",
                max_length=20,
                null=True,
            ),
        ),
    ]
