# Generated by Django 5.1.4 on 2025-05-25 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_agency_payment_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="head",
        ),
        migrations.AddField(
            model_name="agency",
            name="heads",
            field=models.ManyToManyField(
                blank=True,
                help_text="User who manages this agency and can see all agents' data",
                related_name="managed_agency",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commissionpayout",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_payouts",
                to="users.agency",
            ),
        ),
        migrations.AddField(
            model_name="travelagent",
            name="agency_handles_payment",
            field=models.BooleanField(
                default=False,
                help_text="If checked, commission payments will be made to the agency instead of directly to the agent",
            ),
        ),
    ]
