# Generated by Django 5.1.4 on 2026-01-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_agency_head_agency_heads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
