# Generated by Django 5.1.4 on 2026-01-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_contactusform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusform',
            name='contacted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when form was marked as contacted', null=True),
        ),
    ]
