# Generated by Django 5.1.4 on 2026-02-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_contactusform_contacted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelagent",
            name="include_in_confirmation_sms",
            field=models.BooleanField(
                default=False,
                help_text="If checked, confirmation texts to the guest will mention that the trip was booked through this agent/agency",
            ),
        ),
    ]
