# Generated by ChatGPT on 2026-02-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_add_travel_agent_include_in_confirmation_sms"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="travelagent",
                    name="include_in_confirmation_sms",
                    field=models.BooleanField(
                        default=False,
                        help_text=(
                            "If checked, confirmation texts to the guest will "
                            "mention that the trip was booked through this "
                            "agent/agency"
                        ),
                    ),
                ),
            ],
        ),
    ]
