# Generated by Django 5.1.4 on 2026-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_travelagent_include_in_confirmation_sms_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycommissionpayout',
            name='payment_method_used',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('paypal', 'PayPal'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('cashapp', 'Cash App'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agencycommissionpayout',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='payment_method_used',
            field=models.CharField(blank=True, choices=[('agency', 'Agency'), ('paypal', 'PayPal'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('cashapp', 'Cash App'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
