# Generated by Django 5.1.4 on 2026-05-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_payout_reference_and_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerform',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='partnerform',
            name='contacted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this inquiry was marked as contacted.', null=True),
        ),
        migrations.AddField(
            model_name='partnerform',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes from staff about this partner inquiry.'),
        ),
        migrations.AddField(
            model_name='partnerform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20),
        ),
    ]
