# Generated by Django 5.1.4 on 2026-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_partnerform_options_partnerform_contacted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerform',
            name='agency_size',
            field=models.CharField(blank=True, choices=[('solo', 'Just me (solo agent)'), ('2-5', '2–5 agents'), ('6-20', '6–20 agents'), ('21-50', '21–50 agents'), ('50+', '50+ agents')], help_text='Roughly how many travel agents work at this agency.', max_length=10),
        ),
    ]
