# Generated by Django 5.1.4 on 2026-06-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_partnerform_agency_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerform',
            name='agency_size',
            field=models.CharField(blank=True, choices=[('solo', 'Solo advisor'), ('2-5', '2–5 agents'), ('6-20', '6–20 agents'), ('21-50', '21–50 agents'), ('50+', '50+ agents')], help_text='Roughly how many travel agents work at this agency.', max_length=10),
        ),
    ]
