# Generated by Django 5.1.4 on 2026-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_partnerform_agency_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_fleet_manager',
            field=models.BooleanField(default=False, help_text='Runs the fleet. Lands on the Fleet desk after login, sees the fleet top bar, and receives the fleet alert texts (if enabled).'),
        ),
    ]
