# Generated by Django 5.1.4 on 2026-09-07 20:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0129_legclientmessage'),
        ('users', '0033_alter_partnerform_agency_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('state', models.CharField(db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_id', models.UUIDField(null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('disclosure_version', models.CharField(blank=True, max_length=30)),
                ('disclosed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_payee', models.CharField(choices=[('direct', 'Pay me directly'), ('agency', 'Pay through my agency')], max_length=10)),
                ('offered_payee', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(choices=[('unmatched', 'Unmatched'), ('ambiguous', 'Ambiguous'), ('candidate', 'Candidate'), ('payment_pending', 'Payment_Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='unmatched', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='users.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_claims', to='users.travelagent')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=200)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='users.agency')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBackfill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.JSONField(default=list)),
                ('change_visibility', models.BooleanField(default=True)),
                ('change_payee', models.BooleanField(default=False)),
                ('payee', models.CharField(default='direct', max_length=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.agency')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold', models.CharField(blank=True, max_length=100)),
                ('legacy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_contexts', to='users.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_contexts', to='users.travelagent')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_contexts', to='users.affiliationclaim')),
                ('payee_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_contexts', to='users.agency')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_context', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveBigIntegerField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_email', models.EmailField(blank=True, max_length=254)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(blank=True, max_length=30)),
                ('terms_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_booking_at', models.DateTimeField(blank=True, null=True)),
                ('legacy', models.BooleanField(default=False)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerform')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('inquiry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.partnerform')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('authority', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('information', 'Information'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.agency')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'information'])), fields=('applicant',), name='one_open_agency_application')],
            },
        ),
        migrations.CreateModel(
            name='AgencyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('agent', 'Agent')], default='agent', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('booking_affiliation', models.BooleanField(default=False)),
                ('payee', models.CharField(choices=[('direct', 'Direct'), ('agency', 'Agency'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='users.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('agency', 'user'), name='one_active_agency_membership'), models.UniqueConstraint(condition=models.Q(('active', True), ('booking_affiliation', True)), fields=('user',), name='one_booking_affiliation')],
            },
        ),
    ]
