# Generated by Django 5.1.4 on 2026-09-17 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_fleet_downtime_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shift_end',
            field=models.TimeField(default=datetime.time(16, 0), help_text="End of this person's working day."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift_start',
            field=models.TimeField(default=datetime.time(7, 30), help_text="Start of this person's working day. The fleet inspection round only offers cars that can be walked between these hours."),
        ),
    ]
