# Generated by Django 5.1.4 on 2026-09-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_seed_partner_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNameLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='partneridentity',
            name='registration_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
