# Generated by Django 5.1.4 on 2026-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_username_unique_ignoring_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagent',
            name='bank_account_holder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_routing_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='venmo_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
