# Generated by Django 5.1.4 on 2026-09-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_partnerpayoutadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='bank_account_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_account_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='agency',
            name='bank_routing_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='agency',
            name='paypal_email',
            field=models.EmailField(blank=True, default='', help_text='The email on the PayPal account.', max_length=254),
        ),
        migrations.AddField(
            model_name='agency',
            name='venmo_handle',
            field=models.CharField(blank=True, default='', help_text='Venmo username, without the @.', max_length=64),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_account_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_account_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='bank_routing_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='paypal_email',
            field=models.EmailField(blank=True, default='', help_text='The email on the PayPal account.', max_length=254),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='venmo_handle',
            field=models.CharField(blank=True, default='', help_text='Venmo username, without the @.', max_length=64),
        ),
    ]
