# Generated by Django 5.1.4 on 2026-10-04 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0130_refundrequest_approve_permission'),
        ('users', '0038_convert_old_bank_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('personal', 'Possible personal trip'), ('duplicate', 'Possible duplicate')], max_length=20)),
                ('decision', models.CharField(choices=[('fine', 'Pay as normal'), ('excluded', 'Not commissionable')], max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_checks', to='reservations.reservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reservation', 'kind'), name='one_commission_check_per_kind')],
            },
        ),
    ]
