# Generated by Django 5.1.4 on 2026-09-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_agency_bank_account_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationclaim',
            name='requested_payee',
            field=models.CharField(choices=[('direct', 'Pay directly'), ('agency', 'Pay my agency')], max_length=10),
        ),
    ]
