# Generated by Django 5.1.4 on 2026-09-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_affiliationclaim_requested_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='payout_policy',
            field=models.CharField(choices=[('either', 'Agents may ask to be paid directly'), ('agency', 'Grayson always pays the agency, never the agent')], default='either', help_text="Whether this agency's agents may be paid directly by Grayson.", max_length=10),
        ),
        migrations.AlterField(
            model_name='affiliationclaim',
            name='requested_payee',
            field=models.CharField(choices=[('direct', 'Grayson pays me directly'), ('agency', 'Grayson pays my agency, and my agency pays me')], max_length=10),
        ),
    ]
