# Generated by Django 5.1.4 on 2026-06-17 03:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0115_historicalleg_dispatch_eta_origin_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Destination label, e.g. 'Miami (MIA)'.", max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('origin_label', models.CharField(default='Orlando', help_text='Origin shown to the customer (routes are priced one-way from the Orlando service area).', max_length=80)),
                ('approx_miles', models.PositiveIntegerField(default=0, help_text='Approximate one-way miles (informational only).')),
                ('aliases', models.TextField(blank=True, help_text="Comma-separated alternate names a customer might type (e.g. 'MIA, Miami International, Downtown Miami').")),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeakDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Inclusive — the last peak day.')),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override of the global peak multiplier for this event. Leave blank to use the global value.', max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Peak date',
                'verbose_name_plural': 'Peak dates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gratuity_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Gratuity shown as a separate line on every quote (default 20%).', max_digits=5)),
                ('peak_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Default multiplier applied to the base on peak dates (recommended 1.15–1.50). A PeakDate may override this per event.', max_digits=4)),
                ('round_to_whole_dollars', models.BooleanField(default=True, help_text='Round the final quote (base, gratuity, total) to whole dollars.')),
                ('overtime_increment_minutes', models.PositiveIntegerField(default=30, help_text='Hourly overtime past the minimum is billed in increments of this many minutes.')),
                ('all_inclusive_note', models.CharField(default='All-inclusive — tolls included.', help_text='Shown on city-to-city quotes.', max_length=120)),
                ('hourly_tolls_note', models.CharField(default='Tolls & parking billed at cost.', help_text='Shown on hourly quotes.', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing configuration',
                'verbose_name_plural': 'Pricing configuration',
            },
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable internal key used by the API and quote payloads (e.g. 'towncar', 'sprinter'). Do not change once quotes reference it.", max_length=40, unique=True)),
                ('display_name', models.CharField(help_text="Customer-facing name shown on the site and quotes (e.g. 'Sprinter Van', 'Pax Van').", max_length=60)),
                ('vehicle_type', models.CharField(choices=[('towncar', 'towncar (Towncar)'), ('suv', 'suv (SUV)'), ('mini_van', 'mini_van (Mini Van)'), ('van', 'van (Pax Van)'), ('Van(14 Pax)', 'Van(14 Pax) (Sprinter Van)')], help_text='The rates.Vehicle type this class maps to when a quote converts into a booking. The DB value is never shown to customers.', max_length=20)),
                ('passenger_capacity', models.PositiveIntegerField(default=4, help_text='Shown on the fleet page / quote widget.')),
                ('luggage_capacity', models.PositiveIntegerField(default=3)),
                ('ideal_for', models.CharField(blank=True, help_text="One-line 'ideal for…' blurb shown on the fleet card.", max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers sort first in dropdowns and grids.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle class',
                'verbose_name_plural': 'Vehicle classes',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RouteDistanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_key', models.CharField(db_index=True, max_length=160)),
                ('destination_key', models.CharField(db_index=True, max_length=160)),
                ('origin_text', models.CharField(max_length=200)),
                ('destination_text', models.CharField(max_length=200)),
                ('miles', models.DecimalField(decimal_places=2, max_digits=7)),
                ('source', models.CharField(choices=[('manual', 'Manually entered'), ('distance_matrix', 'Google Distance Matrix'), ('seed', 'Seeded')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Route distance (cache)',
                'verbose_name_plural': 'Route distances (cache)',
                'constraints': [models.UniqueConstraint(fields=('origin_key', 'destination_key'), name='unique_distance_pair')],
            },
        ),
        migrations.CreateModel(
            name='InstantQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_type', models.CharField(choices=[('hourly', 'Hourly charter'), ('city_to_city', 'City-to-city transfer')], max_length=20)),
                ('service_date', models.DateField()),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('loaded_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peak_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gratuity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('all_inclusive', models.BooleanField(default=False)),
                ('price_source', models.CharField(choices=[('route_table', 'Named route table'), ('formula', 'Per-mile formula'), ('hourly', 'Hourly rate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('city_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='pricing.cityroute')),
                ('converted_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='reservations.reservation')),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='pricing.vehicleclass')),
            ],
            options={
                'verbose_name': 'Instant quote',
                'verbose_name_plural': 'Instant quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_hours', models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='Minimum billable hours (default 3).', max_digits=4)),
                ('peak_minimum_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Optional higher minimum on peak dates (e.g. Sprinter = 4 hr on peak). Leave blank to use the normal minimum on peak dates too.', max_digits=4, null=True)),
                ('vehicle_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rate', to='pricing.vehicleclass')),
            ],
            options={
                'ordering': ['vehicle_class__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FallbackFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('per_mile', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum', models.DecimalField(decimal_places=2, help_text='Price floor for this class.', max_digits=8)),
                ('vehicle_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_formula', to='pricing.vehicleclass')),
            ],
            options={
                'ordering': ['vehicle_class__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CityRoutePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='One-way price (USD), tolls included, before gratuity.', max_digits=9)),
                ('city_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.cityroute')),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_prices', to='pricing.vehicleclass')),
            ],
            options={
                'ordering': ['city_route__sort_order', 'vehicle_class__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('city_route', 'vehicle_class'), name='unique_route_class_price')],
            },
        ),
    ]
