# Generated by Django 5.1.4 on 2026-06-17 19:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_seed_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallbackformula',
            name='deadhead_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.80'), help_text='Multiplier on the loaded miles to cover the empty return trip (1.0 = charge loaded miles only, 2.0 = full round-trip). Recommended ~1.8. Applies to this per-mile formula only, never to named-route flat prices. The customer still sees the true loaded miles.', max_digits=4),
        ),
    ]
