# Generated by Django 5.1.4 on 2025-04-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default=0,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
