# Generated by Django 5.1.4 on 2025-04-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_userpayment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayment",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Pending"), ("paid", "Paid")], max_length=50
            ),
        ),
    ]
