# Generated by Django 5.1.4 on 2025-04-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_userpayment_delete_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_checkout_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("pay_now", "Pay Now"), ("pay_later", "Pay Later")],
                        default="pay_now",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("card_saved", "Card Saved"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userpayment",
            name="user",
        ),
    ]
