# Generated by Django 5.1.4 on 2025-04-04 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_payment_remove_userpayment_user"),
        ("reservations", "0005_alter_reservation_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPayment",
        ),
    ]
