# Generated by Django 5.1.4 on 2025-04-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_rename_payment_mode_payment_payment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("pay_now", "Pay Now"), ("pay_later", "Pay Later")],
                default="pay_later",
                max_length=20,
            ),
        ),
    ]
