# Generated by Django 5.1.4 on 2026-01-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, help_text="Payment description (e.g., 'Initial Payment', 'Gratuity 20%', 'Additional Charge')", max_length=255, null=True),
        ),
    ]
