# Generated by Django 5.1.4 on 2026-01-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded from this payment (for partial refunds)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_refund_id',
            field=models.CharField(blank=True, help_text='Stripe refund ID for tracking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('card_saved', 'Card Saved On File'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
