# Generated by Django 5.1.4 on 2025-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="legs",
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
