# Generated by Django 5.1.4 on 2025-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_legs_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
