# Generated by Django 5.1.4 on 2025-05-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0004_driverpayment_legpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="payment_method",
            field=models.CharField(blank=True, default="direct deposit", max_length=50),
        ),
    ]
