# Generated by Django 5.1.4 on 2026-01-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driverpayment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_type',
            field=models.CharField(choices=[('inhouse', 'Inhouse'), ('affiliate', 'Affiliate/Outhouse')], default='affiliate', help_text='Inhouse drivers work for the company and can drive any vehicle. Affiliates are contractors with specific vehicles.', max_length=20),
        ),
    ]
