# Generated by Django 5.1.4 on 2026-01-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_driver_driver_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Driver's phone number", max_length=25, null=True),
        ),
    ]
