# Generated by Django 5.1.4 on 2026-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_driver_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this driver for dispatchers', null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='schedule',
            field=models.CharField(blank=True, help_text="Driver's availability schedule (e.g., 'Mon-Thu: 4AM-4PM, Fri: 6PM-8PM, Sat-Sun: 5AM-5PM')", max_length=255, null=True),
        ),
    ]
