# Generated by Django 5.1.4 on 2026-01-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_drivervehicleassignment'),
        ('drivers', '0009_driver_notes_alter_driver_schedule'),
    ]

    operations = [
    ]
