# Generated by Django 5.1.4 on 2026-01-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0011_fleet_vehicle_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverpayment",
            name="base_pay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total base pay amount (excluding gratuity)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="driverpayment",
            name="gratuity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total gratuity amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legpayment",
            name="base_pay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base pay amount for this leg (excluding gratuity)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legpayment",
            name="gratuity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Gratuity amount for this leg",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="driverpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total payment (base_pay + gratuity)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="legpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total payment (base_pay + gratuity)",
                max_digits=10,
            ),
        ),
    ]
