# Generated by Django 5.1.4 on 2026-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0012_add_driver_pay_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverpayment",
            name="additional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total additional pay amount (e.g., wait time, early morning bonus, etc.)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legpayment",
            name="additional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Additional pay amount for this leg (e.g., wait time, early morning bonus, etc.)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="driverpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total payment (base_pay + gratuity + additional)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="legpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total payment (base_pay + gratuity + additional)",
                max_digits=10,
            ),
        ),
    ]
