# Generated by Django 5.1.4 on 2026-02-10 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_add_driver_additional_field'),
        ('rates', '0017_location_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetvehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Vehicle type/tier for scheduling (e.g. SUV, Van, MiniVan)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.vehicle'),
        ),
    ]
