# Generated by Django 5.1.4 on 2026-02-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_fleetvehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='default_end_hour',
            field=models.IntegerField(default=23, help_text='Default latest hour this driver works until (0-23). Used as default in auto-assign.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='default_preference',
            field=models.CharField(blank=True, default='', help_text='Default trip type preference for auto-assign (e.g., prefer_arrival, only_return).', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='default_start_hour',
            field=models.IntegerField(default=6, help_text='Default earliest hour this driver is available (0-23). Used as default in auto-assign.'),
        ),
    ]
