# Generated by Django 5.1.4 on 2026-02-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_add_driver_schedule_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_available', models.BooleanField(default=True)),
                ('start_hour', models.IntegerField(default=6)),
                ('end_hour', models.IntegerField(default=23)),
                ('preference', models.CharField(blank=True, choices=[('', 'Any'), ('prefer_arrival', 'Prefer Arrivals'), ('prefer_return', 'Prefer Returns'), ('prefer_cruise', 'Prefer Cruises'), ('heavy_arrival', 'Heavy Arrivals'), ('heavy_return', 'Heavy Returns'), ('heavy_cruise', 'Heavy Cruises'), ('only_arrival', 'Arrivals Only'), ('only_return', 'Returns Only'), ('only_cruise', 'Cruises Only')], default='', max_length=30)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='drivers.driver')),
            ],
            options={
                'ordering': ['driver', 'day_of_week'],
                'unique_together': {('driver', 'day_of_week')},
            },
        ),
    ]
