# Generated by Django 5.1.4 on 2026-02-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_add_driver_weekly_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='exclude_from_timing',
            field=models.BooleanField(default=False, help_text="Exclude this driver's completed trips from route timing data. Affiliates are always excluded."),
        ),
    ]
