# Generated by Django 5.1.4 on 2026-02-18 02:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0017_add_exclude_from_timing'),
        ('rates', '0017_location_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='night_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Night pickup bonus (10 PM - 6 AM). Set per driver. $0 for no bonus.', max_digits=6),
        ),
        migrations.CreateModel(
            name='DriverPayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reverse', models.BooleanField(default=False, help_text='False = route direction (origin→dest). True = reverse (dest→origin).')),
                ('base_pay', models.DecimalField(decimal_places=2, help_text='Base pay for this driver/route/vehicle/direction combo', max_digits=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rates', to='drivers.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_pay_rates', to='rates.route')),
                ('vehicle', models.ForeignKey(blank=True, help_text='NULL = same rate for all vehicles on this route.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_pay_rates', to='rates.vehicle')),
            ],
            options={
                'ordering': ['driver', 'route'],
                'indexes': [models.Index(fields=['driver', 'route'], name='drivers_dri_driver__6755ea_idx')],
                'unique_together': {('driver', 'route', 'vehicle', 'is_reverse')},
            },
        ),
    ]
