# Generated by Django 5.1.4 on 2026-02-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0018_driver_pay_rates'),
        ('rates', '0018_populate_location_aliases'),
    ]

    operations = [
        # 1. Drop old unique_together (uses is_reverse)
        migrations.AlterUniqueTogether(
            name='driverpayrate',
            unique_together=set(),
        ),
        # 2. Add new direction field
        migrations.AddField(
            model_name='driverpayrate',
            name='direction',
            field=models.CharField(choices=[('both', 'Both directions'), ('forward', 'Forward (origin \u2192 dest)'), ('reverse', 'Reverse (dest \u2192 origin)')], default='both', help_text="'both' = same rate both ways. 'forward' = origin\u2192dest. 'reverse' = dest\u2192origin.", max_length=10),
        ),
        # 3. Remove old is_reverse field
        migrations.RemoveField(
            model_name='driverpayrate',
            name='is_reverse',
        ),
        # 4. Set new unique_together (uses direction)
        migrations.AlterUniqueTogether(
            name='driverpayrate',
            unique_together={('driver', 'route', 'vehicle', 'direction')},
        ),
    ]
