# Generated by Django 5.1.4 on 2026-03-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0019_direction_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="default_flexible",
            field=models.BooleanField(
                default=False,
                help_text="Flexible drivers have no hard time limits — the planner builds them a reasonable shift using scoring penalties instead of filtering.",
            ),
        ),
        migrations.AddField(
            model_name="driverweeklyschedule",
            name="flexible",
            field=models.BooleanField(
                default=False,
                help_text="No hard time limits — planner builds a reasonable shift via scoring instead of filtering.",
            ),
        ),
    ]
