# Generated by Django 5.1.4 on 2026-04-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0020_driver_default_flexible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='default_max_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Default max hours per day. NULL = no limit.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='default_shift_type',
            field=models.CharField(default='full_day', help_text='Default shift type for days without a weekly override.', max_length=20),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='max_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum hours to schedule this driver per day. NULL = no limit.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='scheduling_notes',
            field=models.CharField(blank=True, default='', help_text='Short note visible to dispatchers on the schedule board.', max_length=200),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('midday', 'Midday'), ('evening', 'Evening'), ('night', 'Night'), ('split', 'Split AM/PM'), ('full_day', 'Full Day'), ('custom', 'Custom')], default='full_day', help_text='Shift classification for dispatchers. Named types auto-set hours and flexibility.', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='default_flexible',
            field=models.BooleanField(default=True, help_text='Flexible = no hard time limits, planner builds a reasonable shift. Uncheck only if driver has strict start/end constraints.'),
        ),
        migrations.AlterField(
            model_name='driverweeklyschedule',
            name='flexible',
            field=models.BooleanField(default=True, help_text='Flexible = no hard time limits, planner builds a reasonable shift. Uncheck only if driver has strict start/end constraints.'),
        ),
    ]
