# Generated by Django 5.1.4 on 2026-04-15 01:07

from django.db import migrations


def infer_shift_type(start_hour, end_hour, flexible):
    """Infer shift_type from existing hours + flexible flag.

    The flexible flag was never exposed in the dispatcher UI, so its value
    is unreliable for intent inference. Classify primarily by hour span.
    """
    span = end_hour - start_hour
    # Wide ranges (14+ hours) are effectively "full day"
    if span >= 14:
        return "full_day"
    # Narrow ranges that fit named shifts
    if end_hour <= 14:
        return "morning"
    if start_hour >= 14:
        return "evening"
    if start_hour >= 10 and end_hour <= 18:
        return "midday"
    if start_hour >= 20:
        return "night"
    # Mid-range spans (8-13 hours) with flexible flag = split
    if flexible and span >= 8:
        return "split"
    return "custom"


def backfill_weekly(apps, schema_editor):
    DriverWeeklySchedule = apps.get_model("drivers", "DriverWeeklySchedule")
    for entry in DriverWeeklySchedule.objects.all():
        entry.shift_type = infer_shift_type(entry.start_hour, entry.end_hour, entry.flexible)
        entry.save(update_fields=["shift_type"])


def backfill_defaults(apps, schema_editor):
    Driver = apps.get_model("drivers", "Driver")
    for driver in Driver.objects.all():
        driver.default_shift_type = infer_shift_type(
            driver.default_start_hour, driver.default_end_hour, driver.default_flexible
        )
        driver.save(update_fields=["default_shift_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0021_add_shift_type_max_hours'),
    ]

    operations = [
        migrations.RunPython(backfill_weekly, migrations.RunPython.noop),
        migrations.RunPython(backfill_defaults, migrations.RunPython.noop),
    ]
