# Generated by Django 5.1.4 on 2026-04-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0022_backfill_shift_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='default_preferred_shift',
            field=models.CharField(blank=True, default='', help_text='Default preferred time of day (morning, evening, etc.).', max_length=20),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='preferred_shift',
            field=models.CharField(blank=True, choices=[('', 'No Preference'), ('morning', 'Prefer Morning'), ('midday', 'Prefer Midday'), ('evening', 'Prefer Evening'), ('night', 'Prefer Night')], default='', help_text='Preferred time of day. Scheduler tries this window first but can assign outside it.', max_length=20),
        ),
    ]
