# Generated by Django 5.1.4 on 2026-04-15 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0023_add_preferred_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=False, help_text='False = driver is off on this date. True = special availability override.')),
                ('reason', models.CharField(choices=[('day_off', 'Day Off'), ('pto', 'PTO'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('other', 'Other')], default='day_off', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='drivers.driver')),
            ],
            options={
                'ordering': ['date', 'driver'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
