# Generated by Django 5.1.4 on 2026-04-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0024_add_driver_date_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetvehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_vehicle_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
