# Generated by Django 5.1.4 on 2026-05-14 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0024_add_driver_date_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverdateoverride',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_driver_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='end_date',
            field=models.DateField(blank=True, help_text='Last day this exception applies. Leave blank for a single-day exception.', null=True),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='end_time',
            field=models.TimeField(blank=True, help_text='For partial-day exceptions: the end of the affected window.', null=True),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='exception_type',
            field=models.CharField(choices=[('off', 'Off (full day)'), ('available_until', 'Available until time'), ('available_after', 'Available after time'), ('available_window', 'Available only during window'), ('unavailable_window', 'Unavailable during window'), ('flexible', 'Flexible (override off-day)'), ('note_only', 'Note only')], default='off', help_text='What kind of exception this is.', max_length=24),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='start_time',
            field=models.TimeField(blank=True, help_text='For partial-day exceptions: the start of the affected window.', null=True),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driverdateoverride',
            name='date',
            field=models.DateField(help_text='First day this exception applies.'),
        ),
        migrations.AlterField(
            model_name='driverdateoverride',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Derived: False for full-day Off; True for partial-day or flexible exceptions.'),
        ),
        migrations.AlterField(
            model_name='driverdateoverride',
            name='reason',
            field=models.CharField(choices=[('day_off', 'Day Off'), ('pto', 'PTO'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('appointment', 'Appointment'), ('other', 'Other')], default='day_off', max_length=20),
        ),
    ]
