# Generated by Django 5.1.4 on 2026-05-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0025_extend_driverdateoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdateoverride',
            name='reason',
            field=models.CharField(choices=[('day_off', 'Day Off'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('appointment', 'Appointment'), ('other', 'Other')], default='day_off', max_length=20),
        ),
    ]
