# Generated by Django 5.1.4 on 2026-05-18 20:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0026_remove_pto_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='gusto_business_name',
            field=models.CharField(blank=True, default='', help_text='Business / DBA name if contractor is paid as a business entity.', max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='gusto_contractor_id',
            field=models.CharField(blank=True, default='', help_text="Gusto's internal contractor ID, if known. Optional alternative to last-4.", max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='gusto_first_name',
            field=models.CharField(blank=True, default='', help_text='Legal first name on file with Gusto. Leave blank to use profile first name.', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='gusto_last_name',
            field=models.CharField(blank=True, default='', help_text='Legal last name on file with Gusto. Leave blank to use profile last name.', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='gusto_payment_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('individual', 'Individual (SSN)'), ('business', 'Business (EIN)')], default='', help_text='How this contractor is paid in Gusto. Informational only.', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='gusto_ssn_ein_last4',
            field=models.CharField(blank=True, default='', help_text='Last 4 digits of SSN or EIN, e.g. "9579" or "*9579". Used for Gusto matching only. Do NOT enter the full number.', max_length=5),
        ),
        migrations.CreateModel(
            name='DriverPaymentExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_date', models.DateField(help_text='Payroll period start (Monday typically).')),
                ('to_date', models.DateField(help_text='Payroll period end (Sunday typically).')),
                ('csv_file_name', models.CharField(max_length=255)),
                ('selected_driver_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('exported_payment_ids', models.JSONField(blank=True, default=list, help_text='List of DriverPayment IDs included in this CSV.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gusto_csv_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver payment Gusto export',
                'verbose_name_plural': 'Driver payment Gusto exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
