# Generated by Django 5.1.4 on 2026-05-19 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0027_gusto_export'),
        ('reservations', '0102_reservation_unpaid_completed_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legpayment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The line's amount at the moment of processing. Captured on first edit so subsequent edits don't lose the initial value.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='legpayment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='legpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='legpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leg_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legpayment',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='legpayment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legpayment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_leg_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DriverPayoutAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('void_line', 'Void line'), ('edit_amount', 'Edit amount'), ('add_missing_leg', 'Add missing leg')], max_length=20)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Line amount before this adjustment. Null for add_missing_leg.', max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Line amount after this adjustment. Null for void_line.', max_digits=10, null=True)),
                ('delta', models.DecimalField(decimal_places=2, help_text='Signed change applied to DriverPayment.amount.', max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('statement_was_emailed', models.BooleanField(default=False)),
                ('statement_was_exported', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payout_adjustments', to=settings.AUTH_USER_MODEL)),
                ('leg', models.ForeignKey(blank=True, help_text='Denormalized — same as leg_payment.leg when present; set directly for add_missing_leg.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_adjustments', to='reservations.leg')),
                ('leg_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='drivers.legpayment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='drivers.driverpayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='drivers_dri_payment_9e2817_idx')],
            },
        ),
    ]
