# Generated by Django 5.1.4 on 2026-05-25 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0028_payout_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdateoverride',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Founder/dispatcher who approved or denied this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_driver_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='denial_reason',
            field=models.CharField(blank=True, default='', help_text='Shown to the driver when their request is denied.', max_length=200),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending review'), ('denied', 'Denied'), ('cancelled', 'Cancelled by driver')], default='approved', help_text="Approval state. Only 'approved' rows affect schedule availability.", max_length=12),
        ),
        migrations.AddField(
            model_name='driverdateoverride',
            name='submitted_by_driver',
            field=models.BooleanField(default=False, help_text='True when the driver submitted this themselves via the driver portal.'),
        ),
    ]
