# Generated by Django 5.1.4 on 2026-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0029_add_timeoff_approval_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this driver from the directory and assignment pickers. Keeps historical legs/payments intact — use this for drivers who no longer work with us or are on extended leave.",
            ),
        ),
    ]
