# Generated by Django 5.1.4 on 2026-06-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0030_add_driver_is_active"),
        ("rates", "0023_vehicle_requires_certification"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="certified_vehicle_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restricted vehicle types this driver is cleared to drive (e.g. the Sprinter / 14-pax van). Non-restricted types need no entry here.",
                related_name="certified_drivers",
                to="rates.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="preferred_vehicle_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vehicle type(s) this driver prefers to drive (soft preference — informational).",
                related_name="preferring_drivers",
                to="rates.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="preferred_vehicles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific vehicle unit(s) this driver prefers / usually drives, e.g. their regular car (soft preference — informational).",
                related_name="preferring_drivers",
                to="drivers.fleetvehicle",
            ),
        ),
    ]
