# Generated by Django 5.1.4 on 2026-06-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0032_certify_sprinter_drivers"),
        ("rates", "0023_vehicle_requires_certification"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="vehicle_preference_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No vehicle preference (display only)"),
                    ("prefer", "Prefer these vehicle types"),
                    ("heavy", "Mostly these vehicle types"),
                    ("only", "Only these vehicle types"),
                ],
                default="",
                help_text="How strongly auto-assign should steer this driver toward the preferred vehicle type(s) above. Works exactly like the trip-type preference. 'Only' hard-restricts; leave blank for no scheduler effect.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="preferred_vehicle_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vehicle type(s) this driver prefers to drive. Soft/informational unless a Vehicle preference mode is selected below — then auto-assign uses it.",
                related_name="preferring_drivers",
                to="rates.vehicle",
            ),
        ),
    ]
