# Generated by Django 5.1.4 on 2026-06-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0033_driver_vehicle_preference_mode_and_more"),
        ("rates", "0023_vehicle_requires_certification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="vehicle_preference_mode",
        ),
        migrations.AlterField(
            model_name="driver",
            name="preferred_vehicle_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Vehicle type(s) this driver prefers to drive (soft preference — informational).",
                related_name="preferring_drivers",
                to="rates.vehicle",
            ),
        ),
    ]
