# Generated by Django 5.1.4 on 2026-06-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0034_remove_driver_vehicle_preference_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_last_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_last_location_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reverse-geocoded label from Samsara (e.g. 'near MCO Terminal A').",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_last_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_last_seen_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of the Samsara GPS sample itself.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When we last successfully polled Samsara for this vehicle (diagnostic).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_movement_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="driving / idle (derived from Samsara speed).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_vehicle_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Samsara vehicle id. Blank = not onboarded; renders no live position.",
                max_length=64,
            ),
        ),
    ]
