# Generated by Django 5.1.4 on 2026-06-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0035_fleetvehicle_samsara_last_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetvehicle",
            name="samsara_stationary_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When the vehicle last stopped moving (cleared when it drives). Drives the 'vehicle not moving' dwell detection.",
                null=True,
            ),
        ),
    ]
