# Generated by Django 5.1.4 on 2026-06-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0036_fleetvehicle_samsara_stationary_since"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_vehicle_tier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Highest vehicle class this affiliate can serve: one of towncar / mini_van / suv / van / Van(14 Pax) (scheduler.VEHICLE_TIER_ORDER). Blank = no capability cap (the rate card alone gates eligibility). REQUIRED for a flat all-vehicle card, whose single NULL-vehicle row otherwise matches every class.",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_mode",
                    models.CharField(
                        choices=[
                            (
                                "single_chain",
                                "Single vehicle (one feasibility chain, no count cap)",
                            ),
                            ("count_cap", "Daily leg-count cap (finite seats/day)"),
                            (
                                "fleet",
                                "Fleet (treated as a higher count cap; true parallel chains deferred)",
                            ),
                        ],
                        default="single_chain",
                        help_text="How the optimizer rations this affiliate's daily capacity.",
                        max_length=20,
                    ),
                ),
                (
                    "daily_cap",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Legs/day for count_cap (e.g. Anthony 12) or fleet capacity for fleet mode. Ignored for single_chain (capacity = the feasibility chain). NULL = unlimited count.",
                        null=True,
                    ),
                ),
                (
                    "no_pickup_at_port_sanford",
                    models.BooleanField(
                        default=False,
                        help_text="Affiliate may DROP at Port Canaveral / Sanford but never PICK UP there (no permit). Excludes any leg ORIGINATING at Port/Sanford from this affiliate (Waleed's rule).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes about this affiliate's capability / capacity / permits.",
                    ),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        help_text="The affiliate this config describes (driver_type='affiliate').",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_profile",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "ordering": ["driver"],
            },
        ),
    ]
