# Generated by Django 5.1.4 on 2026-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0037_affiliateprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivervehicleassignment",
            name="planned_end_hour",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drivervehicleassignment",
            name="planned_start_hour",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
