# Generated by Django 5.1.4 on 2026-06-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0038_dva_planned_share_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetvehicle",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Inactive vehicles can't be assigned and are hidden from selection/availability surfaces. Legs already on the vehicle still render so history is preserved.",
            ),
        ),
    ]
