# Generated by Django 5.1.4 on 2026-06-11 07:14

import django.db.models.deletion
import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0040_driverpushsubscription"),
        ("reservations", "0113_historicalleg_dispatch_vehicle_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverWakeupCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Service date of the early first pickup.",
                    ),
                ),
                (
                    "first_pickup_at",
                    models.DateTimeField(
                        help_text="The driver's first pickup — every deadline is relative to this. Re-synced each sweep while the check is unacknowledged."
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=drivers.models._wakeup_token,
                        help_text="Capability token for the no-login tap-to-confirm link.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acked", "Confirmed awake"),
                            ("escalated", "Escalated to owners"),
                            (
                                "cancelled",
                                "Cancelled (no longer an early first pickup)",
                            ),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("push_sent_at", models.DateTimeField(blank=True, null=True)),
                ("call_started_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ack_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="link (tapped the SMS link), call (pressed a key), admin (manual).",
                        max_length=12,
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Timestamped breadcrumbs per step.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wakeup_checks",
                        to="drivers.driver",
                    ),
                ),
                (
                    "leg",
                    models.ForeignKey(
                        blank=True,
                        help_text="The first leg the check was built around (informational).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wakeup_checks",
                        to="reservations.leg",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "first_pickup_at"],
                "unique_together": {("driver", "date")},
            },
        ),
    ]
