# Generated by Django 5.1.4 on 2026-06-12 20:20

from django.db import migrations, models


def _normalize_tiers(apps, schema_editor):
    """Canonicalize legacy free-typed max_vehicle_tier values (the field used to be free text and
    the engine matches case-sensitively — a typed 'SUV' silently excluded the affiliate from
    every job). Maps case/punctuation variants onto scheduler.VEHICLE_TIER_ORDER values; truly
    unknown strings are left for the admin dropdown to force-fix."""
    AffiliateProfile = apps.get_model("drivers", "AffiliateProfile")

    def squash(s):
        return "".join(ch for ch in s.lower() if ch.isalnum())

    canonical = ["towncar", "mini_van", "suv", "van", "Van(14 Pax)"]
    lookup = {squash(c): c for c in canonical}
    lookup.update({"van14": "Van(14 Pax)", "14pax": "Van(14 Pax)", "van14p": "Van(14 Pax)"})

    for prof in AffiliateProfile.objects.exclude(max_vehicle_tier=""):
        fixed = lookup.get(squash(prof.max_vehicle_tier))
        if fixed and fixed != prof.max_vehicle_tier:
            prof.max_vehicle_tier = fixed
            prof.save(update_fields=["max_vehicle_tier"])


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0041_driverwakeupcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateprofile',
            name='max_vehicle_tier',
            field=models.CharField(blank=True, choices=[('', '— no cap (rate card alone gates; vans still need an explicit van rate row)'), ('towncar', 'Towncar'), ('mini_van', 'Mini Van'), ('suv', 'SUV'), ('van', 'Van'), ('Van(14 Pax)', 'Van (14 Pax)')], default='', help_text='Highest vehicle class this affiliate can serve. Blank = no capability cap (the rate card alone gates eligibility — but van/14-pax jobs then require an explicit van rate row; a flat all-vehicle card never auto-claims them).', max_length=20),
        ),
        migrations.RunPython(_normalize_tiers, migrations.RunPython.noop),
    ]
