# Generated by Django 5.1.4 on 2026-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0042_alter_affiliateprofile_max_vehicle_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetvehicle',
            name='max_luggage_capacity',
            field=models.PositiveIntegerField(blank=True, help_text="Scheduler-only suitcase cap for this specific unit. NULL = use the vehicle type's luggage capacity (no per-unit cap).", null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='max_passenger_capacity',
            field=models.PositiveIntegerField(blank=True, help_text="Scheduler-only passenger cap for this specific unit. NULL = use the vehicle type's capacity (no per-unit cap).", null=True),
        ),
    ]
