# Generated by Django 5.1.4 on 2026-07-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0043_fleetvehicle_max_luggage_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full time — works every available day'), ('part_time', 'Part time — available days are offers, not commitments')], default='', help_text='Full time means they are expected to work every day they are marked available, so an unworked available day is a real gap. Part time means available days are offers they need not take. Leave blank if unsure — the load reports show unlabelled drivers separately rather than guessing, because the wrong label inverts what every number means.', max_length=20),
        ),
    ]
