# Generated by Django 5.1.4 on 2026-08-05 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0044_driver_employment_type'),
        ('rates', '0024_merge_duplicate_universal_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(help_text="Feed key: 'vehicle_stats' | 'faults' | 'nightly_reconcile'.", max_length=32, unique=True)),
                ('cursor', models.TextField(blank=True, default='', help_text='Resume cursor for a DELTA feed only. Blank for snapshot polls.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['feed'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDayReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='LOCAL service date (America/New_York). Always derive with timezone.localdate() — USE_TZ is on, so a naive UTC date would put the 8pm-to-midnight window on the wrong day.')),
                ('samsara_vehicle_id', models.CharField(blank=True, default='', max_length=64)),
                ('start_odometer_meters', models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True)),
                ('end_odometer_meters', models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True)),
                ('start_gps_distance_meters', models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True)),
                ('end_gps_distance_meters', models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True)),
                ('miles_driven', models.DecimalField(blank=True, decimal_places=1, help_text='DERIVED from start/end via dispatching.mileage. NULL = unknown (render as em-dash), 0 = provably did not move.', max_digits=8, null=True)),
                ('mileage_source', models.CharField(blank=True, default='', help_text='obd (exact) / gps (estimate) / none. Stored so the UI can mark provenance and an audit can tell a reading from an estimate.', max_length=8)),
                ('mileage_note', models.CharField(blank=True, default='', help_text='Why a reading was rejected or fell back. Diagnostics only.', max_length=200)),
                ('sample_count', models.PositiveIntegerField(default=0, help_text='Polls that contributed. Low count = sparse day.')),
                ('has_gap', models.BooleanField(default=False, help_text='True when the feed was silent long enough that this day is under-counted. Makes a sparse day visibly sparse instead of silently wrong.')),
                ('first_sample_at', models.DateTimeField(blank=True, null=True)),
                ('last_sample_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'vehicle__vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('obd_fault', 'OBD fault code'), ('maintenance', 'Samsara maintenance issue'), ('dvir', 'DVIR defect')], db_index=True, default='obd_fault', max_length=16)),
                ('external_id', models.CharField(help_text="Samsara's own id for this fault/issue. The idempotency key — never generate our own.", max_length=64)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('raw', models.JSONField(blank=True, help_text='The Samsara payload for this episode. Bounded (one row per episode, not per sample) so it stays cheap — unlike a raw sample ledger, which would reach millions of rows a year.', null=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil', 'Oil change'), ('tires', 'Tires'), ('brakes', 'Brakes'), ('transmission', 'Transmission'), ('inspection', 'Inspection'), ('other', 'Other'), ('repair', 'Repair')], max_length=32)),
                ('performed_on', models.DateField(db_index=True)),
                ('odometer_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('out_of_service_from', models.DateField(blank=True, null=True)),
                ('out_of_service_to', models.DateField(blank=True, null=True)),
                ('fault_reference', models.CharField(blank=True, default='', help_text='Free text: the fault code or Samsara issue this addressed.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-performed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil', 'Oil change'), ('tires', 'Tires'), ('brakes', 'Brakes'), ('transmission', 'Transmission'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=32)),
                ('interval_miles', models.PositiveIntegerField(blank=True, help_text='Due this many miles after the last one.', null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Due this many days after the last one.', null=True)),
                ('last_done_on', models.DateField(blank=True, null=True)),
                ('last_done_odometer_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['vehicle__vehicle_number', 'service_type'],
            },
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='in_service_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='insurance_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='license_plate',
            field=models.CharField(blank=True, default='', help_text='Plate as Samsara reports it. Identification/display only.', max_length=16),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='next_inspection_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='registration_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_battery_millivolts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_engine_seconds',
            field=models.BigIntegerField(blank=True, help_text='Engine hours in seconds (obdEngineSeconds). Frequently absent on light-duty OBD-II — populated opportunistically, nothing is built on it. Do not add a feature that requires this without checking coverage first (manage.py fleet_probe).', null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_engine_state',
            field=models.CharField(blank=True, default='', help_text='Running / Idle / Off, as Samsara reports it.', max_length=16),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_faults_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_fuel_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_gps_distance_meters',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cumulative gpsDistanceMeters. The mileage FALLBACK baseline.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_name',
            field=models.CharField(blank=True, default='', help_text="Samsara's own label for this vehicle. Shown beside vehicle_number so a mis-typed samsara_vehicle_id is obvious at a glance.", max_length=128),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_odometer_at',
            field=models.DateTimeField(blank=True, help_text="Samsara's timestamp for the odometer sample.", null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_odometer_meters',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Latest odometer in METERS (canonical unit). NULL = never reported.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_odometer_source',
            field=models.CharField(blank=True, default='', help_text='Which counter produced it: obd (exact) / gps (estimate). Stored, never inferred at render — see dispatching/mileage.py.', max_length=8),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='samsara_open_fault_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='vin',
            field=models.CharField(blank=True, db_index=True, default='', help_text='17-char VIN. Synced from Samsara where available; blank = unknown.', max_length=17),
        ),
        migrations.AddConstraint(
            model_name='fleetvehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('samsara_vehicle_id', ''), _negated=True), fields=('samsara_vehicle_id',), name='uniq_fleetvehicle_samsara_vehicle_id'),
        ),
        migrations.AddField(
            model_name='vehicledayreading',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_readings', to='drivers.fleetvehicle'),
        ),
        migrations.AddField(
            model_name='vehiclefault',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faults', to='drivers.fleetvehicle'),
        ),
        migrations.AddField(
            model_name='vehicleservicerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_service_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleservicerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='drivers.fleetvehicle'),
        ),
        migrations.AddField(
            model_name='vehicleserviceschedule',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='drivers.fleetvehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicledayreading',
            index=models.Index(fields=['date', 'vehicle'], name='drivers_veh_date_ea0fa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicledayreading',
            constraint=models.UniqueConstraint(fields=('vehicle', 'date'), name='uniq_vehicle_day_reading'),
        ),
        migrations.AddIndex(
            model_name='vehiclefault',
            index=models.Index(fields=['vehicle', 'resolved_at'], name='drivers_veh_vehicle_b7ef0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclefault',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('vehicle', 'source', 'external_id'), name='uniq_open_vehicle_fault'),
        ),
        migrations.AddConstraint(
            model_name='vehicleserviceschedule',
            constraint=models.UniqueConstraint(fields=('vehicle', 'service_type'), name='uniq_vehicle_service_schedule'),
        ),
    ]
