# Generated by Django 5.1.4 on 2026-08-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0045_fleet_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetvehicle',
            name='transponder_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Transponder / account number mounted in this vehicle. Blank = none assigned.', max_length=32),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='transponder_type',
            field=models.CharField(blank=True, choices=[('sunpass', 'SunPass'), ('epass', 'E-PASS'), ('other', 'Other')], default='', help_text='Which toll network this transponder bills through.', max_length=16),
        ),
    ]
