# Generated by Django 5.1.4 on 2026-08-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0046_vehicle_transponder'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetvehicle',
            name='out_of_service_from',
            field=models.DateField(blank=True, db_index=True, help_text='First date the unit is unavailable. Blank = in service.', null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='out_of_service_reason',
            field=models.CharField(blank=True, default='', help_text="Why it's down, in the dispatcher's words — 'transmission, at Bob's', 'rear-ended 8/3'. Shown wherever the unit is blocked.", max_length=200),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='out_of_service_until',
            field=models.DateField(blank=True, help_text='Last date unavailable (inclusive). Blank with a start date means down indefinitely — no return date known.', null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='permit_mco',
            field=models.BooleanField(default=False, help_text='Holds a GOAA / MCO pickup permit.'),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='permit_mco_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='permit_port_canaveral',
            field=models.BooleanField(default=False, help_text='Holds a Port Canaveral pickup permit.'),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='permit_port_canaveral_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='permit_sanford',
            field=models.BooleanField(default=False, help_text='Holds a Sanford (SFB) pickup permit.'),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='permit_sanford_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
