# Generated by Django 5.1.4 on 2026-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0047_vehicle_oos_and_permits'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='default_min_turn_buffer',
            field=models.IntegerField(blank=True, help_text="Spare minutes THIS driver needs between two jobs, on top of the drive between them. Leave blank to use whatever buffer the build is run with. Type 0 for a driver who genuinely needs no cushion (gets his guests up and out early) — he will keep building as tight as the drive time allows even on a buffered run. A typed number always wins over the run's setting, in both directions.", null=True),
        ),
    ]
