# Generated by Django 5.1.4 on 2026-08-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0048_driver_default_min_turn_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='portal_role',
            field=models.CharField(choices=[('driver', 'Chauffeur — drives the jobs themselves'), ('operator', 'Operator — re-dispatches jobs to their own drivers')], default='driver', help_text='Operator = this login runs a company that takes our jobs and hands them to its OWN drivers (in LimoAnywhere or similar). They get the operator job board instead of the chauffeur portal: accept/decline, copy the job details out to their system, name the driver they put on it, and report status back. Leave as Chauffeur for anyone who actually drives the trip themselves.', max_length=20),
        ),
    ]
