# Generated by Django 5.1.4 on 2026-08-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0049_driver_portal_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='exclude_from_payroll',
            field=models.BooleanField(default=False, help_text='Keep this driver off the Driver Payments page and out of the Gusto export. For owner/founder accounts and placeholder records that run trips but are never paid through payroll. Changes nothing about dispatch — they still appear on the board and can still be assigned trips.'),
        ),
    ]
