# Generated by Django 5.1.4 on 2026-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0050_driver_chauffeur_permit_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_address',
            field=models.CharField(blank=True, default='', help_text='Address as printed on the license. Often out of date — drivers move without reprinting a license — so this is reference only.', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth as printed on the license.', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_full_name',
            field=models.CharField(blank=True, default='', help_text='Name exactly as printed on the license — for matching against the account name, not a replacement for it. May legitimately differ (maiden name, nickname on the account, etc.).', max_length=150),
        ),
    ]
