# Generated by Django 5.1.4 on 2026-08-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0051_exclude_founder_accounts_from_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='chauffeur_permit_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='chauffeur_permit_number',
            field=models.CharField(blank=True, default='', help_text='Chauffeur / for-hire permit number, where required.', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='chauffeur_permit_scan',
            field=models.FileField(blank=True, help_text='Optional scan/photo of the chauffeur / for-hire permit.', null=True, upload_to='drivers/permits/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='dot_medical_card_expiration',
            field=models.DateField(blank=True, help_text="Expiration of the DOT medical examiner's certificate, if applicable.", null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='dot_medical_card_scan',
            field=models.FileField(blank=True, help_text='Optional scan/photo of the DOT medical card.', null=True, upload_to='drivers/medical_cards/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_class',
            field=models.CharField(blank=True, default='', help_text='License class/endorsement, e.g. "E" (standard FL) or "CDL-A".', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_scan',
            field=models.FileField(blank=True, help_text="Optional scan/photo of the driver's license.", null=True, upload_to='drivers/licenses/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_state',
            field=models.CharField(blank=True, default='', help_text='Issuing state (or country, for a non-US license), e.g. "FL".', max_length=30),
        ),
    ]
