# Generated by Django 5.1.4 on 2026-08-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0053_driver_license_address_driver_license_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='chauffeur_permit_fdl_number',
            field=models.CharField(blank=True, default='', help_text='Driver\'s-license number as printed on the physical permit card (labeled "FDL#" on a City of Orlando permit) — cross-checked against license_number below; a mismatch usually means one of the two was mistyped.', max_length=50),
        ),
    ]
