# Generated by Django 5.1.4 on 2026-09-14 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_windows_into_ledger(apps, schema_editor):
    """Carry the one-window-per-vehicle state into the VehicleDowntime ledger.

    A window that already ended becomes a CLOSED row (its history is the
    point of the ledger); one still running or booked for later stays open.
    The old `until` was the LAST unavailable day; the ledger stores the first
    day BACK, so it shifts by one.
    """
    from datetime import date, timedelta

    FleetVehicle = apps.get_model("drivers", "FleetVehicle")
    VehicleDowntime = apps.get_model("drivers", "VehicleDowntime")
    today = date.today()

    for vehicle in FleetVehicle.objects.exclude(out_of_service_from__isnull=True):
        until = vehicle.out_of_service_until
        back = until + timedelta(days=1) if until else None
        if back is not None and back <= vehicle.out_of_service_from:
            # A backwards window never gated anything; it isn't history either.
            continue
        ended = back if (back is not None and back <= today) else None
        VehicleDowntime.objects.create(
            vehicle=vehicle,
            category="other",
            reason=(vehicle.out_of_service_reason or "").strip() or "Out of service",
            starts_on=vehicle.out_of_service_from,
            expected_back_on=back,
            ended_on=ended,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0054_driver_chauffeur_permit_fdl_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="What's wrong, in one line: 'brakes grinding at low speed'.", max_length=200)),
                ('details', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('ground', 'Do not drive'), ('soon', 'Fix soon'), ('watch', 'Keep an eye on it')], db_index=True, default='soon', help_text="'Do not drive' is a statement, not a gate — take the car out of service with a downtime if it must not be assigned.", max_length=8)),
                ('source', models.CharField(choices=[('dispatch', 'Dispatch'), ('driver', 'Chauffeur (relayed)'), ('fleet', 'Fleet')], default='dispatch', max_length=12)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution', models.TextField(blank=True, help_text='What was done about it. Kept with the issue so the next time this car makes the same noise, the fix is on record.')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_vehicle_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_vehicle_issues', to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='drivers.vehicleservicerecord')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='drivers.fleetvehicle')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'Scheduled maintenance'), ('repair', 'Repair'), ('tires', 'Tires'), ('bodywork', 'Body / accident'), ('inspection', 'Inspection'), ('recall', 'Recall / dealer'), ('other', 'Other')], db_index=True, default='repair', max_length=16)),
                ('reason', models.CharField(help_text="Why it's down, in plain words — 'transmission, at Bob's', 'rear-ended 8/3'. Shown wherever the unit is blocked.", max_length=200)),
                ('vendor', models.CharField(blank=True, help_text='Shop or dealer.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('starts_on', models.DateField(db_index=True)),
                ('expected_back_on', models.DateField(blank=True, help_text='First day the unit is expected back on the road. Blank = no ETA.', null=True)),
                ('ended_on', models.DateField(blank=True, db_index=True, help_text='First day it was actually back. NULL while the downtime is open.', null=True)),
                ('demand_verdict', models.CharField(blank=True, choices=[('clear', 'Clear'), ('tight', 'Tight'), ('conflict', 'Conflict')], default='', help_text='What the demand check said when this window was planned.', max_length=12)),
                ('demand_snapshot', models.JSONField(blank=True, help_text='Per-day detail behind the verdict, as it stood at planning time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_vehicle_downtimes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicle_downtimes', to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(blank=True, help_text='The service that closed it, if logged.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='drivers.vehicleservicerecord')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='drivers.fleetvehicle')),
                ('issue', models.ForeignKey(blank=True, help_text='The reported problem that caused this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to='drivers.vehicleissue')),
            ],
            options={
                'ordering': ['-starts_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleissue',
            index=models.Index(fields=['vehicle', 'resolved_at'], name='drivers_veh_vehicle_27f640_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledowntime',
            index=models.Index(fields=['vehicle', 'ended_on'], name='drivers_veh_vehicle_2d6987_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledowntime',
            index=models.Index(fields=['starts_on', 'ended_on'], name='drivers_veh_starts__b0cf25_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicledowntime',
            constraint=models.CheckConstraint(condition=models.Q(('expected_back_on__isnull', True), ('expected_back_on__gt', models.F('starts_on')), _connector='OR'), name='downtime_expected_after_start'),
        ),
        migrations.AddConstraint(
            model_name='vehicledowntime',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('starts_on')), _connector='OR'), name='downtime_ended_not_before_start'),
        ),
        migrations.RunPython(copy_windows_into_ledger, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='out_of_service_from',
        ),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='out_of_service_reason',
        ),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='out_of_service_until',
        ),
    ]
