# Generated by Django 5.1.4 on 2026-09-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0055_fleet_downtime_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetvehicle',
            name='out_of_service_from',
            field=models.DateField(blank=True, editable=False, help_text='LEGACY, unused. Kept so pre-ledger code can boot. See VehicleDowntime.', null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='out_of_service_reason',
            field=models.CharField(blank=True, default='', editable=False, help_text='LEGACY, unused. Kept so pre-ledger code can boot.', max_length=200),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='out_of_service_until',
            field=models.DateField(blank=True, editable=False, help_text='LEGACY, unused. Kept so pre-ledger code can boot.', null=True),
        ),
    ]
