# Generated by Django 5.1.4 on 2026-09-15 17:31

import django.db.models.deletion
import drivers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0056_readd_legacy_oos_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='Monday of the ISO week this inspection counts for.')),
                ('inspected_on', models.DateField(db_index=True)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('ok', 'All good'), ('found', 'Found something')], db_index=True, default='ok', max_length=8)),
                ('odometer_miles', models.DecimalField(blank=True, decimal_places=1, help_text='Read off the dash. For the two units with no Samsara gateway this is the only mileage the system ever gets, which is what makes their service intervals work at all.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_inspections', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, help_text='The problem this inspection raised, if it raised one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='drivers.vehicleissue')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='drivers.fleetvehicle')),
            ],
            options={
                'ordering': ['-week_start', 'vehicle'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(blank=True, help_text='The checklist item this shows, or blank for the walk-around in general.', max_length=64)),
                ('image', models.ImageField(upload_to=drivers.models.inspection_photo_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drivers.vehicleinspection')),
            ],
            options={
                'ordering': ['item_key', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['week_start', 'outcome'], name='drivers_veh_week_st_5e882a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleinspection',
            unique_together={('vehicle', 'week_start')},
        ),
    ]
