# Generated by Django 5.1.4 on 2026-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0057_vehicle_inspection_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='service_due_miles',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="The odometer figure on the windshield sticker — the mileage the next service is due at. MILES, deliberately, with no companion date field: these cars run 190-350 miles a day, so a shop's 'or by <date>' is written for a car that does 30 and is meaningless here. The date is DERIVED from this number and the unit's own measured daily mileage.", max_digits=10, null=True),
        ),
    ]
