# Generated by Django 5.1.4 on 2026-09-27 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0058_inspection_service_due_miles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='details_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Last time the chauffeur reviewed their own contact details in the driver app.', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='hired_on',
            field=models.DateField(blank=True, help_text='First day with us. Drives tenure on the profile; nothing else reads it yet.', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='home_address',
            field=models.CharField(blank=True, default='', help_text='Where they actually live now — the licence address is often stale.', max_length=255),
        ),
        migrations.CreateModel(
            name='DriverInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_via', models.CharField(choices=[('sms', 'Text message'), ('email', 'Email'), ('link', 'Copied link')], default='link', max_length=10)),
                ('sent_to', models.CharField(blank=True, default='', help_text='The number or address the link was last sent to.', max_length=150)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_count', models.PositiveSmallIntegerField(default=0)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
