# Generated by Django 5.1.4 on 2026-09-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0060_normalize_driver_phones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking_type', models.CharField(choices=[('service', 'Service'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('detailing', 'Detailing'), ('repair', 'Repair'), ('transfer', 'Vehicle pickup / drop-off'), ('fleet_use', 'Fleet Manager use'), ('training', 'Driver training'), ('permit', 'Permit / registration appointment'), ('reserved', 'Reserved for another operational reason'), ('other', 'Other')], default='service', max_length=16)),
                ('reason', models.CharField(blank=True, help_text="What it's for, in plain words — 'rear tyres', 'new-hire drive with Ana'.", max_length=200)),
                ('location', models.CharField(blank=True, help_text='Where, or which vendor.', max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('is_hard', models.BooleanField(default=False, help_text='Hard = no trip may be put on the car in this window. Soft (default) = dispatch is warned and may continue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_vehicle_bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicle_bookings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vehicle_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='drivers.fleetvehicle')),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='drivers_veh_vehicle_84af11_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='vehicle_booking_ends_after_start')],
            },
        ),
    ]
