# Generated by Django 5.1.4 on 2026-10-04 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0061_vehicle_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='extra_shift_days',
            field=models.JSONField(blank=True, default=list, help_text='Weekdays this driver is open to an extra shift, 0 = Monday to 6 = Sunday. Empty = not open to extra shifts.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='hard_earliest_start',
            field=models.TimeField(blank=True, help_text='The earliest this driver will ever leave base. Blank = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='hard_latest_finish',
            field=models.TimeField(blank=True, help_text='The latest this driver will ever be back at base. Blank = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='hard_latest_finish_next_day',
            field=models.BooleanField(default=False, help_text='Tick when the latest finish above is after midnight, e.g. 1 AM the next day.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='max_days_per_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The most days a week this driver works (1-7). Blank = no limit.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='driver',
            name='regular_shift_confirmed_at',
            field=models.DateTimeField(blank=True, help_text="When a manager confirmed this driver's regular shift. Blank = no regular shift yet. A week where every day is Off still counts as confirmed.", null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='regular_shift_confirmed_by',
            field=models.ForeignKey(blank=True, help_text="The manager who confirmed this driver's regular shift.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='shift_end',
            field=models.TimeField(blank=True, help_text="When this day's regular shift is back at base. At or before the start means the next day.", null=True),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='shift_start',
            field=models.TimeField(blank=True, help_text="When this day's regular shift leaves base.", null=True),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('morning', 'Morning'), ('midday', 'Midday'), ('evening', 'Evening')], help_text='Which shape this is: Morning, Midday or Evening.', max_length=12, unique=True)),
                ('name', models.CharField(help_text='The name dispatchers see.', max_length=40)),
                ('start_earliest', models.TimeField(help_text='Earliest usual time to leave base.')),
                ('start_latest', models.TimeField(help_text='Latest usual time to leave base.')),
                ('end_earliest', models.TimeField(help_text='Earliest usual time to be back at base.')),
                ('end_latest', models.TimeField(help_text='Latest usual time to be back at base. Earlier than the earliest means the next day.')),
                ('max_span_minutes', models.PositiveSmallIntegerField(default=720, help_text='Longest a regular shift of this shape may run, base to base, in minutes. Never more than 720 (12 hours).', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(720)])),
                ('notes', models.CharField(blank=True, default='', help_text='What the trip data shows for this shape, for whoever tunes it.', max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='shift_template',
            field=models.ForeignKey(blank=True, help_text="This day's regular shift: Morning, Midday or Evening. Blank = Off.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_rows', to='drivers.shifttemplate'),
        ),
    ]
