# Generated by Django 5.1.4 on 2026-10-04 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0063_seed_shift_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='shift_role',
            field=models.ForeignKey(blank=True, help_text="The driver's usual shift: Morning, Midday, Evening, or Float for anything.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_drivers', to='drivers.shifttemplate'),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='alt_template',
            field=models.ForeignKey(blank=True, help_text='A second shift this day can be instead, e.g. Morning or Evening. Blank = only the shift above.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drivers.shifttemplate'),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='day_earliest_start',
            field=models.TimeField(blank=True, help_text='This day only: never leaves base before this time. Blank = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='day_latest_finish',
            field=models.TimeField(blank=True, help_text='This day only: back at base by this time, e.g. done by 3 PM on Thursdays. Blank = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='driverweeklyschedule',
            name='day_latest_finish_next_day',
            field=models.BooleanField(default=False, help_text="Tick when this day's finish-by above is after midnight."),
        ),
        migrations.AlterField(
            model_name='driverweeklyschedule',
            name='shift_end',
            field=models.TimeField(blank=True, help_text="When this day's regular shift is back at base. At or before the start means the next day. Leave both times blank for the shift's usual times.", null=True),
        ),
        migrations.AlterField(
            model_name='driverweeklyschedule',
            name='shift_start',
            field=models.TimeField(blank=True, help_text="When this day's regular shift leaves base. Leave both times blank for the shift's usual times.", null=True),
        ),
        migrations.AlterField(
            model_name='driverweeklyschedule',
            name='shift_template',
            field=models.ForeignKey(blank=True, help_text="This day's regular shift: Morning, Midday, Evening or Float. Blank = Off.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_rows', to='drivers.shifttemplate'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='kind',
            field=models.CharField(choices=[('morning', 'Morning'), ('midday', 'Midday'), ('evening', 'Evening'), ('float', 'Float')], help_text='Which shape this is: Morning, Midday, Evening or Float.', max_length=12, unique=True),
        ),
    ]
