# Generated by Django 5.1.4 on 2026-10-04 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0065_seed_float_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('habit', 'Habit'), ('language', 'Language'), ('area', 'Area')], max_length=12)),
                ('polarity', models.CharField(choices=[('positive', 'Positive'), ('caution', 'Caution')], default='positive', help_text='Caution = something to plan around, e.g. Runs late.', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop offering this tag. Drivers who have it keep it.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DriverTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='drivers.driver')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='drivers.drivertag')),
            ],
            options={
                'unique_together': {('driver', 'tag')},
            },
        ),
    ]
