# Generated by Django 5.1.4 on 2026-10-04 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0067_seed_driver_tags'),
        ('reservations', '0130_refundrequest_approve_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField()),
                ('kind', models.CharField(choices=[('compliment', 'Compliment'), ('complaint', 'Complaint'), ('incident', 'Incident'), ('note', 'Note')], max_length=12)),
                ('is_strike', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, choices=[('', 'Not set'), ('minor', 'Minor'), ('serious', 'Serious')], default='', max_length=10)),
                ('summary', models.CharField(max_length=140)),
                ('details', models.TextField(blank=True, default='')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='drivers.driver')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reservations.leg')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'driver log entries',
                'ordering': ['-occurred_on', '-logged_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_strike', False), ('kind__in', ('complaint', 'incident')), _connector='OR'), name='driverlog_strike_is_complaint_or_incident', violation_error_message='A strike must be a complaint or an incident.')],
            },
        ),
    ]
