# Generated by Django 5.1.4 on 2025-03-31 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("zipcode", models.CharField(max_length=20)),
                ("is_returning", models.BooleanField(default=False)),
                ("reservation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_type",
                    models.CharField(
                        choices=[("arrival", "Arrival"), ("departure", "Departure")],
                        max_length=10,
                    ),
                ),
                ("airline", models.CharField(max_length=50)),
                ("flight_number", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("one_way", "One Way"), ("round_trip", "Round Trip")],
                        max_length=20,
                    ),
                ),
                ("passenger_count", models.PositiveIntegerField(default=1)),
                ("has_children", models.BooleanField(default=False)),
                ("luggage_count", models.PositiveIntegerField(default=1)),
                (
                    "carseat_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("booster", "Booster Seat"),
                            ("rear_facing", "Rear-Facing Car Seat"),
                            ("forward_facing", "Forward-Facing Car Seat"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("store_stop", models.BooleanField(default=False)),
                ("special_requests", models.TextField(blank=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_charges",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_status", models.CharField(default="PENDING", max_length=20)),
                ("stripe_payment_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reservations.customer",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rates.route"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rates.vehicle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                (
                    "flight_information",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.flight",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
    ]
