# Generated by Django 5.1.4 on 2025-04-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
    ]
