# Generated by Django 5.1.4 on 2025-04-02 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="date",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="time",
        ),
    ]
