# Generated by Django 5.1.4 on 2025-03-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_alter_reservation_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="arrival_date",
            new_name="pickup_date",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="arrival_time",
            new_name="pickup_time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="luggage_count",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="reservation",
            name="pasenger_count",
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
    ]
