# Generated by Django 5.1.4 on 2025-04-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_userpayment_delete_payment"),
        ("reservations", "0002_remove_reservation_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.userpayment",
            ),
        ),
    ]
