# Generated by Django 5.1.4 on 2025-04-04 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0004_alter_rate_route_alter_rate_vehicle"),
        ("reservations", "0002_remove_flight_date_remove_flight_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="route",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="vehicle",
        ),
        migrations.AddField(
            model_name="reservation",
            name="rate",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="rates.rate"
            ),
            preserve_default=False,
        ),
    ]
