# Generated by Django 5.1.4 on 2025-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_rename_arrival_date_reservation_pickup_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="pickup_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="pickup_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="special_requests",
            field=models.TextField(
                blank=True,
                help_text="Any Special Requests, Carseats, Booster Seats",
                null=True,
            ),
        ),
    ]
