# Generated by Django 5.1.4 on 2025-04-04 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_userpayment_status"),
        (
            "reservations",
            "0003_remove_reservation_route_remove_reservation_vehicle_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="stripe_payment_id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="payment",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.userpayment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("confirmed", "Confirmed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
