# Generated by Django 5.1.4 on 2025-04-04 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_userpayment_status"),
        ("reservations", "0004_remove_reservation_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="payment",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.userpayment",
            ),
        ),
    ]
