# Generated by Django 5.1.4 on 2025-04-04 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_payment_remove_userpayment_user"),
        ("reservations", "0004_customer_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.payment",
            ),
        ),
    ]
