# Generated by Django 5.1.4 on 2025-03-28 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_alter_location_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="rate",
            old_name="price",
            new_name="oneway_price",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="airline",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="flight_number",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest_email",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="guest_phone",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="user",
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.customer",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FlightInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airline", models.CharField(max_length=50)),
                ("flight_number", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
    ]
