# Generated by Django 5.1.4 on 2025-04-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_userpayment_created_at_and_more'),
        ('reservations', '0006_alter_reservation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.userpayment'),
        ),
    ]
