# Generated by Django 5.1.4 on 2025-03-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_rename_price_rate_oneway_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="dropoff_location",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="pickup_location",
        ),
        migrations.AddField(
            model_name="reservation",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="phone_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="route",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="reservations.route",
            ),
            preserve_default=False,
        ),
    ]
