# Generated by Django 5.1.4 on 2025-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_contactusform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusform',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('text', 'Text Message')], default='email', max_length=10),
        ),
    ]
