# Generated by Django 5.1.4 on 2025-04-05 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_alter_reservation_payment"),
        ("reservations", "0008_contactusform_contact_method"),
    ]

    operations = []
