# Generated by Django 5.1.4 on 2025-03-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_remove_reservation_dropoff_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="roundtrip_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
