# Generated by Django 5.1.4 on 2025-04-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0009_merge_20250404_2050"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="card_brand",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="card_exp_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="card_exp_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="card_last4",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
