# Generated by Django 5.1.4 on 2025-03-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0009_rate_roundtrip_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="user",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="reservation",
        ),
        migrations.AlterUniqueTogether(
            name="rate",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rate",
            name="route",
        ),
        migrations.RemoveField(
            model_name="rate",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="savedcard",
            name="user",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="carseat_needed",
            new_name="has_children",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="payment_status",
            new_name="payemnt_status",
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="children_count",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="vehicle_type",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="available",
        ),
        migrations.AddField(
            model_name="flightinformation",
            name="flight_type",
            field=models.CharField(
                choices=[("arrival", "Arrival"), ("departure", "Departure")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="dropoff_location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="reservation",
            name="pickup_location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="return_dropoff_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reservation",
            name="return_pickup_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reservation",
            name="return_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="store_stop",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="trip_type",
            field=models.CharField(
                choices=[("one_way", "One Way"), ("round_trip", "Round Trip")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="vehicle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="reservations.vehicle",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="zipcode",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="name",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="luggage_capacity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="carseat_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("booster", "Booster Seat"),
                    ("rear_facing", "Rear-Facing Car Seat"),
                    ("forward_facing", "Forward-Facing Car Seat"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="luggage_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="passenger_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Rate",
        ),
        migrations.DeleteModel(
            name="SavedCard",
        ),
        migrations.RemoveField(
            model_name="route",
            name="dropoff_location",
        ),
        migrations.RemoveField(
            model_name="route",
            name="pickup_location",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
