# Generated by Django 5.1.4 on 2025-03-28 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0010_remove_reservation_customer_remove_driver_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oneway_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "round_trip_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.vehicle",
                    ),
                ),
            ],
            options={
                "unique_together": {("vehicle", "route")},
            },
        ),
    ]
