# Generated by Django 5.1.4 on 2025-04-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_delete_userpayment"),
        ("rates", "0005_alter_rate_unique_together_alter_rate_oneway_price_and_more"),
        ("reservations", "0010_customer_card_brand_customer_card_exp_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="reservation_email_0020f5_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["created_at"], name="reservation_created_6a7714_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leg",
            index=models.Index(
                fields=["pickup_date"], name="reservation_pickup__cb04eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leg",
            index=models.Index(
                fields=["reservation"], name="reservation_reserva_a61631_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leg",
            index=models.Index(
                fields=["pickup_location", "dropoff_location"],
                name="reservation_pickup__f74179_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["customer"], name="reservation_custome_24f7d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["trip_type"], name="reservation_trip_ty_300e7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["rate"], name="reservation_rate_id_395a9e_idx"),
        ),
    ]
