# Generated by Django 5.1.4 on 2025-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
