# Generated by Django 5.1.4 on 2025-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0011_alter_customer_email_alter_customer_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="booster_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="ff_carseat",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="need_carseats",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="rf_carseat",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
