# Generated by Django 5.1.4 on 2025-04-07 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0012_reservation_booster_seats_reservation_ff_carseat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
