# Generated by Django 5.1.4 on 2025-04-07 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0013_reservation_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="uuid",
        ),
    ]
