# Generated by Django 5.1.4 on 2025-03-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0013_customer_flight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reservations.customer"
            ),
        ),
    ]
