# Generated by Django 5.1.4 on 2025-04-07 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0014_remove_reservation_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
