# Generated by Django 5.1.4 on 2025-03-31 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
        ("reservations", "0014_alter_reservation_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="rates.route"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="rates.vehicle"
            ),
        ),
        migrations.DeleteModel(
            name="Rate",
        ),
        migrations.DeleteModel(
            name="Route",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
