# Generated by Django 5.1.4 on 2025-04-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_delete_userpayment"),
        ("rates", "0010_remove_rate_rates_rate_vehicle_822bc6_idx_and_more"),
        ("reservations", "0015_reservation_uuid"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="reservation_created_6a7714_idx",
        ),
        migrations.RemoveIndex(
            model_name="leg",
            name="reservation_pickup__cb04eb_idx",
        ),
        migrations.RemoveIndex(
            model_name="leg",
            name="reservation_pickup__f74179_idx",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="ff_carseat",
            new_name="ff_carseats",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="rf_carseat",
            new_name="rf_carseats",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="carseat_type",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="has_children",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["phone_number"], name="reservation_phone_n_0ae1db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leg",
            index=models.Index(
                fields=["flight_information"], name="reservation_flight__2229ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["uuid"], name="reservation_uuid_8a65e3_idx"),
        ),
    ]
