# Generated by Django 5.1.4 on 2025-04-08 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0010_remove_rate_rates_rate_vehicle_822bc6_idx_and_more"),
        (
            "reservations",
            "0016_remove_customer_reservation_created_6a7714_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rates.vehicle",
            ),
        ),
    ]
