# Generated by Django 5.1.4 on 2025-04-08 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0017_reservation_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="payment",
        ),
    ]
