# Generated by Django 5.1.4 on 2025-04-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0018_remove_reservation_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactUsForm",
        ),
    ]
