# Generated by Django 5.1.4 on 2025-04-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0019_delete_contactusform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airline",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_type",
            field=models.CharField(
                blank=True,
                choices=[("arrival", "Arrival"), ("departure", "Departure")],
                max_length=10,
            ),
        ),
    ]
