# Generated by Django 5.1.4 on 2025-04-25 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0020_alter_flight_airline_alter_flight_flight_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leg",
            options={"ordering": ["pickup_date", "pickup_time"]},
        ),
    ]
