# Generated by Django 5.1.4 on 2025-04-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_leg_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='private_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
