# Generated by Django 5.1.4 on 2025-04-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_remove_driver_legs_driver_vehicle"),
        ("reservations", "0023_reservation_private_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legs",
                to="drivers.driver",
            ),
        ),
    ]
