# Generated by Django 5.1.4 on 2025-04-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0024_leg_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
