# Generated by Django 5.1.4 on 2025-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0025_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Assigned", "Assigned"),
                    ("At Pickup Location", "At Pickup Location"),
                    ("Completed", "Completed"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
