# Generated by Django 5.1.4 on 2025-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0027_alter_leg_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leg",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in-progress", "In-Progress"),
                    ("picked-up", "Picked-Up"),
                    ("completed", "Completed"),
                ],
                default="in-progress",
                max_length=255,
                null=True,
            ),
        ),
    ]
