# Generated by Django 5.1.4 on 2025-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0028_alter_leg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booster_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Booster'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ff_carseats',
            field=models.PositiveBigIntegerField(default=0, verbose_name='FF-Seat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rf_carseats',
            field=models.PositiveIntegerField(default=0, verbose_name='RF-Seat'),
        ),
    ]
