# Generated by Django 5.1.4 on 2025-05-10 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0012_alter_vehicle_carseats_display"),
        ("reservations", "0029_alter_reservation_booster_seats_and_more"),
        ("users", "0011_travelagent"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="commission_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="travel_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.travelagent",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["travel_agent"], name="reservation_travel__d8518a_idx"
            ),
        ),
    ]
