# Generated by Django 5.1.4 on 2025-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0030_reservation_commission_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="commission_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="commission_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
