# Generated by Django 5.1.4 on 2025-05-16 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0031_reservation_commission_paid_and_more"),
        ("users", "0018_commissionpayout_created_at_contactusform_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="travel_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="users.travelagent",
            ),
        ),
    ]
