# Generated by Django 5.1.4 on 2025-05-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0032_alter_reservation_travel_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="driver_pay_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount to pay the driver (set by admin)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="profit_estimate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated profit (revenue share - driver payment)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="revenue_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="This leg's portion of the reservation revenue",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="profit_estimate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated profit (total price - driver payments)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="total_driver_payments",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sum of all driver payments",
                max_digits=10,
                null=True,
            ),
        ),
    ]
