# Generated by Django 5.1.4 on 2025-05-22 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0012_alter_vehicle_carseats_display"),
        ("reservations", "0033_leg_driver_pay_amount_leg_payment_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("pickup_location", models.CharField(max_length=200)),
                ("dropoff_location", models.CharField(max_length=200)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("oneway", "One Way"), ("roundtrip", "Round Trip")],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("converted", models.BooleanField(default=False)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rates.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
