# Generated by Django 5.1.4 on 2025-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0034_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
