# Generated by Django 5.1.4 on 2025-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0012_alter_vehicle_carseats_display"),
        ("reservations", "0035_lead_pickup_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="contact_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="contacted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contact_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_follow_up",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("text", "Text Message"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                help_text="Priority level of the lead",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("referral", "Referral"),
                    ("social", "Social Media"),
                    ("other", "Other"),
                ],
                default="website",
                help_text="Where did this lead come from?",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("interested", "Interested"),
                    ("proposal", "Proposal Sent"),
                    ("negotiating", "Negotiating"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                default="new",
                help_text="Current status of the lead",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="reservation_status_404d08_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["priority"], name="reservation_priorit_7f4713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["next_follow_up"], name="reservation_next_fo_0e3592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["created_at"], name="reservation_created_fe84d9_idx"
            ),
        ),
    ]
