# Generated by Django 5.1.4 on 2025-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0036_lead_contact_attempts_lead_contacted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="converted_at",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="last_contact_date",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="preferred_contact_method",
        ),
        migrations.AddField(
            model_name="lead",
            name="contacted_at",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("text", "Text Message"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("fresh", "Fresh"),
                    ("contacted", "Contacted"),
                    ("interested", "Interested - Potential"),
                    ("converted", "Converted"),
                    ("lost", "Not Interested"),
                ],
                default="new",
                help_text="Current status of the lead",
                max_length=20,
            ),
        ),
    ]
