# Generated by Django 5.1.4 on 2025-05-25 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0037_remove_lead_converted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.RemoveField(
            model_name="lead",
            name="contacted",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="contacted_at",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="source",
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Conversion Date"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contact_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last contact attempt.",
                null=True,
                verbose_name="Last Contact Timestamp",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("text", "Text Message"),
                    ("none", "None"),
                ],
                default="none",
                help_text="Method of last contact attempt.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="contact_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times contact has been attempted."
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="converted",
            field=models.BooleanField(
                default=False, help_text="Has this lead been successfully converted?"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="estimated_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="next_follow_up",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Next Follow-Up Date"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("interested", "Interested - Potential"),
                    ("future_contact", "Contact Closer to Trip"),
                    ("converted", "Converted"),
                    ("lost", "Not Interested"),
                ],
                default="new",
                help_text="Current status of the lead",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="trip_type",
            field=models.CharField(
                blank=True,
                choices=[("oneway", "One Way"), ("roundtrip", "Round Trip")],
                max_length=20,
            ),
        ),
    ]
