# Generated by Django 5.1.4 on 2025-05-25 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0012_alter_vehicle_carseats_display"),
        ("reservations", "0038_alter_lead_options_remove_lead_contacted_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lead",
            name="reservation_status_404d08_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="reservation_priorit_7f4713_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="reservation_next_fo_0e3592_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="reservation_created_fe84d9_idx",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="last_contact_method",
        ),
        migrations.AlterField(
            model_name="lead",
            name="contact_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lead",
            name="converted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lead",
            name="converted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="lead",
            name="dropoff_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_contact_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="next_follow_up",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("interested", "Interested"),
                    ("future_contact", "Future Contact"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rates.vehicle",
            ),
        ),
    ]
