# Generated by Django 5.1.4 on 2025-06-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0039_remove_lead_reservation_status_404d08_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leg",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in-progress", "In-Progress"),
                    ("on-location", "On-Location"),
                    ("picked-up", "Picked-Up"),
                    ("completed", "Completed"),
                ],
                default="in-progress",
                max_length=255,
                null=True,
            ),
        ),
    ]
