# Generated by Django 5.1.4 on 2025-06-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0042_migrate_lead_data_to_quotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="gclid",
            field=models.CharField(
                blank=True,
                help_text="Google Click ID for conversion tracking",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="UTM campaign parameter",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="utm_content",
            field=models.CharField(
                blank=True, help_text="UTM content parameter", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="utm_medium",
            field=models.CharField(
                blank=True, help_text="UTM medium parameter", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="utm_source",
            field=models.CharField(
                blank=True, help_text="UTM source parameter", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="utm_term",
            field=models.CharField(
                blank=True, help_text="UTM term parameter", max_length=100, null=True
            ),
        ),
    ]
