# Generated by Django 5.1.4 on 2025-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0043_reservation_gclid_reservation_utm_campaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="driver_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes added by the driver about this trip",
                null=True,
            ),
        ),
    ]
