# Generated by Django 5.1.4 on 2025-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0043_reservation_gclid_reservation_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='status',
            field=models.CharField(blank=True, choices=[('in-progress', 'In-Progress'), ('confirmed', 'Confirmed'), ('on-the-way', 'On the Way'), ('on-location', 'On-Location'), ('picked-up', 'Picked-Up'), ('completed', 'Completed')], default='in-progress', max_length=255, null=True),
        ),
    ]
