# Generated by Django 5.1.4 on 2025-06-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0043_lead_updated_at_reservation_gclid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="updated_at",
        ),
    ]
