# Generated by Django 5.1.4 on 2025-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0044_update_leg_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="driver_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes added by the driver about this trip",
                null=True,
            ),
        ),
    ]
