# Generated by Django 5.1.4 on 2025-10-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0044_update_leg_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="gratuity_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="reservation",
            name="gratuity_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
