# Generated by Django 5.1.4 on 2025-12-03 19:21

from django.db import migrations, models, connection


def add_driver_notes_if_not_exists(apps, schema_editor):
    """
    Add driver_notes column only if it doesn't already exist.
    This makes the migration safe to run on Railway where the column may already exist.
    """
    db_table = 'reservations_leg'
    
    with connection.cursor() as cursor:
        # Check if column exists
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name='driver_notes'
            """, [db_table])
            column_exists = cursor.fetchone() is not None
        elif connection.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({db_table})")
            columns = [row[1] for row in cursor.fetchall()]
            column_exists = 'driver_notes' in columns
        else:
            # For other databases, assume it doesn't exist and let AddField handle it
            column_exists = False
        
        if not column_exists:
            # Column doesn't exist, add it using schema_editor
            Leg = apps.get_model('reservations', 'Leg')
            field = models.TextField(blank=True, help_text='Notes added by the driver about this trip', null=True)
            field.set_attributes_from_name('driver_notes')
            schema_editor.add_field(Leg, field)


def reverse_add_driver_notes(apps, schema_editor):
    """Reverse migration - remove the column if it exists"""
    Leg = apps.get_model('reservations', 'Leg')
    try:
        field = Leg._meta.get_field('driver_notes')
        schema_editor.remove_field(Leg, field)
    except:
        # Field doesn't exist, nothing to remove
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0046_auto_20251024_1241'),
    ]

    operations = [
        migrations.RunPython(
            add_driver_notes_if_not_exists,
            reverse_add_driver_notes,
        ),
    ]
