# Generated by Django 5.1.4 on 2025-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0047_leg_driver_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='baggage_claim',
            field=models.CharField(blank=True, help_text='Baggage claim area (e.g., 31)', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(blank=True, help_text='Destination airport (e.g., MCO - Orlando Intl)', max_length=255),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Estimated arrival time in local timezone', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_iata',
            field=models.CharField(blank=True, help_text='IATA flight code (e.g., DL1691)', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, help_text='Arrival gate (e.g., 76)', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='When flight data was last fetched from AeroAPI', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin airport (e.g., SLC - Salt Lake City Intl)', max_length=255),
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduled_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Scheduled arrival time in local timezone', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(blank=True, help_text='Flight status (e.g., En Route, Landed, Scheduled)', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='terminal',
            field=models.CharField(blank=True, help_text='Arrival terminal (e.g., B)', max_length=10),
        ),
    ]
