# Generated by Django 5.1.4 on 2025-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0048_flight_baggage_claim_flight_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='estimated_gate_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Estimated gate arrival time in local timezone', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduled_gate_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Scheduled gate arrival time in local timezone', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Estimated runway arrival time in local timezone', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Scheduled runway arrival time in local timezone', null=True),
        ),
    ]
