# Generated by Django 5.1.4 on 2025-12-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0049_flight_estimated_gate_arrival_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='actual_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Actual runway arrival time in local timezone (what actually happened)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_gate_arrival_local',
            field=models.DateTimeField(blank=True, help_text='Actual gate arrival time in local timezone (what actually happened)', null=True),
        ),
    ]
