# Generated by Django 5.1.4 on 2026-01-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0051_add_actual_arrival_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ghl_contact_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ghl_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='initial_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='initial_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
