# Generated by Django 5.1.4 on 2026-01-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0052_lead_ghl_contact_id_lead_ghl_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline_display_name',
            field=models.CharField(blank=True, help_text='Full airline name for display (e.g., Delta Airlines, Southwest Airlines)', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(blank=True, help_text='IATA code (e.g., DL, WN, B6) for API calls', max_length=50),
        ),
    ]
