# Generated by Django 5.1.4 on 2026-01-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Fix Django migration state for driver_notes field.
    
    Migration 0047 used RunPython to add driver_notes, which doesn't properly
    update Django's migration state. This migration uses SeparateDatabaseAndState
    to tell Django's state that the field exists, without modifying the database.
    
    This permanently fixes the issue where makemigrations keeps trying to add
    driver_notes in future migrations.
    """

    dependencies = [
        ('reservations', '0053_add_airline_display_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: Do nothing (field already exists)
            database_operations=[],
            # State operations: Tell Django the field exists in the model state
            state_operations=[
                migrations.AddField(
                    model_name='leg',
                    name='driver_notes',
                    field=models.TextField(blank=True, help_text='Notes added by the driver about this trip', null=True),
                ),
            ],
        ),
    ]
