# Generated by Django 5.1.4 on 2026-01-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0054_fix_driver_notes_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_line', models.CharField(blank=True, help_text='Cruise line name (e.g., Disney Cruise Line, Royal Caribbean, Carnival)', max_length=100)),
                ('ship_name', models.CharField(blank=True, help_text='Ship name (e.g., Disney Wish, Wonder of the Seas, Mardi Gras)', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='leg',
            name='cruise_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.cruise'),
        ),
    ]
