# Generated by Django 5.1.4 on 2026-01-10 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0055_cruise_leg_cruise_information'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='driver_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when driver was last assigned/changed', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='driver_assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who last assigned/changed the driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_driver_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leg',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when leg status was last changed', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who last changed the leg status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs_status_changed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last modification', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Name of the model that was changed (e.g., 'Reservation', 'Leg')", max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object that was changed')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('driver_assigned', 'Driver Assigned'), ('driver_unassigned', 'Driver Unassigned'), ('status_changed', 'Status Changed'), ('payment_processed', 'Payment Processed'), ('commission_processed', 'Commission Processed')], help_text='Type of action performed', max_length=50)),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that changed (if specific field change)', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (before change)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (after change)', null=True)),
                ('username', models.CharField(blank=True, help_text='Username at time of change (for historical reference)', max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the change occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who made the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context about the change', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='reservation_model_n_048da3_idx'), models.Index(fields=['user', '-timestamp'], name='reservation_user_id_c69091_idx'), models.Index(fields=['action', '-timestamp'], name='reservation_action_c8a3d9_idx'), models.Index(fields=['-timestamp'], name='reservation_timesta_ce3b7e_idx')],
            },
        ),
    ]
