# Generated by Django 5.1.4 on 2026-01-10 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0056_leg_driver_assigned_at_leg_driver_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refund (can be partial or full)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the refund processing', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='When the refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason for refund request from staff', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the refund was requested', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_requested_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who requested the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund Requested'), ('requested', 'Refund Requested'), ('processing', 'Processing Refund'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Refund Completed')], default='none', help_text='Current status of refund request', max_length=20),
        ),
    ]
