# Generated by Django 5.1.4 on 2026-01-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0057_reservation_refund_amount_reservation_refund_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, db_index=True, help_text='Google Click ID for conversion tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, help_text='UTM campaign parameter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, help_text='UTM content parameter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, db_index=True, help_text='UTM medium parameter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, help_text='UTM source parameter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, help_text='UTM term parameter', max_length=100, null=True),
        ),
    ]
