# Generated by Django 5.1.4 on 2026-01-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0058_add_utm_to_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fbclid',
            field=models.CharField(blank=True, db_index=True, help_text='Facebook Click ID for conversion tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fbclid',
            field=models.CharField(blank=True, db_index=True, help_text='Facebook Click ID for conversion tracking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='gclid',
            field=models.CharField(blank=True, db_index=True, help_text='Google Click ID for conversion tracking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, help_text='UTM source parameter', max_length=100, null=True),
        ),
    ]
