# Generated by Django 5.1.4 on 2026-01-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0060_leg_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="driver_base_pay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base pay amount for the driver (excluding gratuity)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="driver_gratuity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Gratuity amount for the driver",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leg",
            name="driver_pay_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount to pay the driver (set by admin) - DEPRECATED: Use driver_base_pay + driver_gratuity",
                max_digits=10,
                null=True,
            ),
        ),
    ]
