# Generated by Django 5.1.4 on 2026-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0061_add_driver_pay_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="driver_additional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Additional pay amount (e.g., wait time, early morning bonus, etc.)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
