# Generated by Django 5.1.4 on 2026-01-27 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0062_add_driver_additional_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when the time slot is blocked"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Start time of the blocked window (e.g., 12:00 AM)"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="End time of the blocked window (e.g., 8:00 AM)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason for blocking (e.g., 'Fully booked', 'Maintenance')",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this blocked time slot",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to temporarily disable this block without deleting it",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this blocked time slot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_blocked_time_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Time Slot",
                "verbose_name_plural": "Blocked Time Slots",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["date", "is_active"], name="reservation_date_9d24d2_idx"
                    )
                ],
            },
        ),
    ]
