# Generated by Django 5.1.4 on 2026-02-01 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0013_add_driver_additional_field"),
        ("rates", "0017_location_aliases"),
        ("reservations", "0063_add_blocked_time_slot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leg",
            index=models.Index(
                fields=["pickup_date", "pickup_time"],
                name="reservation_pickup__5e60ae_idx",
            ),
        ),
    ]
