# Generated by Django 5.1.4 on 2026-02-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0064_add_leg_pickup_date_time_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="confirmation_sms_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When next-day confirmation SMS was sent (Twilio)",
                null=True,
            ),
        ),
    ]
