# Generated by Django 5.1.4 on 2026-02-08 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0066_reservation_list_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Job Assigned'), ('in-progress', 'In Progress'), ('confirmed', 'Confirmed'), ('on-the-way', 'On the Way'), ('on-location', 'On Location'), ('picked-up', 'Picked Up'), ('completed', 'Completed')], help_text='The status at this point in time', max_length=30)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this status was set')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this status change', null=True)),
            ],
            options={
                'verbose_name': 'Leg Status Update',
                'verbose_name_plural': 'Leg Status Updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_created_fddb5a_idx',
            old_name='reservation_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_status_f1a03a_idx',
            old_name='reservation_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_refund__4f4dab_idx',
            old_name='reservation_refund_status_idx',
        ),
        migrations.AddField(
            model_name='legstatus',
            name='leg',
            field=models.ForeignKey(help_text='The leg this status update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.leg'),
        ),
        migrations.AddField(
            model_name='legstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who updated the status (admin, driver, or system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leg_status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='legstatus',
            index=models.Index(fields=['leg', '-timestamp'], name='reservation_leg_id_34c6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='legstatus',
            index=models.Index(fields=['-timestamp'], name='reservation_timesta_cf3908_idx'),
        ),
    ]
