# Generated by Django 5.1.4 on 2026-02-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_add_driver_additional_field'),
        ('reservations', '0067_legstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for this demand pattern')),
                ('hour', models.IntegerField(help_text='Hour of day (0-23)')),
                ('day_of_week', models.IntegerField(help_text='Day of week (0=Monday, 6=Sunday)')),
                ('arrival_legs', models.IntegerField(default=0, help_text='Number of arrival legs in this hour')),
                ('return_legs', models.IntegerField(default=0, help_text='Number of return legs in this hour')),
                ('cruise_legs', models.IntegerField(default=0, help_text='Number of cruise transfer legs in this hour')),
                ('other_legs', models.IntegerField(default=0, help_text='Number of other legs in this hour')),
                ('total_legs', models.IntegerField(default=0, help_text='Total legs in this hour')),
                ('total_drivers_needed', models.IntegerField(blank=True, help_text='Estimated drivers needed based on timing constraints', null=True)),
                ('inhouse_drivers_used', models.IntegerField(default=0, help_text='Number of in-house drivers used')),
                ('affiliate_drivers_used', models.IntegerField(default=0, help_text='Number of affiliate drivers used')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue for this hour', max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this demand pattern was last calculated')),
            ],
            options={
                'verbose_name': 'Demand Pattern',
                'verbose_name_plural': 'Demand Patterns',
                'ordering': ['-date', 'hour'],
                'indexes': [models.Index(fields=['-date', 'hour'], name='reservation_date_918892_idx'), models.Index(fields=['day_of_week', 'hour'], name='reservation_day_of__1f6ac9_idx'), models.Index(fields=['-calculated_at'], name='reservation_calcula_edfd05_idx')],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='RouteTimingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('arrival', 'Arrival (Airport → Destination)'), ('return', 'Return (Destination → Airport)'), ('cruise', 'Cruise Transfer'), ('other', 'Other')], help_text='Type of trip (arrival, return, cruise, other)', max_length=20)),
                ('pickup_location_category', models.CharField(help_text="Categorized pickup location (e.g., 'MCO', 'Disney Resort', 'Universal Resort')", max_length=100)),
                ('dropoff_location_category', models.CharField(help_text='Categorized dropoff location', max_length=100)),
                ('time_of_day_category', models.CharField(choices=[('early_morning', 'Early Morning (4-7 AM)'), ('morning_rush', 'Morning Rush (7-10 AM)'), ('midday', 'Midday (10 AM - 2 PM)'), ('afternoon', 'Afternoon (2-6 PM)'), ('evening', 'Evening (6-10 PM)'), ('night', 'Night (10 PM - 4 AM)')], help_text='Time of day category for this metric', max_length=20)),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend'), ('holiday', 'Holiday')], help_text='Day type (weekday, weekend, holiday)', max_length=20)),
                ('avg_airport_dwell_time', models.IntegerField(blank=True, help_text='Average time from gate arrival to picked up (arrivals only)', null=True)),
                ('median_airport_dwell_time', models.IntegerField(blank=True, help_text='Median dwell time for more accurate estimates', null=True)),
                ('p90_airport_dwell_time', models.IntegerField(blank=True, help_text='90th percentile for conservative scheduling', null=True)),
                ('avg_drive_time', models.IntegerField(blank=True, help_text='Average time from picked up to completed', null=True)),
                ('median_drive_time', models.IntegerField(blank=True, help_text='Median drive time', null=True)),
                ('p90_drive_time', models.IntegerField(blank=True, help_text='90th percentile drive time', null=True)),
                ('avg_total_time', models.IntegerField(blank=True, help_text='Average total time from gate arrival/scheduled pickup to completed', null=True)),
                ('sample_count', models.IntegerField(default=0, help_text='Number of historical legs used to calculate this metric')),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='When this metric was last recalculated')),
            ],
            options={
                'verbose_name': 'Route Timing Metric',
                'verbose_name_plural': 'Route Timing Metrics',
                'indexes': [models.Index(fields=['trip_type', 'pickup_location_category', 'dropoff_location_category'], name='reservation_trip_ty_8073eb_idx'), models.Index(fields=['time_of_day_category'], name='reservation_time_of_38cb58_idx'), models.Index(fields=['-last_calculated'], name='reservation_last_ca_a41997_idx')],
                'unique_together': {('trip_type', 'pickup_location_category', 'dropoff_location_category', 'time_of_day_category', 'day_type')},
            },
        ),
        migrations.CreateModel(
            name='DriverDailyCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of this capacity record')),
                ('total_legs', models.IntegerField(default=0, help_text='Total number of legs completed this day')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated this day', max_digits=10)),
                ('total_active_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours from first pickup to last dropoff', max_digits=5, null=True)),
                ('avg_turnaround_time', models.IntegerField(blank=True, help_text='Average minutes between jobs', null=True)),
                ('longest_gap_minutes', models.IntegerField(blank=True, help_text='Longest idle period between jobs', null=True)),
                ('arrival_count', models.IntegerField(default=0, help_text='Number of arrival legs (airport → destination)')),
                ('return_count', models.IntegerField(default=0, help_text='Number of return legs (destination → airport)')),
                ('cruise_count', models.IntegerField(default=0, help_text='Number of cruise transfer legs')),
                ('other_count', models.IntegerField(default=0, help_text='Number of other legs')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this record was last calculated')),
                ('driver', models.ForeignKey(help_text='The driver this capacity record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_capacity_records', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Driver Daily Capacity',
                'verbose_name_plural': 'Driver Daily Capacities',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['driver', '-date'], name='reservation_driver__a4b471_idx'), models.Index(fields=['-date'], name='reservation_date_bb40de_idx'), models.Index(fields=['-calculated_at'], name='reservation_calcula_966edc_idx')],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
