# Generated by Django 5.1.4 on 2026-02-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0068_demandpattern_routetimingmetric_driverdailycapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='routetimingmetric',
            name='median_total_time',
            field=models.IntegerField(blank=True, help_text='Median total time', null=True),
        ),
        migrations.AddField(
            model_name='routetimingmetric',
            name='p75_airport_dwell_time',
            field=models.IntegerField(blank=True, help_text='75th percentile dwell time for balanced scheduling', null=True),
        ),
        migrations.AddField(
            model_name='routetimingmetric',
            name='p75_drive_time',
            field=models.IntegerField(blank=True, help_text='75th percentile drive time for balanced scheduling', null=True),
        ),
        migrations.AddField(
            model_name='routetimingmetric',
            name='p75_total_time',
            field=models.IntegerField(blank=True, help_text='75th percentile total time', null=True),
        ),
        migrations.AddField(
            model_name='routetimingmetric',
            name='p90_total_time',
            field=models.IntegerField(blank=True, help_text='90th percentile total time', null=True),
        ),
    ]
