# Generated by Django 5.1.4 on 2026-02-10 20:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_add_driver_additional_field'),
        ('reservations', '0069_add_p75_and_total_percentiles_to_routetimingmetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(help_text='The date whose schedule was saved')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger', models.CharField(choices=[('manual', 'Manual Save'), ('before_reset', 'Auto-save Before Reset'), ('before_auto_assign', 'Auto-save Before Auto-Assign')], default='manual', max_length=30)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_count', models.IntegerField(default=0, help_text='Number of legs with drivers at snapshot time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSnapshotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('driver_assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_entries', to='reservations.leg')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reservations.schedulesnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='schedulesnapshot',
            index=models.Index(fields=['schedule_date', '-created_at'], name='reservation_schedul_a0f759_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesnapshotentry',
            index=models.Index(fields=['snapshot', 'leg'], name='reservation_snapsho_0e86e0_idx'),
        ),
    ]
