# Generated by Django 5.1.4 on 2026-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0070_schedulesnapshot_schedulesnapshotentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesnapshot',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes about why this snapshot was saved'),
        ),
    ]
