# Generated by Django 5.1.4 on 2026-02-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0072_leg_exclude_from_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='luggage_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('carry_on', 'Carry-On Only'),
                    ('checked', 'Checked Bags'),
                    ('mixed', 'Mixed / Not Sure'),
                ],
                default='',
                max_length=10,
            ),
        ),
    ]
