# Generated by Django 5.1.4 on 2026-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0073_add_luggage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='extra_boosters',
            field=models.PositiveIntegerField(default=0, verbose_name='Extra Boosters'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extra_carseats',
            field=models.PositiveIntegerField(default=0, verbose_name='Extra Car Seats'),
        ),
    ]
