# Generated by Django 5.1.4 on 2026-02-24 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0019_direction_field'),
        ('rates', '0021_add_included_seat_limits'),
        ('reservations', '0074_add_extra_seat_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['driver'], name='reservation_driver__8493b0_idx'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['status'], name='reservation_status_087f56_idx'),
        ),
    ]
