# Generated by Django 5.1.4 on 2026-03-03 04:47

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0019_direction_field"),
        ("rates", "0021_add_included_seat_limits"),
        ("reservations", "0075_add_leg_driver_status_indexes"),
        ("users", "0029_travelagent_include_in_confirmation_sms_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLeg",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("private_notes", models.TextField(blank=True, null=True)),
                (
                    "driver_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes added by the driver about this trip",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in-progress", "In-Progress"),
                            ("confirmed", "Confirmed"),
                            ("on-the-way", "On the Way"),
                            ("on-location", "On-Location"),
                            ("picked-up", "Picked-Up"),
                            ("completed", "Completed"),
                        ],
                        default="in-progress",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "driver_pay_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount to pay the driver (set by admin) - DEPRECATED: Use driver_base_pay + driver_gratuity",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "driver_base_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base pay amount for the driver (excluding gratuity)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "driver_gratuity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Gratuity amount for the driver",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "driver_additional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Additional pay amount (e.g., wait time, early morning bonus, etc.)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "revenue_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="This leg's portion of the reservation revenue",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "profit_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated profit (revenue share - driver payment)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "driver_assigned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when driver was last assigned/changed",
                        null=True,
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when leg status was last changed",
                        null=True,
                    ),
                ),
                (
                    "confirmation_sms_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When next-day confirmation SMS was sent (Twilio)",
                        null=True,
                    ),
                ),
                (
                    "exclude_from_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude this leg from route timing analytics (bad data)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cruise_information",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reservations.cruise",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="drivers.driver",
                    ),
                ),
                (
                    "driver_assigned_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who last assigned/changed the driver",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flight_information",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reservations.flight",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Matched route for this leg (auto-filled when possible)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rates.route",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who last changed the leg status",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical leg",
                "verbose_name_plural": "historical legs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReservation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("one_way", "One Way"), ("round_trip", "Round Trip")],
                        max_length=20,
                    ),
                ),
                ("passenger_count", models.PositiveIntegerField(default=1)),
                ("luggage_count", models.PositiveIntegerField(default=1)),
                (
                    "luggage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("carry_on", "Carry-On Only"),
                            ("checked", "Checked Bags"),
                            ("mixed", "Mixed / Not Sure"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("need_carseats", models.BooleanField(default=False)),
                (
                    "rf_carseats",
                    models.PositiveIntegerField(default=0, verbose_name="RF-Seat"),
                ),
                (
                    "ff_carseats",
                    models.PositiveBigIntegerField(default=0, verbose_name="FF-Seat"),
                ),
                (
                    "booster_seats",
                    models.PositiveIntegerField(default=0, verbose_name="Booster"),
                ),
                (
                    "extra_carseats",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Extra Car Seats"
                    ),
                ),
                (
                    "extra_boosters",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Extra Boosters"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, db_index=True, default=uuid.uuid4, editable=False
                    ),
                ),
                ("store_stop", models.BooleanField(default=False)),
                ("special_requests", models.TextField(blank=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gratuity_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gratuity_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("canceled", "Canceled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("private_notes", models.TextField(blank=True, null=True)),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("commission_paid", models.BooleanField(default=False)),
                ("commission_paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_driver_payments",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of all driver payments",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "profit_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated profit (total price - driver payments)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gclid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Google Click ID for conversion tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fbclid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Facebook Click ID for conversion tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UTM source parameter",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True,
                        help_text="UTM medium parameter",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True,
                        help_text="UTM campaign parameter",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True,
                        help_text="UTM term parameter",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True,
                        help_text="UTM content parameter",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last modification",
                        null=True,
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("none", "No Refund Requested"),
                            ("requested", "Refund Requested"),
                            ("processing", "Processing Refund"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Refund Completed"),
                        ],
                        default="none",
                        help_text="Current status of refund request",
                        max_length=20,
                    ),
                ),
                (
                    "refund_requested_at",
                    models.DateTimeField(
                        blank=True, help_text="When the refund was requested", null=True
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for refund request from staff",
                        null=True,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount to refund (can be partial or full)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "refund_processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the refund was processed", null=True
                    ),
                ),
                (
                    "refund_notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes about the refund processing",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this reservation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reservations.customer",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who last modified this reservation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rates.rate",
                    ),
                ),
                (
                    "refund_processed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Admin who processed the refund",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Staff member who requested the refund",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "travel_agent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="users.travelagent",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rates.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reservation",
                "verbose_name_plural": "historical reservations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
