# Generated by Django 5.1.4 on 2026-03-05 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0077_historicalcustomer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalleg",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in-progress", "In-Progress"),
                    ("confirmed", "Confirmed"),
                    ("on-the-way", "On the Way"),
                    ("on-location", "On-Location"),
                    ("picked-up", "Picked-Up"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="in-progress",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leg",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in-progress", "In-Progress"),
                    ("confirmed", "Confirmed"),
                    ("on-the-way", "On the Way"),
                    ("on-location", "On-Location"),
                    ("picked-up", "Picked-Up"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="in-progress",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_type",
                    models.CharField(
                        choices=[
                            ("price_adjustment", "Price Adjustment"),
                            ("partial_cancellation", "Partial Cancellation"),
                            ("full_cancellation", "Full Cancellation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final approved refund amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "suggested_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Policy-calculated suggested refund amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "policy_override",
                    models.BooleanField(
                        default=False,
                        help_text="True if admin overrode the policy-suggested amount",
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for refund request")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about processing", null=True
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_refund_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Stripe refund IDs created for this request",
                    ),
                ),
                (
                    "legs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific legs included in this refund (empty = all legs for full cancellation)",
                        related_name="refund_requests",
                        to="reservations.leg",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="reservation_status_f6c312_idx"
                    ),
                    models.Index(
                        fields=["reservation", "status"],
                        name="reservation_reserva_60960b_idx",
                    ),
                ],
            },
        ),
    ]
