# Generated by Django 5.1.4 on 2026-03-05 05:38

from django.db import migrations


def migrate_existing_refunds(apps, schema_editor):
    """
    Copy existing flat refund_* fields from Reservation into the new RefundRequest model.
    This preserves all 61 completed + 13 pending refunds in production.
    The flat fields on Reservation are NOT removed — both systems coexist.
    """
    Reservation = apps.get_model('reservations', 'Reservation')
    RefundRequest = apps.get_model('reservations', 'RefundRequest')

    # Get all reservations with any refund activity
    refund_reservations = Reservation.objects.exclude(refund_status='none')

    for res in refund_reservations:
        # Map the old flat status to new RefundRequest status
        status_map = {
            'requested': 'requested',
            'processing': 'processing',
            'approved': 'approved',
            'rejected': 'rejected',
            'completed': 'completed',
        }
        new_status = status_map.get(res.refund_status, 'requested')

        # Create the RefundRequest record
        rr = RefundRequest.objects.create(
            reservation=res,
            refund_type='full_cancellation',  # Legacy refunds were all full-reservation level
            status=new_status,
            amount=res.refund_amount,
            suggested_amount=res.refund_amount,  # No policy engine existed before
            policy_override=False,
            reason=res.refund_reason or 'Migrated from legacy refund system',
            notes=res.refund_notes,
            requested_by_id=res.refund_requested_by_id,
            processed_by_id=res.refund_processed_by_id,
            processed_at=res.refund_processed_at,
        )

        # Fix requested_at (auto_now_add=True sets it to now, but we want the original)
        if res.refund_requested_at:
            RefundRequest.objects.filter(pk=rr.pk).update(
                requested_at=res.refund_requested_at
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse: delete all RefundRequest records that were created by this migration.
    The flat fields on Reservation are untouched.
    """
    RefundRequest = apps.get_model('reservations', 'RefundRequest')
    RefundRequest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0078_add_refundrequest_model_and_cancelled_status"),
    ]

    operations = [
        migrations.RunPython(migrate_existing_refunds, reverse_migration),
    ]
