# Generated by Django 5.1.4 on 2026-03-05 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0019_direction_field"),
        ("reservations", "0080_fix_legacy_pending_refund_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="The status when this location was captured",
                        max_length=30,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy_meters", models.FloatField(blank=True, null=True)),
                ("heading", models.FloatField(blank=True, null=True)),
                (
                    "speed_mps",
                    models.FloatField(
                        blank=True, help_text="Speed in meters/second", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "eta_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated minutes to destination (computed via Google Maps)",
                        null=True,
                    ),
                ),
                (
                    "eta_destination",
                    models.CharField(
                        blank=True,
                        help_text="The destination address used for ETA calculation",
                        max_length=255,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to="drivers.driver",
                    ),
                ),
                (
                    "leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_locations",
                        to="reservations.leg",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["leg", "-timestamp"],
                        name="reservation_leg_id_aa7669_idx",
                    ),
                    models.Index(
                        fields=["driver", "-timestamp"],
                        name="reservation_driver__f25ae7_idx",
                    ),
                ],
            },
        ),
    ]
