# Generated by Django 5.1.4 on 2026-03-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0081_add_driver_location_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_reservation',
            field=models.ForeignKey(blank=True, help_text='Reservation created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ghl_opportunity_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs_human_follow_up',
            field=models.BooleanField(default=False, help_text='Flagged for human closer after lead replied'),
        ),
        migrations.AddField(
            model_name='lead',
            name='segment',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('airport_transfer', 'Airport Transfer'), ('cruise_transfer', 'Cruise Transfer'), ('theme_park', 'Theme Park'), ('large_group', 'Large Group'), ('repeat_customer', 'Repeat Customer'), ('abandoned_quote', 'Abandoned Quote')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='sequence_active',
            field=models.BooleanField(default=False, help_text='Whether follow-up automation is running'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sequence_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('future_contact', 'Future Contact'), ('converted', 'Converted'), ('lost', 'Lost'), ('cold', 'Cold')], default='new', max_length=20),
        ),
    ]
