# Generated by Django 5.1.4 on 2026-03-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0084_backfill_lost_leads"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="initial_email_sent",
            field=models.BooleanField(
                default=False, help_text="Fallback email sent when SMS failed"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="initial_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
