# Generated by Django 5.1.4 on 2026-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0086_backfill_lead_converted_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email_invalid",
            field=models.BooleanField(
                default=False,
                help_text="Email failed deliverability check (no MX, disposable, junk)",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_invalid_reason",
            field=models.CharField(
                blank=True, help_text="Why email was marked invalid", max_length=50
            ),
        ),
    ]
