# Generated by Django 5.1.4 on 2026-03-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0087_lead_email_invalid_lead_email_invalid_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email_invalid',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email_invalid_reason',
        ),
    ]
