# Generated by Django 5.1.4 on 2026-03-18 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0021_add_included_seat_limits"),
        ("reservations", "0088_remove_lead_email_invalid_and_more"),
        ("users", "0029_travelagent_include_in_confirmation_sms_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="reservation_status_404d08_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["pickup_date"], name="reservation_pickup__e41f8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["created_at"], name="reservation_created_fe84d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "pickup_date"], name="reservation_status_a01840_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["travel_agent", "status"], name="reservation_travel__891186_idx"
            ),
        ),
    ]
