# Generated by Django 5.1.4 on 2026-03-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0088_remove_lead_email_invalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
