# Generated by Django 5.1.4 on 2026-03-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0089_add_missing_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="normalized_phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Last 10 digits of phone (auto-populated on save). Used for fast dedup lookups.",
                max_length=10,
            ),
        ),
    ]
