# Generated by Django 5.1.4 on 2026-03-18 03:00

from django.db import migrations


def backfill_normalized_phone(apps, schema_editor):
    """Populate normalized_phone for all existing leads."""
    Lead = apps.get_model("reservations", "Lead")
    leads_to_update = []
    for lead in Lead.objects.exclude(phone="").exclude(phone__isnull=True).iterator():
        digits = "".join(filter(str.isdigit, lead.phone))
        norm = digits[-10:] if len(digits) >= 10 else ""
        if norm and lead.normalized_phone != norm:
            lead.normalized_phone = norm
            leads_to_update.append(lead)
            if len(leads_to_update) >= 500:
                Lead.objects.bulk_update(leads_to_update, ["normalized_phone"])
                leads_to_update = []
    if leads_to_update:
        Lead.objects.bulk_update(leads_to_update, ["normalized_phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0090_add_lead_normalized_phone"),
    ]

    operations = [
        migrations.RunPython(backfill_normalized_phone, migrations.RunPython.noop),
    ]
