# Generated by Django 5.1.4 on 2026-03-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0089_zipcode_optional"),
        ("reservations", "0091_backfill_lead_normalized_phone"),
    ]

    operations = []
