# Generated by Django 5.1.4 on 2026-04-15 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0021_add_included_seat_limits'),
        ('reservations', '0093_reservation_attribution_and_paid_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleg',
            name='booster_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Override booster seats. NULL = use reservation value.', null=True, verbose_name='Booster'),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='extra_boosters',
            field=models.PositiveIntegerField(blank=True, help_text='Override extra boosters. NULL = use reservation value.', null=True, verbose_name='Extra Boosters'),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='extra_carseats',
            field=models.PositiveIntegerField(blank=True, help_text='Override extra car seats. NULL = use reservation value.', null=True, verbose_name='Extra Car Seats'),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='ff_carseats',
            field=models.PositiveIntegerField(blank=True, help_text='Override forward-facing car seats. NULL = use reservation value.', null=True, verbose_name='FF-Seat'),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='leg_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for this leg. NULL = equal split of reservation base_price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='leg_rate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Rate for this leg's vehicle+route. NULL = use reservation rate.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rates.rate'),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='luggage_count',
            field=models.PositiveIntegerField(blank=True, help_text='Override luggage count. NULL = use reservation value.', null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='luggage_type',
            field=models.CharField(blank=True, default='', help_text='Override luggage type. Empty = use reservation value.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='need_carseats',
            field=models.BooleanField(blank=True, help_text='Override car seat requirement. NULL = use reservation value.', null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='passenger_count',
            field=models.PositiveIntegerField(blank=True, help_text='Override passenger count. NULL = use reservation value.', null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='rf_carseats',
            field=models.PositiveIntegerField(blank=True, help_text='Override rear-facing car seats. NULL = use reservation value.', null=True, verbose_name='RF-Seat'),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Override vehicle for this leg. NULL = use reservation vehicle.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rates.vehicle'),
        ),
        migrations.AddField(
            model_name='leg',
            name='booster_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Override booster seats. NULL = use reservation value.', null=True, verbose_name='Booster'),
        ),
        migrations.AddField(
            model_name='leg',
            name='extra_boosters',
            field=models.PositiveIntegerField(blank=True, help_text='Override extra boosters. NULL = use reservation value.', null=True, verbose_name='Extra Boosters'),
        ),
        migrations.AddField(
            model_name='leg',
            name='extra_carseats',
            field=models.PositiveIntegerField(blank=True, help_text='Override extra car seats. NULL = use reservation value.', null=True, verbose_name='Extra Car Seats'),
        ),
        migrations.AddField(
            model_name='leg',
            name='ff_carseats',
            field=models.PositiveIntegerField(blank=True, help_text='Override forward-facing car seats. NULL = use reservation value.', null=True, verbose_name='FF-Seat'),
        ),
        migrations.AddField(
            model_name='leg',
            name='leg_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for this leg. NULL = equal split of reservation base_price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='leg_rate',
            field=models.ForeignKey(blank=True, help_text="Rate for this leg's vehicle+route. NULL = use reservation rate.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='rates.rate'),
        ),
        migrations.AddField(
            model_name='leg',
            name='luggage_count',
            field=models.PositiveIntegerField(blank=True, help_text='Override luggage count. NULL = use reservation value.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='luggage_type',
            field=models.CharField(blank=True, default='', help_text='Override luggage type. Empty = use reservation value.', max_length=10),
        ),
        migrations.AddField(
            model_name='leg',
            name='need_carseats',
            field=models.BooleanField(blank=True, help_text='Override car seat requirement. NULL = use reservation value.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='passenger_count',
            field=models.PositiveIntegerField(blank=True, help_text='Override passenger count. NULL = use reservation value.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='rf_carseats',
            field=models.PositiveIntegerField(blank=True, help_text='Override rear-facing car seats. NULL = use reservation value.', null=True, verbose_name='RF-Seat'),
        ),
        migrations.AddField(
            model_name='leg',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Override vehicle for this leg. NULL = use reservation vehicle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='rates.vehicle'),
        ),
    ]
