# Generated by Django 5.1.4 on 2026-04-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0094_leg_trip_detail_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleg',
            name='confirmation_sms_override',
            field=models.TextField(blank=True, default='', help_text='Custom confirmation SMS body for this leg. When set, it replaces the auto-generated message body. The standard footer is still appended.'),
        ),
        migrations.AddField(
            model_name='leg',
            name='confirmation_sms_override',
            field=models.TextField(blank=True, default='', help_text='Custom confirmation SMS body for this leg. When set, it replaces the auto-generated message body. The standard footer is still appended.'),
        ),
    ]
