# Generated by Django 5.1.4 on 2026-04-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0022_add_locationgroup_and_extra_stop_fee'),
        ('reservations', '0095_leg_confirmation_sms_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='requires_manual_review',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this reservation has a stop or detail needing dispatcher pricing review before charging'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requires_manual_review',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this reservation has a stop or detail needing dispatcher pricing review before charging'),
        ),
        migrations.CreateModel(
            name='LegFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_controlling', models.BooleanField(default=False, help_text='True for the flight that determines pickup timing (the later-arriving flight, by convention)')),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower values shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legflights', to='reservations.flight')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legflight_set', to='reservations.leg')),
            ],
            options={
                'ordering': ['leg_id', 'sequence', 'id'],
                'indexes': [models.Index(fields=['leg', 'is_controlling'], name='reservation_leg_id_ba9953_idx')],
                'constraints': [models.UniqueConstraint(fields=('leg', 'flight'), name='legflight_unique_leg_flight'), models.UniqueConstraint(condition=models.Q(('is_controlling', True)), fields=('leg',), name='legflight_one_controlling_per_leg')],
            },
        ),
        migrations.CreateModel(
            name='LegStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text="Order between the leg's pickup and dropoff anchors (0, 1, 2, ...)")),
                ('location_text', models.CharField(help_text='Free-text address or venue name for this stop', max_length=255)),
                ('stop_type', models.CharField(choices=[('dropoff', 'Drop-off'), ('pickup', 'Pickup'), ('luggage', 'Luggage drop'), ('wait', 'Wait / hold'), ('other', 'Other')], default='dropoff', max_length=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=10, help_text='Estimated minutes the chauffeur will be stopped here')),
                ('notes', models.TextField(blank=True)),
                ('extra_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of the per-stop fee at creation. NULL = manual review pending or fee not yet quoted.', max_digits=10, null=True)),
                ('requires_manual_review', models.BooleanField(default=False, help_text="True for out-of-area or 'Other' stops needing a custom quote before charging")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legstop_set', to='reservations.leg')),
                ('location', models.ForeignKey(blank=True, help_text='Structured Location match — populated when location_text matches a known Location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legstops', to='rates.location')),
            ],
            options={
                'ordering': ['leg_id', 'sequence'],
                'indexes': [models.Index(fields=['leg', 'sequence'], name='reservation_leg_id_b65a80_idx'), models.Index(fields=['requires_manual_review'], name='reservation_require_1585da_idx')],
                'unique_together': {('leg', 'sequence')},
            },
        ),
    ]
