# Generated by Django 5.1.4 on 2026-05-18 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0022_add_locationgroup_and_extra_stop_fee'),
        ('reservations', '0101_backfill_legflight_for_orphan_flight_information'),
        ('users', '0030_add_payout_reference_and_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='legstop',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Estimated minutes the chauffeur will be stopped here. For charter, this stores hours × 60.'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(condition=models.Q(('commission_paid', False), ('status', 'completed')), fields=['travel_agent', 'created_at'], name='res_unpaid_completed_agent_idx'),
        ),
    ]
