# Generated by Django 5.1.4 on 2026-05-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0102_reservation_unpaid_completed_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_auto_cancel_eligible_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the reservation crosses pickup-2h still unpaid. v1 surfaces this for manual review; future versions may auto-cancel from this signal.', null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_auto_reminder_hold',
            field=models.BooleanField(db_index=True, default=False, help_text='Staff override — when True, the automated reminder pipeline skips this reservation entirely.'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_auto_reminder_hold_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_duplicate_suspected',
            field=models.BooleanField(db_index=True, default=False, help_text='Set by the duplicate guard in the reminder engine. Clears when staff resolves via /duplicate-reservations/.'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_final_warning_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_first_reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_second_reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='unpaid_three_day_warning_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_auto_cancel_eligible_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the reservation crosses pickup-2h still unpaid. v1 surfaces this for manual review; future versions may auto-cancel from this signal.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_auto_reminder_hold',
            field=models.BooleanField(db_index=True, default=False, help_text='Staff override — when True, the automated reminder pipeline skips this reservation entirely.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_auto_reminder_hold_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_duplicate_suspected',
            field=models.BooleanField(db_index=True, default=False, help_text='Set by the duplicate guard in the reminder engine. Clears when staff resolves via /duplicate-reservations/.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_final_warning_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_first_reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_second_reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='unpaid_three_day_warning_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
