# Generated by Django 5.1.4 on 2026-05-24 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0104_leg_flight_verification_email_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='commission_excluded',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually excluded from commission (e.g. personal trip with discount).'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='commission_excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='commission_excluded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who flagged this reservation as non-commissionable.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='commission_exclusion_reason',
            field=models.CharField(blank=True, help_text='Why this reservation was excluded from commission (shown in the Excluded bucket).', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commission_excluded',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually excluded from commission (e.g. personal trip with discount).'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commission_excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commission_excluded_by',
            field=models.ForeignKey(blank=True, help_text='User who flagged this reservation as non-commissionable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_exclusions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='commission_exclusion_reason',
            field=models.CharField(blank=True, help_text='Why this reservation was excluded from commission (shown in the Excluded bucket).', max_length=255),
        ),
    ]
