# Generated by Django 5.1.4 on 2026-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0105_historicalreservation_commission_excluded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalleg",
            name="afterhours_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="After-hours fee currently applied for this leg (pickup 10 PM-6 AM). Set at booking and reconciled when a flight delay shifts the pickup into/out of the window. 0 = none applied.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="afterhours_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="After-hours fee currently applied for this leg (pickup 10 PM-6 AM). Set at booking and reconciled when a flight delay shifts the pickup into/out of the window. 0 = none applied.",
                max_digits=6,
            ),
        ),
    ]
