# Generated by Django 5.1.4 on 2026-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0107_backfill_afterhours_fee_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pre_pickup_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deliberate discount ($) for the pre-pickup nudge. Default 0. When > 0, the lead is routed to a human to book with the discount applied.', max_digits=10),
        ),
    ]
