# Generated by Django 5.1.4 on 2026-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0108_lead_pre_pickup_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sms_opt_out',
            field=models.BooleanField(db_index=True, default=False, help_text='Contact opted out of SMS (replied STOP/UNSUBSCRIBE/etc). Blocks all outbound SMS.'),
        ),
    ]
