# Generated by Django 5.1.4 on 2026-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0109_lead_sms_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='purchase_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable Meta Purchase dedup event_id (browser pixel + CAPI)', max_length=64),
        ),
        migrations.AddField(
            model_name='reservation',
            name='purchase_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable Meta Purchase dedup event_id (browser pixel + CAPI)', max_length=64),
        ),
    ]
