# Generated by Django 5.1.4 on 2026-06-03 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0030_add_driver_is_active'),
        ('reservations', '0109_lead_sms_opt_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(db_index=True, help_text='The date this draft holds')),
                ('state', models.CharField(choices=[('draft', 'Draft (building)'), ('in_review', 'Submitted for review'), ('changes_requested', 'Changes requested'), ('published', 'Published'), ('discarded', 'Discarded')], default='draft', max_length=20)),
                ('baseline_leg_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('base_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='reservations.schedulesnapshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts_created', to=settings.AUTH_USER_MODEL)),
                ('notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts_notified', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts_published', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_assignments', to='reservations.leg')),
                ('proposed_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_assignments', to='drivers.driver')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reservations.scheduledraft')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDraftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Draft opened'), ('edited', 'Assignment edited'), ('submitted', 'Submitted for review'), ('approved', 'Approved & published'), ('rejected', 'Changes requested'), ('published', 'Published to live'), ('notified', 'Drivers notified (SMS)'), ('discarded', 'Draft discarded'), ('conflict', 'Conflict detected')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_events', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservations.scheduledraft')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledraft',
            index=models.Index(fields=['schedule_date', 'state'], name='reservation_schedul_077eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledraft',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['draft', 'in_review', 'changes_requested'])), fields=('schedule_date',), name='uniq_active_draft_per_date'),
        ),
        migrations.AddIndex(
            model_name='draftassignment',
            index=models.Index(fields=['draft', 'leg'], name='reservation_draft_i_e61db1_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftassignment',
            constraint=models.UniqueConstraint(fields=('draft', 'leg'), name='uniq_draft_leg'),
        ),
        migrations.AddIndex(
            model_name='scheduledraftevent',
            index=models.Index(fields=['draft', 'created_at'], name='reservation_draft_i_1f55b6_idx'),
        ),
    ]
