# Generated by Django 5.1.4 on 2026-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0109_lead_sms_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreservation",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
