# Generated by Django 5.1.4 on 2026-06-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0110_historicalreservation_is_vip_reservation_is_vip"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_eta_evaluated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the sweep last computed this. Render only while fresh.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_eta_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Live drive-time (min) from the assigned vehicle's GPS to this leg's relevant target.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_eta_target",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What the ETA is to: pickup / dropoff / next_pickup.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_eta_target_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled (flight-aware) time of the target, for the slack/late comparison.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_risk_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable reason shown on hover.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_risk_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On time"),
                    ("watch", "Watch"),
                    ("at_risk", "At risk"),
                    ("late", "Late"),
                    ("unknown", "Unknown (telematics stale)"),
                ],
                db_index=True,
                default="",
                help_text="Will-he-make-it band driving the board badge color.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_eta_evaluated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the sweep last computed this. Render only while fresh.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_eta_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Live drive-time (min) from the assigned vehicle's GPS to this leg's relevant target.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_eta_target",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What the ETA is to: pickup / dropoff / next_pickup.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_eta_target_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled (flight-aware) time of the target, for the slack/late comparison.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_risk_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable reason shown on hover.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_risk_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On time"),
                    ("watch", "Watch"),
                    ("at_risk", "At risk"),
                    ("late", "Late"),
                    ("unknown", "Unknown (telematics stale)"),
                ],
                db_index=True,
                default="",
                help_text="Will-he-make-it band driving the board badge color.",
                max_length=16,
            ),
        ),
    ]
