# Generated by Django 5.1.4 on 2026-06-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0110_scheduledraft_draftassignment_scheduledraftevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledraft',
            options={'ordering': ['-created_at'], 'permissions': [('use_schedule_sandbox', 'Can build/hold sandbox schedules')]},
        ),
    ]
