# Generated by Django 5.1.4 on 2026-06-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0111_historicalleg_dispatch_eta_evaluated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_is_moving",
            field=models.BooleanField(
                blank=True,
                help_text="Snapshot of whether the assigned vehicle was moving at sweep time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_stationary_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="How long the assigned vehicle had been stationary at sweep time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_is_moving",
            field=models.BooleanField(
                blank=True,
                help_text="Snapshot of whether the assigned vehicle was moving at sweep time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_stationary_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="How long the assigned vehicle had been stationary at sweep time.",
                null=True,
            ),
        ),
    ]
