# Generated by Django 5.1.4 on 2026-06-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0111_alter_scheduledraft_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledraft',
            name='baseline_legs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
