# Generated by Django 5.1.4 on 2026-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0112_historicalleg_dispatch_is_moving_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalleg",
            name="dispatch_vehicle_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Assigned vehicle number snapshot, shown in the live-tracking panel.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="dispatch_vehicle_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Assigned vehicle number snapshot, shown in the live-tracking panel.",
                max_length=50,
            ),
        ),
    ]
