# Generated by Django 5.1.4 on 2026-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0114_scheduledraft_draftassignment_scheduledraftevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleg',
            name='dispatch_eta_origin_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vehicle GPS latitude the stored dispatch_eta_minutes was computed against.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='dispatch_eta_origin_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vehicle GPS longitude the stored dispatch_eta_minutes was computed against.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='dispatch_eta_origin_target',
            field=models.CharField(blank=True, default='', help_text='Target location string the stored ETA was computed against; a change forces a fresh lookup.', max_length=255),
        ),
        migrations.AddField(
            model_name='leg',
            name='dispatch_eta_origin_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vehicle GPS latitude the stored dispatch_eta_minutes was computed against.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='dispatch_eta_origin_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vehicle GPS longitude the stored dispatch_eta_minutes was computed against.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='dispatch_eta_origin_target',
            field=models.CharField(blank=True, default='', help_text='Target location string the stored ETA was computed against; a change forces a fresh lookup.', max_length=255),
        ),
    ]
