# Generated by Django 5.1.4 on 2026-06-17 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0023_vehicle_requires_certification'),
        ('reservations', '0115_historicalleg_dispatch_eta_origin_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='quoted_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours booked for an hourly charter.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='service_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('hourly', 'Hourly Charter'), ('city_to_city', 'City-to-City')], db_index=True, default='transfer', help_text='Which service line this booking belongs to.', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='quoted_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours booked for an hourly charter.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('hourly', 'Hourly Charter'), ('city_to_city', 'City-to-City')], db_index=True, default='transfer', help_text='Which service line this booking belongs to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rates.rate'),
        ),
    ]
