# Generated by Django 5.1.4 on 2026-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0117_reclassify_booking_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="referrer_host",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="First-touch external referrer host (fallback attribution when no UTM source)",
                max_length=255,
                null=True,
            ),
        ),
    ]
