# Generated by Django 5.1.4 on 2026-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0118_lead_referrer_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="departure_date",
            field=models.DateField(
                blank=True,
                help_text="Takeoff date (Eastern) for this flight — guest-confirmed or staff-set. Disambiguates overnight red-eyes: the same flight number lands just after midnight every night, so only the departure date pins which instance the guest is on. When set, AeroAPI lookups anchor on this date instead of the leg's pickup date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="overnight_confirm_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the overnight date-confirmation email (one-tap takeoff-date question) was last sent to the guest.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="overnight_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the guest (or staff) confirmed which night this overnight arrival actually lands. Once set, the pickup date is trusted and no confirmation call/email is needed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalleg",
            name="overnight_confirmed_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="How the overnight date was confirmed: booking_form | one_tap | staff.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="overnight_confirm_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the overnight date-confirmation email (one-tap takeoff-date question) was last sent to the guest.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="overnight_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the guest (or staff) confirmed which night this overnight arrival actually lands. Once set, the pickup date is trusted and no confirmation call/email is needed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leg",
            name="overnight_confirmed_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="How the overnight date was confirmed: booking_form | one_tap | staff.",
                max_length=20,
            ),
        ),
    ]
