# Generated by Django 5.1.4 on 2026-07-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0120_perf_hot_path_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleg',
            name='pickup_change_ack_at',
            field=models.DateTimeField(blank=True, help_text='When a dispatcher acknowledged the pickup-time change on the board.', null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='pickup_time_changed_at',
            field=models.DateTimeField(blank=True, help_text='When pickup_time last changed on an existing leg.', null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='pickup_time_was',
            field=models.TimeField(blank=True, help_text='Pickup time before the earliest still-unacknowledged change.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='pickup_change_ack_at',
            field=models.DateTimeField(blank=True, help_text='When a dispatcher acknowledged the pickup-time change on the board.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='pickup_time_changed_at',
            field=models.DateTimeField(blank=True, help_text='When pickup_time last changed on an existing leg.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='pickup_time_was',
            field=models.TimeField(blank=True, help_text='Pickup time before the earliest still-unacknowledged change.', null=True),
        ),
    ]
