# Generated by Django 5.1.4 on 2026-07-24 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0121_historicalleg_pickup_change_ack_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegKeoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tight_schedule', 'Tight Schedule'), ('driver_conflict', 'Possible Driver Conflict'), ('flight_delay', 'Flight Delay Risk'), ('passenger_readiness', 'Passenger Readiness Risk'), ('traffic', 'Traffic Risk'), ('waiting_info', 'Waiting on Information'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('operational_status', models.CharField(choices=[('needs_attention', 'Needs Attention'), ('being_monitored', 'Being Monitored'), ('backup_arranged', 'Backup Arranged')], default='needs_attention', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, choices=[('leg_completed', 'Leg Completed'), ('leg_cancelled', 'Leg Cancelled'), ('admin_removed', 'Removed by Admin')], max_length=20, null=True)),
                ('removal_reason', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keoi_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keoi_created', to=settings.AUTH_USER_MODEL)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keoi_flags', to='reservations.leg')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keoi_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('remove_keoi', 'Can remove KEOI flags (with reason)')],
                'indexes': [models.Index(fields=['leg', '-created_at'], name='reservation_leg_id_4a5e4e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('leg',), name='uniq_active_keoi_per_leg'), models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_reason__isnull', True)), models.Q(('closed_at__isnull', False), ('closed_reason__isnull', False)), _connector='OR'), name='keoi_closed_fields_paired')],
            },
        ),
    ]
