# Generated by Django 5.1.4 on 2026-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0122_legkeoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDistanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('pickup_text', models.CharField(max_length=500)),
                ('dropoff_text', models.CharField(max_length=500)),
                ('drive_minutes', models.PositiveIntegerField(blank=True, help_text='Google Distance Matrix traffic-aware drive time, rounded to minutes.', null=True)),
                ('distance_text', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending resolution'), ('ok', 'Resolved'), ('failed', 'Failed (address unresolvable)')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Route Distance Cache',
                'verbose_name_plural': 'Route Distance Cache',
                'indexes': [models.Index(fields=['status', 'resolved_at'], name='reservation_status_a49b4e_idx')],
            },
        ),
    ]
