# Generated by Django 5.1.4 on 2026-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0124_schedulesnapshot_conflict_advisor_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleg',
            name='pickup_date_was',
            field=models.DateField(blank=True, help_text='Pickup DATE before the earliest still-unacknowledged change. Set only when a move crossed the calendar day — a day move is the dangerous one (the trip silently leaves the board it was on), so the badge has to say so, not just show a new time.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='pickup_date_was',
            field=models.DateField(blank=True, help_text='Pickup DATE before the earliest still-unacknowledged change. Set only when a move crossed the calendar day — a day move is the dangerous one (the trip silently leaves the board it was on), so the badge has to say so, not just show a new time.', null=True),
        ),
    ]
