# Generated by Django 5.1.4 on 2026-08-10 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0049_driver_portal_role'),
        ('reservations', '0124_schedulesnapshot_conflict_advisor_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleg',
            name='operator_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the operator accepted this farm-out in their portal.', null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='operator_decline_reason',
            field=models.CharField(blank=True, default='', help_text='Why the operator turned the job down (no car, already booked, rate).', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='operator_declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='operator_declined_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Operator who gave this leg back. Kept after the unassign so the board can say who declined.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='operator_driver_name',
            field=models.CharField(blank=True, default='', help_text="Name of the operator's own chauffeur on this leg. Typed by the operator; blank until they assign it.", max_length=120),
        ),
        migrations.AddField(
            model_name='historicalleg',
            name='operator_driver_phone',
            field=models.CharField(blank=True, default='', help_text="Cell for the operator's chauffeur, so dispatch can reach the actual driver.", max_length=25),
        ),
        migrations.AddField(
            model_name='leg',
            name='operator_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the operator accepted this farm-out in their portal.', null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='operator_decline_reason',
            field=models.CharField(blank=True, default='', help_text='Why the operator turned the job down (no car, already booked, rate).', max_length=255),
        ),
        migrations.AddField(
            model_name='leg',
            name='operator_declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='operator_declined_by',
            field=models.ForeignKey(blank=True, help_text='Operator who gave this leg back. Kept after the unassign so the board can say who declined.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_legs', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='leg',
            name='operator_driver_name',
            field=models.CharField(blank=True, default='', help_text="Name of the operator's own chauffeur on this leg. Typed by the operator; blank until they assign it.", max_length=120),
        ),
        migrations.AddField(
            model_name='leg',
            name='operator_driver_phone',
            field=models.CharField(blank=True, default='', help_text="Cell for the operator's chauffeur, so dispatch can reach the actual driver.", max_length=25),
        ),
    ]
