# Generated by Django 5.1.4 on 2026-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0125_leg_pickup_date_was"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Job Assigned"),
                    ("in-progress", "In Progress"),
                    ("confirmed", "Confirmed"),
                    ("on-the-way", "On the Way"),
                    ("on-location", "On Location"),
                    ("picked-up", "Picked Up"),
                    ("store-arrived", "At Store"),
                    ("store-departed", "Left Store"),
                    ("store-skipped", "Store Stop Skipped"),
                    ("completed", "Completed"),
                ],
                help_text="The status at this point in time",
                max_length=30,
            ),
        ),
    ]
