# Generated by Django 5.1.4 on 2026-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0126_historicalleg_operator_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legkeoi',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('leg_completed', 'Leg Completed'), ('leg_cancelled', 'Leg Cancelled'), ('admin_removed', 'Removed by Admin'), ('conflict_resolved', 'Conflict Resolved')], max_length=20, null=True),
        ),
    ]
