# Generated by Django 5.1.4 on 2026-08-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0127_alter_legkeoi_closed_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleg',
            name='pay_manually_set',
            field=models.BooleanField(default=False, help_text="True when a person typed this leg's pay instead of the system computing it. Automatic recalculation (a pickup time move, an address edit) leaves these legs alone. Cleared when the driver changes, since the typed amount belonged to the previous driver."),
        ),
        migrations.AddField(
            model_name='leg',
            name='pay_manually_set',
            field=models.BooleanField(default=False, help_text="True when a person typed this leg's pay instead of the system computing it. Automatic recalculation (a pickup time move, an address edit) leaves these legs alone. Cleared when the driver changes, since the typed amount belonged to the previous driver."),
        ),
    ]
