# Generated by Django 5.1.4 on 2026-08-19 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0049_driver_portal_role'),
        ('reservations', '0128_historicalleg_pay_manually_set_leg_pay_manually_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('on_the_way', 'On the way'), ('on_location', 'On location'), ('review', 'Review request')], help_text='Which of the three standard moments this message covers.', max_length=20)),
                ('situation', models.CharField(blank=True, default='', help_text="Trip situation the copy was chosen for (arrival_tracked, departure, cruise_from_port, ...). Stored so reworded templates don't retroactively change what we think was sent.", max_length=30)),
                ('body', models.TextField(blank=True, default='', help_text='The text handed to the composer. The chauffeur may have edited it before sending — this is our side of the handoff.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, help_text="Chauffeur credited with the message. Denormalised from the leg at tap time so a later reassignment can't rewrite history.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_messages', to='drivers.driver')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='reservations.leg')),
                ('sent_by', models.ForeignKey(blank=True, help_text="User account that tapped. Normally the driver's own login.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Message Sent',
                'verbose_name_plural': 'Client Messages Sent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['leg', 'kind'], name='reservation_leg_id_16f90a_idx'), models.Index(fields=['driver', '-created_at'], name='reservation_driver__9d285a_idx'), models.Index(fields=['kind', '-created_at'], name='reservation_kind_1a21f5_idx')],
            },
        ),
    ]
