# Generated by Django 5.1.4 on 2026-10-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0129_legclientmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'ordering': ['-requested_at'], 'permissions': [('approve_refund', 'Can approve or reject refund requests')]},
        ),
    ]
