# Generated by Django 5.1.4 on 2026-04-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0025_fleetvehicle_is_active_fleetvehicle_license_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamsaraMaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samsara_issue_id', models.CharField(max_length=64, unique=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('samsara_url', models.URLField(blank=True)),
                ('fleet_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='drivers.fleetvehicle')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['fleet_vehicle', 'resolved_at'], name='samsara_int_fleet_v_2e4de2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SamsaraVehicleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('speed_mph', models.FloatField(blank=True, null=True)),
                ('heading_degrees', models.FloatField(blank=True, null=True)),
                ('fuel_percent', models.IntegerField(blank=True, null=True)),
                ('odometer_miles', models.IntegerField(blank=True, null=True)),
                ('engine_state', models.CharField(blank=True, max_length=20)),
                ('formatted_address', models.CharField(blank=True, max_length=255)),
                ('location_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('fleet_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='samsara_snapshot', to='drivers.fleetvehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='samsara_int_fetched_58cc9a_idx')],
            },
        ),
    ]
