# Generated by Django 5.1.4 on 2026-03-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0082_lead_followup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(help_text='Step in the sequence (1-5)')),
                ('segment', models.CharField(choices=[('general', 'General'), ('airport_transfer', 'Airport Transfer'), ('cruise_transfer', 'Cruise Transfer'), ('theme_park', 'Theme Park'), ('large_group', 'Large Group'), ('repeat_customer', 'Repeat Customer'), ('abandoned_quote', 'Abandoned Quote')], default='general', max_length=30)),
                ('delay_hours', models.PositiveIntegerField(help_text='Hours after Step 1 send for this step (0=immediate, 4, 20, 48, 96)')),
                ('message_template', models.TextField(help_text='SMS body with {first_name}, {pickup_location}, {dropoff_location}, {pickup_date}, {estimated_price}, {vehicle_name} placeholders')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Follow-Up Sequence Template',
                'verbose_name_plural': 'Follow-Up Sequence Templates',
                'ordering': ['segment', 'step_number'],
                'unique_together': {('step_number', 'segment')},
            },
        ),
        migrations.CreateModel(
            name='GHLSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_contact', 'Create Contact'), ('send_sms', 'Send SMS'), ('update_status', 'Update Status'), ('add_tag', 'Add Tag')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='reservations.lead')),
            ],
            options={
                'verbose_name': 'GHL Sync Log',
                'verbose_name_plural': 'GHL Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('sms_sent', 'SMS Sent'), ('sms_failed', 'SMS Failed'), ('reply_received', 'Reply Received'), ('converted', 'Converted'), ('status_change', 'Status Change'), ('sequence_started', 'Sequence Started'), ('sequence_stopped', 'Sequence Stopped'), ('sequence_completed', 'Sequence Completed')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reservations.lead')),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('segment', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(help_text='When to send (already adjusted for send window)')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, help_text='replied, converted, expired_date', max_length=50)),
                ('message_body', models.TextField(blank=True, help_text='Rendered message saved after send for audit')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_tasks', to='reservations.lead')),
            ],
            options={
                'verbose_name': 'Follow-Up Task',
                'verbose_name_plural': 'Follow-Up Tasks',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='idx_task_status_sched')],
                'unique_together': {('lead', 'step_number')},
            },
        ),
    ]
