# Generated by Django 5.1.4 on 2026-03-11 22:56

from django.db import migrations


# Universal templates — used as the "general" segment defaults.
# Segment-specific overrides can be added later via Django admin.
TEMPLATES = [
    {
        "step_number": 1,
        "segment": "general",
        "delay_hours": 0,
        "message_template": (
            "Hey {first_name}, this is Grayson Towncar. "
            "Do you still need transportation from {pickup_location} to {dropoff_location} on {pickup_date}?"
        ),
    },
    {
        "step_number": 2,
        "segment": "general",
        "delay_hours": 4,
        "message_template": (
            "Hey {first_name}! Wanted to make sure my earlier message came through about your "
            "{pickup_location} \u2192 {dropoff_location} trip. A few things we handle that most don\u2019t expect: "
            "complimentary car seats, baggage claim meetup, and grocery stops along the way \u2014 no extra charge. "
            "Happy to hold your spot for {pickup_date} if you want to lock it in. Just say the word!"
        ),
    },
    {
        "step_number": 3,
        "segment": "general",
        "delay_hours": 20,
        "message_template": (
            "Hey {first_name} \u2014 honest question: still looking for a ride on {pickup_date}, or did you "
            "find something? Either way no worries! If you\u2019re still deciding, we\u2019ve got 1,000+ five-star "
            "reviews and I\u2019d love to answer anything before you book. Just shoot me a text \U0001f642"
        ),
    },
    {
        "step_number": 4,
        "segment": "general",
        "delay_hours": 48,
        "message_template": (
            "Hey {first_name}, your quoted rate of {estimated_price} for the {pickup_date} trip is still "
            "available \u2014 wanted to give you a heads up before it changes. I can send you the direct "
            "booking link if you want to grab it quick, takes under a minute. Want me to send it over?"
        ),
    },
    {
        "step_number": 5,
        "segment": "general",
        "delay_hours": 96,
        "message_template": (
            "Hey {first_name}, last message from me \u2014 totally understand if your plans changed or "
            "you went another direction. If you ever need a ride in Orlando, we\u2019re always here. "
            "Take care! \U0001f64f"
        ),
    },
]


def seed_templates(apps, schema_editor):
    FollowUpSequence = apps.get_model("ghl_integration", "FollowUpSequence")
    for t in TEMPLATES:
        FollowUpSequence.objects.update_or_create(
            step_number=t["step_number"],
            segment=t["segment"],
            defaults={
                "delay_hours": t["delay_hours"],
                "message_template": t["message_template"],
                "is_active": True,
            },
        )


def remove_templates(apps, schema_editor):
    FollowUpSequence = apps.get_model("ghl_integration", "FollowUpSequence")
    FollowUpSequence.objects.filter(segment="general").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ghl_integration", "0001_followup_engine_models"),
    ]

    operations = [
        migrations.RunPython(seed_templates, remove_templates),
    ]
