# Generated by Django 5.1.4 on 2026-03-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_integration', '0002_seed_followup_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlsynclog',
            name='action',
            field=models.CharField(choices=[('create_contact', 'Create Contact'), ('send_sms', 'Send SMS'), ('update_status', 'Update Status'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag')], max_length=30),
        ),
    ]
