# Generated by Django 5.1.4 on 2026-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_integration', '0003_add_remove_tag_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupsequence',
            name='delay_hours',
            field=models.PositiveIntegerField(help_text='Hours after Step 1 send for this step (0=immediate, 4, 20, 48, 96). Unused for the date-anchored step-6 nudge.'),
        ),
        migrations.AlterField(
            model_name='followupsequence',
            name='message_template',
            field=models.TextField(help_text='SMS body with {first_name}, {pickup_location}, {dropoff_location}, {pickup_date}, {estimated_price}, {vehicle_name} placeholders. Step-6 nudge templates also support {booking_link}.'),
        ),
        migrations.AlterField(
            model_name='followupsequence',
            name='segment',
            field=models.CharField(choices=[('general', 'General'), ('airport_transfer', 'Airport Transfer'), ('cruise_transfer', 'Cruise Transfer'), ('theme_park', 'Theme Park'), ('large_group', 'Large Group'), ('repeat_customer', 'Repeat Customer'), ('abandoned_quote', 'Abandoned Quote'), ('pre_pickup_urgency', 'Pre-Pickup Nudge — Urgency'), ('pre_pickup_cruise_urgency', 'Pre-Pickup Nudge — Cruise Urgency')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='followupsequence',
            name='step_number',
            field=models.PositiveSmallIntegerField(help_text='Step in the sequence (1-5 = form follow-up; 6 = pre-pickup nudge)'),
        ),
    ]
