# Generated by Django 5.1.4 on 2026-02-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_sweet_spot', models.IntegerField(default=100, help_text='20-60 min buffer')),
                ('buffer_good', models.IntegerField(default=80, help_text='60-120 min buffer')),
                ('buffer_tight', models.IntegerField(default=70, help_text='10-20 min buffer')),
                ('buffer_loose', models.IntegerField(default=50, help_text='120+ min buffer')),
                ('buffer_risky', models.IntegerField(default=30, help_text='Under 10 min buffer')),
                ('sb_buffer_sweet_spot', models.IntegerField(default=30, help_text='20-60 min buffer (builder)')),
                ('sb_buffer_good', models.IntegerField(default=20, help_text='60-120 min buffer (builder)')),
                ('sb_buffer_first_job', models.IntegerField(default=25, help_text='First job, no prior (builder)')),
                ('sb_buffer_tight', models.IntegerField(default=15, help_text='10-20 min buffer (builder)')),
                ('tier_exact', models.IntegerField(default=60, help_text='Exact tier match')),
                ('tier_1_down', models.IntegerField(default=40, help_text="1 tier below driver's vehicle")),
                ('tier_2_down', models.IntegerField(default=25, help_text='2 tiers below')),
                ('tier_3_down', models.IntegerField(default=15, help_text='3 tiers below')),
                ('tier_4_down', models.IntegerField(default=10, help_text='4 tiers below')),
                ('scarcity_1', models.IntegerField(default=80, help_text='Only 1 driver can do this job')),
                ('scarcity_2', models.IntegerField(default=50, help_text='2 eligible drivers')),
                ('scarcity_3', models.IntegerField(default=30, help_text='3 eligible drivers')),
                ('scarcity_4', models.IntegerField(default=15, help_text='4 eligible drivers')),
                ('loc_same_area', models.IntegerField(default=50, help_text='Last dropoff = next pickup area')),
                ('loc_close', models.IntegerField(default=30, help_text='Reposition drive <= 15 min')),
                ('loc_first_job', models.IntegerField(default=40, help_text='Driver has no prior jobs')),
                ('sb_loc_same_area', models.IntegerField(default=35, help_text='Same area bonus (builder)')),
                ('flow_3rd_arrival', models.IntegerField(default=-40, help_text='3rd+ consecutive arrival penalty')),
                ('flow_2nd_arrival', models.IntegerField(default=-15, help_text='2nd consecutive arrival penalty')),
                ('flow_break_bonus', models.IntegerField(default=30, help_text='Return/cruise breaking arrival streak')),
                ('sb_flow_3rd_arrival', models.IntegerField(default=-35, help_text='3rd+ arrival penalty (builder)')),
                ('sb_flow_2nd_arrival', models.IntegerField(default=-10, help_text='2nd arrival penalty (builder)')),
                ('sb_flow_break_bonus', models.IntegerField(default=25, help_text='Flow break bonus (builder)')),
                ('retention_bonus', models.IntegerField(default=25, help_text='Bonus for return/cruise in auto-assign')),
                ('chain_3_plus', models.IntegerField(default=45, help_text='3+ follow-up jobs near dropoff')),
                ('chain_2', models.IntegerField(default=35, help_text='2 follow-up jobs')),
                ('chain_1', models.IntegerField(default=20, help_text='1 follow-up job')),
                ('chain_drive_threshold', models.IntegerField(default=30, help_text='Max drive minutes to count as chainable')),
                ('chain_time_min', models.IntegerField(default=10, help_text='Min gap minutes for chain')),
                ('chain_time_max', models.IntegerField(default=180, help_text='Max gap minutes for chain')),
                ('load_balance_multiplier', models.IntegerField(default=5, help_text='Penalty per existing leg on driver')),
                ('inter_job_buffer', models.IntegerField(default=10, help_text='Minutes between jobs (break + buffer)')),
                ('base_score', models.IntegerField(default=50, help_text='Starting score for each candidate leg')),
                ('trip_pref_match', models.IntegerField(default=40, help_text='Bonus when leg matches preferred trip type')),
                ('trip_pref_mismatch', models.IntegerField(default=-10, help_text="Penalty when leg doesn't match preference")),
                ('revenue_divisor', models.IntegerField(default=10, help_text='Revenue / this = bonus points')),
                ('revenue_cap', models.IntegerField(default=20, help_text='Max revenue bonus points')),
            ],
            options={
                'verbose_name': 'Scheduler Settings',
                'verbose_name_plural': 'Scheduler Settings',
            },
        ),
    ]
