# Generated by Django 5.1.4 on 2026-02-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='buffer_perfect',
            field=models.IntegerField(default=120, help_text='20-30 min buffer (ideal)'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='sb_buffer_perfect',
            field=models.IntegerField(default=35, help_text='20-30 min buffer (builder, ideal)'),
        ),
        migrations.AlterField(
            model_name='schedulersettings',
            name='buffer_sweet_spot',
            field=models.IntegerField(default=100, help_text='30-60 min buffer (comfortable)'),
        ),
        migrations.AlterField(
            model_name='schedulersettings',
            name='inter_job_buffer',
            field=models.IntegerField(default=5, help_text='Minutes between jobs (break + buffer)'),
        ),
        migrations.AlterField(
            model_name='schedulersettings',
            name='sb_buffer_sweet_spot',
            field=models.IntegerField(default=30, help_text='30-60 min buffer (builder)'),
        ),
    ]
