# Generated by Django 5.1.4 on 2026-02-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0002_add_buffer_perfect_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='reserve_max_scarcity',
            field=models.IntegerField(default=2, help_text="Max eligible drivers for a job to count as 'needs saving'"),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='reserve_penalty',
            field=models.IntegerField(default=-60, help_text='Penalty when rare-vehicle driver takes mismatched job while matching jobs wait'),
        ),
    ]
