# Generated by Django 5.1.4 on 2026-03-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatching", "0003_add_vehicle_reservation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="swap_buffer_weight",
            field=models.IntegerField(
                default=2, help_text="Score multiplier for min buffer minutes"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="swap_depth_penalty",
            field=models.IntegerField(
                default=150, help_text="Score penalty per swap depth level"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="swap_max_depth",
            field=models.IntegerField(
                default=5, help_text="Max chain length for swap search"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="swap_max_iterations",
            field=models.IntegerField(
                default=5000, help_text="Max states to explore per search"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="swap_revenue_weight",
            field=models.IntegerField(
                default=10,
                help_text="Score weight for normalized revenue (revenue/divisor, capped)",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="swap_tier_bonus",
            field=models.IntegerField(
                default=20, help_text="Score bonus for exact vehicle tier match in swap"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="swap_time_limit_ms",
            field=models.IntegerField(
                default=5000, help_text="Time budget in ms for swap search"
            ),
        ),
    ]
