# Generated by Django 5.1.4 on 2026-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0004_schedulersettings_swap_buffer_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='arrival_grace_minutes',
            field=models.IntegerField(default=10, help_text='Airport arrival grace: flight lands but pax still deplaning/bags, so driver can arrive this many min after flight time'),
        ),
    ]
