# Generated by Django 5.1.4 on 2026-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0005_arrival_grace_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulersettings',
            name='arrival_grace_minutes',
            field=models.IntegerField(default=15, help_text='Airport arrival grace: flight lands but pax still deplaning/bags, so driver can arrive this many min after flight time'),
        ),
    ]
