# Generated by Django 5.1.4 on 2026-03-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatching", "0006_arrival_grace_default_15"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="backward_chain_bonus",
            field=models.IntegerField(
                default=40,
                help_text="Bonus when driver's last dropoff chains into this pickup",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="cluster_gap_minutes",
            field=models.IntegerField(
                default=120, help_text="Time gap in minutes to split into new cluster"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="idle_gap_penalty_per_min",
            field=models.IntegerField(
                default=2, help_text="Penalty per minute over idle threshold"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="idle_gap_threshold",
            field=models.IntegerField(
                default=120, help_text="Minutes of gap before idle penalty applies"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="load_balance_exponent",
            field=models.FloatField(
                default=1.5,
                help_text="Exponent for load balance: multiplier * (n ^ exponent)",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="shift_coherence_bonus",
            field=models.IntegerField(
                default=50,
                help_text="Bonus when job is in driver's assigned time cluster",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="span_penalty_per_hour",
            field=models.IntegerField(
                default=30, help_text="Penalty per hour over span threshold"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="span_threshold_hours",
            field=models.IntegerField(
                default=13, help_text="Max shift span hours before penalty"
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="time_scarcity_bonus",
            field=models.IntegerField(
                default=30,
                help_text="Bonus for legs in time-scarce hours (demand > supply)",
            ),
        ),
        migrations.AlterField(
            model_name="schedulersettings",
            name="load_balance_multiplier",
            field=models.IntegerField(
                default=10, help_text="Base multiplier for load balance penalty"
            ),
        ),
    ]
