# Generated by Django 5.1.4 on 2026-04-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0007_schedulersettings_backward_chain_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='driver_pay_overdue_days',
            field=models.IntegerField(default=14, help_text='Days after which unpaid legs are considered overdue'),
        ),
    ]
