# Generated by Django 5.1.4 on 2026-06-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatching", "0008_add_driver_pay_overdue_days_to_scheduler_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="auto_assign_value_weight",
            field=models.IntegerField(
                default=1,
                help_text="Weight of the founder leg-value scoring term (booked class › trip type › revenue › pax); one class step ≈ 10×weight points; 0 disables",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="displacement_min_value_gain",
            field=models.IntegerField(
                default=500,
                help_text="Evict-to-farm pass: min leg_value(residual) − leg_value(evicted arrival) to displace (1000 ≈ one trip-type step, 10000 ≈ one booked-class step)",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="max_displacements_per_run",
            field=models.IntegerField(
                default=10,
                help_text="Evict-to-farm pass: max evictions per auto-assign run",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="type_priority_arrival",
            field=models.IntegerField(
                default=3,
                help_text="Ordering priority for arrivals within each hour bucket (last: arrivals are the farm-out currency)",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="type_priority_cruise",
            field=models.IntegerField(
                default=1,
                help_text="Ordering priority for cruise legs within each hour bucket",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="type_priority_other",
            field=models.IntegerField(
                default=2,
                help_text="Ordering priority for 'other' legs within each hour bucket (also the fallback for unknown types)",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="type_priority_return",
            field=models.IntegerField(
                default=0,
                help_text="Ordering priority for returns/departures within each hour bucket",
            ),
        ),
    ]
