# Generated by Django 5.1.4 on 2026-06-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatching", "0009_founder_brain_value_knobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="rest_min_gap_minutes",
            field=models.IntegerField(
                default=510,
                help_text="Min overnight rest: minutes between a driver's last drop-off (prev day) and his first pickup (next day). 510=8.5h. 0 disables rest scoring + advisories.",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="rest_penalty_per_hour",
            field=models.IntegerField(
                default=40,
                help_text="Score penalty per hour of overnight-rest deficit, charged ONLY when a leg would become a driver's first pickup of the day (soft — never blocks coverage).",
            ),
        ),
    ]
