# Generated by Django 5.1.4 on 2026-07-20 19:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0010_schedulersettings_rest_min_gap_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRefreshTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('state', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flight Refresh Task',
                'verbose_name_plural': 'Flight Refresh Tasks',
            },
        ),
    ]
