# Generated by Django 5.1.4 on 2026-07-30 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0011_flightrefreshtask'),
        ('drivers', '0044_driver_employment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChauffeurExceptionDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=40)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_dismissals', to='drivers.driver')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('cleared_at', None)), fields=('driver', 'rule'), name='uniq_active_dismissal_per_driver_rule')],
            },
        ),
    ]
