# Generated by Django 5.1.4 on 2026-07-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0012_chauffeurexceptiondismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeurexceptiondismissal',
            name='window',
            field=models.CharField(default='30', max_length=3),
        ),
    ]
