# Generated by Django 5.1.4 on 2026-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0013_chauffeurexceptiondismissal_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='min_turn_buffer',
            field=models.IntegerField(default=5, help_text="Default spare minutes the ENGINE must leave between two jobs, on top of the drive between them. 0 = aggressive (a driver may be due at his next pickup the same instant he clears the last one). The builder and auto-assign can override this per run, and a per-driver number (Driver.default_min_turn_buffer) beats both. Does not affect a dispatcher's own manual assignments."),
        ),
        migrations.AlterField(
            model_name='schedulersettings',
            name='inter_job_buffer',
            field=models.IntegerField(default=5, help_text="DEPRECATED — has no effect. Use 'Min turn buffer'."),
        ),
    ]
