# Generated by Django 5.1.4 on 2026-08-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0014_schedulersettings_min_turn_buffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='manual_assign_warnings',
            field=models.BooleanField(default=True, help_text='Warn-only validation on the manual assign path (board drag-drop and driver dropdowns): turn-slack and shared-car checks returned as dismissible warnings on the response. NEVER blocks an assignment. Off (0) skips the computation entirely.'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='vehicle_share_pad_min',
            field=models.IntegerField(default=120, help_text="Shared-car handoff pad: when two drivers hold ONE physical unit for the day, an insert for one must clear the partner's jobs by this many minutes each side. 120 is the empirical anchor from measured handoffs — the retired constant 60 sat near the 9th percentile of real pickup-to-pickup handoff gaps (optimistic nine times in ten)."),
        ),
    ]
