# Generated by Django 5.1.4 on 2026-08-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatching", "0015_schedulersettings_manual_assign_warnings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulersettings",
            name="handoff_gap_amber_floor_pct",
            field=models.IntegerField(
                default=100,
                help_text="Handoff AMBER floor as a percent of the LOW zone chain — below this (and below the skip-wash fast path) a handoff is RED: shown, never suggested. 100 = the 03-model rule exactly.",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="handoff_gap_green_pct",
            field=models.IntegerField(
                default=100,
                help_text="Handoff GREEN bar as a percent of the central wash-fuel-base zone chain (drop zone to next-pickup zone). 100 = the 03-model rule exactly; lower is more permissive. Structured chain tables live in dispatching/handoff_chain.py.",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="mint_min_jobs_soft",
            field=models.IntegerField(
                default=2,
                help_text="Soft minimum jobs on a proposed standby second shift (D6). NEVER a hard floor — a thinner proposal still shows, flagged 'thin — worth it?' with the dollars it saves.",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="share_split_hour",
            field=models.IntegerField(
                default=16,
                help_text="Default AM/PM cut hour for a planned shared car when no better cut is known (16 = the measured modal handoff hour). A standby second-shift proposal derives its own cut from the actual handoff; this is the fallback for hand-made shares.",
            ),
        ),
        migrations.AddField(
            model_name="schedulersettings",
            name="span_exception_max_hours",
            field=models.FloatField(
                default=15.0,
                help_text="Hard ceiling for the priced crunch exception: a per-driver day may be proposed past the 13.5h soft cap ONLY up to this many hours, priced and rendered as a choice — never a default.",
            ),
        ),
    ]
