# Generated by Django 5.1.4 on 2026-08-25 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0017_schedulersettings_engine_share_pad_min'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_enabled',
            field=models.BooleanField(default=False, help_text="Master switch for the Day-Builder ('Build a plan' in Day Setup). Ships OFF — the feature exists but stays invisible until the founder turns it on (05 §7 acceptance)."),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_epsilon_farmouts',
            field=models.IntegerField(default=0, help_text='The coverage dial: allow up to this many MORE farm-outs than the same-date suggest+build baseline to buy a better day (0-3). At 0 the builder may never worsen coverage. Applies to the farm-out count ONLY — it can never buy a wall (conflicts, hours, rest, shared-car rules).'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_runtime_budget_s',
            field=models.IntegerField(default=240, help_text="Day-Builder: wall-clock ceiling in seconds. The job stops at the ceiling and returns its best-so-far, flagged 'budget exhausted' — never silently truncated."),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_stale_after_min',
            field=models.IntegerField(default=120, help_text="Day-Builder: a computed plan older than this many minutes renders greyed with a 're-build' prompt (bookings move)."),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_w_fairness',
            field=models.FloatField(default=1.0, help_text='Day-Builder quality weight [assumed]: stdev of legs per working driver. Tie-break only.'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_w_gaps',
            field=models.FloatField(default=0.5, help_text='Day-Builder quality weight [assumed]: hours of internal idle gaps above the idle-gap threshold. Tie-break only.'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_w_handoff',
            field=models.FloatField(default=2.0, help_text='Day-Builder quality weight [assumed]: count of AMBER handoff bands in the plan (RED is a wall, never scored). Tie-break only.'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='opt_w_span',
            field=models.FloatField(default=1.0, help_text='Day-Builder quality weight [assumed]: sum of per-driver effective hours over the 13.5h target. Tie-break only — never outranks coverage or farm cost, never moves a wall.'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='pass_b_max_evals',
            field=models.IntegerField(default=10, help_text='Day-Builder: hard budget of full pipeline evaluations per run (each costs ~6-15s on a real day).'),
        ),
        migrations.AddField(
            model_name='schedulersettings',
            name='pass_b_max_swaps',
            field=models.IntegerField(default=6, help_text='Day-Builder: max targeted pairing swaps considered per run. A swap is considered only when it changes a tier constraint or reshapes a shared car.'),
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('done', 'Done'), ('refused', 'Refused'), ('error', 'Error')], default='idle', max_length=10)),
                ('epsilon', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('bookings_as_of', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('result_json', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('budget_exhausted', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
