# Generated by Django 5.1.4 on 2026-09-05 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0018_schedulersettings_opt_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True)),
                ('card_id', models.CharField(db_index=True, max_length=120)),
                ('episode', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(blank=True, default='', max_length=24)),
                ('severity', models.CharField(blank=True, default='', max_length=10)),
                ('basis', models.CharField(blank=True, default='', max_length=24)),
                ('severity_last', models.CharField(blank=True, default='', max_length=10)),
                ('basis_last', models.CharField(blank=True, default='', max_length=24)),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('impact_leg_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('impact_leg_first_id', models.IntegerField(blank=True, null=True)),
                ('leg_count', models.PositiveSmallIntegerField(default=0)),
                ('impact_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField()),
                ('sightings', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('rail', 'Dispatch board rail'), ('task', 'Ops task detail'), ('sweep', 'Background sweep')], default='rail', max_length=8)),
                ('had_plans', models.BooleanField(default=False)),
                ('detected_only', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_plan_id', models.CharField(blank=True, default='', max_length=140)),
                ('applied_mode', models.CharField(blank=True, default='', max_length=8)),
                ('applied_snapshot_id', models.IntegerField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rejected_error', models.CharField(blank=True, default='', max_length=200)),
                ('snoozed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('snooze_count', models.PositiveSmallIntegerField(default=0)),
                ('task_filed_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('task_created', models.BooleanField(default=False)),
                ('outcome_filled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('outcome_attempts', models.PositiveSmallIntegerField(default=0)),
                ('outcome_quality', models.CharField(blank=True, choices=[('ok', 'Scored'), ('batch', 'Batch-entered taps'), ('none', 'No usable tap'), ('no_deadline', 'No priceable deadline'), ('unknown', 'Impact leg off the date')], default='', max_length=12)),
                ('outcome_late_min', models.FloatField(blank=True, null=True)),
                ('outcome_deadline', models.DateTimeField(blank=True, null=True)),
                ('outcome_deadline_basis', models.CharField(blank=True, default='', max_length=60)),
                ('outcome_tap_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snoozed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task_filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisor Event',
                'verbose_name_plural': 'Advisor Events',
                'indexes': [models.Index(fields=['service_date', 'outcome_filled_at'], name='idx_advisor_event_fill')],
                'constraints': [models.UniqueConstraint(fields=('service_date', 'card_id', 'episode'), name='uniq_advisor_event_episode')],
            },
        ),
    ]
