# Generated by Django 5.1.4 on 2026-09-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0019_advisorevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchEtaSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_id_ref', models.IntegerField(db_index=True)),
                ('driver_id_ref', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sampled_at', models.DateTimeField(db_index=True)),
                ('eta_target', models.CharField(blank=True, default='', max_length=12)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('eta_target_time', models.DateTimeField(blank=True, null=True)),
                ('risk_status', models.CharField(blank=True, default='', max_length=12)),
                ('minutes_to_target', models.FloatField(blank=True, null=True)),
                ('slack_minutes', models.FloatField(blank=True, null=True)),
                ('is_moving', models.BooleanField(blank=True, null=True)),
                ('stationary_minutes', models.IntegerField(blank=True, null=True)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('vehicle_label', models.CharField(blank=True, default='', max_length=32)),
                ('eta_carried', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dispatch ETA Sample',
                'verbose_name_plural': 'Dispatch ETA Samples',
                'indexes': [models.Index(fields=['leg_id_ref', 'sampled_at'], name='idx_eta_sample_series')],
                'constraints': [models.UniqueConstraint(fields=('leg_id_ref', 'sampled_at'), name='uniq_eta_sample_leg_tick')],
            },
        ),
    ]
