# Generated by Django 5.1.4 on 2026-09-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0020_dispatchetasample'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchetasample',
            name='origin_target',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
