# Generated by Django 5.1.4 on 2026-10-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatching', '0021_dispatchetasample_origin_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulersettings',
            name='regular_shift_windows',
            field=models.BooleanField(default=False, help_text="Auto-assign reads each driver's hours from their confirmed regular shift instead of the old fixed table. Turned on from the Regular Shifts page once every driver has one."),
        ),
    ]
