# Generated by Django 5.1.4 on 2025-03-31 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0003_alter_rate_route_alter_rate_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rates.route"
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="rates.vehicle",
            ),
        ),
    ]
