# Generated by Django 5.1.4 on 2025-04-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0004_alter_rate_route_alter_rate_vehicle"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rate",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="rate",
            name="oneway_price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="rate",
            name="round_trip_price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name="rate",
            index=models.Index(
                fields=["vehicle", "route"], name="rates_rate_vehicle_822bc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rate",
            index=models.Index(
                fields=["vehicle", "oneway_price"], name="rates_rate_vehicle_96c8ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rate",
            index=models.Index(
                fields=["route", "round_trip_price"],
                name="rates_rate_route_i_d77301_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rate",
            constraint=models.UniqueConstraint(
                fields=("vehicle", "route"), name="unique_vehicle_route"
            ),
        ),
    ]
