# Generated by Django 5.1.4 on 2025-04-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0005_alter_rate_unique_together_alter_rate_oneway_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="carseat",
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="carseat_capacity",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
