# Generated by Django 5.1.4 on 2025-04-07 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0006_vehicle_carseat_vehicle_carseat_capacity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["capacity"]},
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="carseat",
            new_name="carseats",
        ),
    ]
