# Generated by Django 5.1.4 on 2025-04-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0007_alter_vehicle_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="carseats",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="boosters",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="ff_carseats",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="rf_carseats",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
