# Generated by Django 5.1.4 on 2025-04-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0008_remove_vehicle_carseats_vehicle_boosters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="ff_carseats",
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="rf_carseats",
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
