# Generated by Django 5.1.4 on 2025-04-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0009_alter_vehicle_ff_carseats_alter_vehicle_rf_carseats"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rate",
            name="rates_rate_vehicle_822bc6_idx",
        ),
        migrations.RemoveIndex(
            model_name="rate",
            name="rates_rate_vehicle_96c8ea_idx",
        ),
        migrations.RemoveIndex(
            model_name="rate",
            name="rates_rate_route_i_d77301_idx",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="boosters",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="carseat_capacity",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="ff_carseats",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="rf_carseats",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="boosters_max",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="carseats_capacity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="ff_carseats_max",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="rf_carseats_max",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="rate",
            index=models.Index(
                fields=["vehicle"], name="rates_rate_vehicle_43ce2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rate",
            index=models.Index(
                fields=["oneway_price"], name="rates_rate_oneway__fe7735_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rate",
            index=models.Index(
                fields=["round_trip_price"], name="rates_rate_round_t_849d69_idx"
            ),
        ),
    ]
