# Generated by Django 5.1.4 on 2025-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0010_remove_rate_rates_rate_vehicle_822bc6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="carseats_display",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
