# Generated by Django 5.1.4 on 2025-04-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0011_vehicle_carseats_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="carseats_display",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
