# Generated by Django 5.1.4 on 2026-02-18 03:11

from django.db import migrations


# Map Location IDs (used by Routes) to aliases that match real-world addresses.
# The route matcher checks if any alias is a SUBSTRING of the pickup/dropoff text,
# and picks the LONGEST match. This means "Disney Springs" (14 chars) beats
# "Disney" (6 chars) for Disney Springs addresses, which is correct.
LOCATION_ALIASES = {
    1: "MCO, Orlando Airport",                        # Orlando International Airport
    2: "Universal, Portofino Bay, Portfino Bay, Royal Pacific",  # Universal Studios Area Hotels
    3: "Disney, Walt Disney World, Art of Animation, Bonnet Creek, Saratoga Springs",  # All WDW Disney Property Resorts
    4: "International Drive, I-Drive",                 # International Drive Hotels
    5: "Disney Springs",                               # Disney Springs Hotels
    6: "Kissimmee 192, Irlo Bronson",                   # Kissimmee 192 Area Hotels
    7: "Champions Gate, Championsgate, Reunion",       # Omni Championsgate / Reunion
    # 8: Port Canaveral — name already matches all real addresses
    9: "SeaWorld",                                     # Sea World
    10: "Sanford, SFB",                                # Sanford Int'l Airport
}


def populate_aliases(apps, schema_editor):
    Location = apps.get_model("rates", "Location")
    for loc_id, aliases in LOCATION_ALIASES.items():
        Location.objects.filter(id=loc_id).update(aliases=aliases)


def clear_aliases(apps, schema_editor):
    Location = apps.get_model("rates", "Location")
    for loc_id in LOCATION_ALIASES:
        Location.objects.filter(id=loc_id).update(aliases="")


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0017_location_aliases'),
    ]

    operations = [
        migrations.RunPython(populate_aliases, clear_aliases),
    ]
