# Generated by Django 5.1.4 on 2026-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0019_update_location_aliases_and_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='extra_booster_fee',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Fee per additional booster seat beyond vehicle limit', max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='extra_carseat_fee',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Fee per additional car seat beyond vehicle limit', max_digits=6),
        ),
    ]
