# Generated by Django 5.1.4 on 2026-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0020_add_extra_seat_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='included_boosters',
            field=models.PositiveIntegerField(default=2, help_text='Booster seats included in base price — extras cost the fee below'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='included_carseats',
            field=models.PositiveIntegerField(default=2, help_text='Car seats (FF + RF combined) included in base price — extras cost the fee below'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='boosters_max',
            field=models.PositiveIntegerField(default=2, help_text='Max booster seats that physically fit'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='carseats_capacity',
            field=models.PositiveIntegerField(default=4, help_text='Total child seats (FF + RF + boosters) that physically fit'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='extra_booster_fee',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Fee per additional booster seat beyond included limit', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='extra_carseat_fee',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Fee per additional car seat beyond included limit', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ff_carseats_max',
            field=models.PositiveIntegerField(default=2, help_text='Max forward-facing car seats that physically fit'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rf_carseats_max',
            field=models.PositiveIntegerField(default=2, help_text='Max rear-facing car seats that physically fit'),
        ),
    ]
