# Generated by Django 5.1.4 on 2026-04-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0021_add_included_seat_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='extra_stop_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat fee per intermediate stop (same-area drop-offs, luggage drops, etc.)', max_digits=6),
        ),
        migrations.AddField(
            model_name='location',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional area grouping. Locations sharing a group can be offered as extra stops on routes that allow that group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='rates.locationgroup'),
        ),
        migrations.AddField(
            model_name='route',
            name='allowed_extra_stop_groups',
            field=models.ManyToManyField(blank=True, help_text='LocationGroups whose locations may be offered to customers as add-on stops on this route. Empty = no extra-stop picker shown.', related_name='routes_allowing_extra_stops', to='rates.locationgroup'),
        ),
    ]
