# Generated by Django 5.1.4 on 2026-06-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0022_add_locationgroup_and_extra_stop_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="requires_certification",
            field=models.BooleanField(
                default=False,
                help_text="If checked, only drivers explicitly cleared for this vehicle type may be assigned it (e.g. the Sprinter / 14-passenger van). Assigning it to an uncertified driver is blocked.",
            ),
        ),
    ]
