# Generated by Django 5.1.4 on 2026-08-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0024_merge_duplicate_universal_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, help_text='What belongs in this zone, in your own words. Shown nowhere but the admin — it is for whoever picks the zone next.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Display order. Lower comes first.')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='pay_zone',
            field=models.ForeignKey(blank=True, help_text='Which pay zone this place is in. Leave blank for somewhere with no agreed price yet: trips there stay unpriced and are flagged on the driver pay page instead of being guessed at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='rates.zone'),
        ),
        migrations.CreateModel(
            name='ZoneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhouse_base_pay', models.DecimalField(decimal_places=2, help_text='Base pay for an in-house driver on any trip between these two zones.', max_digits=10)),
                ('zone_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_a', to='rates.zone')),
                ('zone_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_b', to='rates.zone')),
            ],
            options={
                'verbose_name': 'Zone rate',
                'ordering': ['zone_a__sort_order', 'zone_b__sort_order'],
                'unique_together': {('zone_a', 'zone_b')},
            },
        ),
    ]
