# Generated by Django 5.1.4 on 2026-03-12 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0085_add_initial_email_sent_to_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("lead_response", "Lead Response"),
                            ("payment_chase", "Payment Chase"),
                            ("flight_verify", "Flight Verification"),
                            ("guest_confirm", "Guest Confirmation"),
                            ("driver_assign", "Driver Assignment"),
                            ("coverage_gap", "Coverage Gap"),
                            ("manual", "Manual Task"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("snoozed", "Snoozed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("escalated", "Escalated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "High"),
                            (3, "Medium"),
                            (4, "Low"),
                        ],
                        db_index=True,
                        default=3,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(db_index=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                (
                    "escalate_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-escalate if still open after this time",
                        null=True,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Task-specific data: flight mismatch details, payment amounts, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_ops_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Soft dependency — shows a warning, does not prevent action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks",
                        to="ops.operationaltask",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ops_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops_tasks",
                        to="reservations.lead",
                    ),
                ),
                (
                    "leg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops_tasks",
                        to="reservations.leg",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops_tasks",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_ops_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Task",
                "verbose_name_plural": "Operational Tasks",
                "ordering": ["priority", "due_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("answered", "Answered"),
                            ("voicemail", "Voicemail"),
                            ("no_answer", "No Answer"),
                            ("busy", "Busy"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contact_value",
                    models.CharField(
                        blank=True,
                        help_text="Phone number or email used",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Call duration in seconds", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comm_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_attempts",
                        to="ops.operationaltask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Attempt",
                "verbose_name_plural": "Communication Attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("task_claimed", "Task Claimed"),
                            ("task_completed", "Task Completed"),
                            ("task_snoozed", "Task Snoozed"),
                            ("task_created", "Task Created"),
                            ("comm_logged", "Communication Logged"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, help_text="URL path for page views", max_length=500
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_activities",
                        to="ops.operationaltask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Activity",
                "verbose_name_plural": "Staff Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="operationaltask",
            index=models.Index(
                fields=["status", "priority", "due_at"], name="idx_ops_queue"
            ),
        ),
        migrations.AddIndex(
            model_name="operationaltask",
            index=models.Index(
                fields=["task_type", "status"], name="idx_ops_type_status"
            ),
        ),
        migrations.AddIndex(
            model_name="operationaltask",
            index=models.Index(
                fields=["assigned_to", "status"], name="idx_ops_assigned"
            ),
        ),
        migrations.AddIndex(
            model_name="operationaltask",
            index=models.Index(
                fields=["leg", "task_type", "status"], name="idx_ops_leg_dedup"
            ),
        ),
        migrations.AddIndex(
            model_name="operationaltask",
            index=models.Index(
                fields=["reservation", "task_type", "status"], name="idx_ops_res_dedup"
            ),
        ),
        migrations.AddIndex(
            model_name="operationaltask",
            index=models.Index(
                fields=["lead", "task_type", "status"], name="idx_ops_lead_dedup"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationattempt",
            index=models.Index(
                fields=["task", "-created_at"], name="idx_comm_task_time"
            ),
        ),
        migrations.AddIndex(
            model_name="staffactivity",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_staff_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="staffactivity",
            index=models.Index(
                fields=["action_type", "-created_at"], name="idx_staff_action_time"
            ),
        ),
    ]
