# Generated by Django 5.1.4 on 2026-03-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        ('users', '0029_travelagent_include_in_confirmation_sms_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaltask',
            name='contact_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_tasks', to='users.contactusform'),
        ),
        migrations.AlterField(
            model_name='operationaltask',
            name='task_type',
            field=models.CharField(choices=[('payment_chase', 'Unpaid Reservations'), ('flight_verify', 'Flight Verification'), ('driver_assign', 'Driver Assignment'), ('contact_form', 'Contact Us'), ('manual', 'Manual Task')], db_index=True, max_length=30),
        ),
    ]
