# Generated by Django 5.1.4 on 2026-03-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_operationaltask_contact_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaltask',
            name='task_type',
            field=models.CharField(choices=[('payment_chase', 'Unpaid Reservations'), ('flight_verify', 'Flight Verification'), ('driver_conflict', 'Driver Conflict'), ('driver_assign', 'Driver Assignment'), ('contact_form', 'Contact Us'), ('manual', 'Manual Task')], db_index=True, max_length=30),
        ),
    ]
