# Generated by Django 5.1.4 on 2026-03-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_add_driver_conflict_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactivity',
            name='action_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('task_claimed', 'Task Claimed'), ('task_completed', 'Task Completed'), ('task_snoozed', 'Task Snoozed'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('comm_logged', 'Communication Logged')], max_length=30),
        ),
    ]
