# Generated by Django 5.1.4 on 2026-04-03 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_add_task_assigned_action_type'),
        ('reservations', '0092_merge_20260324_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('confirmation', 'Reservation Confirmation'), ('payment_reminder', 'Payment Reminder'), ('driver_statement', 'Driver Payment Statement'), ('agent_commission', 'Agent Commission Statement'), ('agency_commission', 'Agency Commission Statement'), ('lead_quote', 'Lead Quote'), ('admin_report', 'Admin Commission Report'), ('other', 'Other')], default='other', max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='reservations.reservation')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Staff member who triggered the send', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_by', '-sent_at'], name='idx_email_user_time'), models.Index(fields=['email_type', '-sent_at'], name='idx_email_type_time')],
            },
        ),
    ]
