# Generated by Django 5.1.4 on 2026-04-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_add_confirmation_texts_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaltask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the task was last assigned or reassigned', null=True),
        ),
    ]
