# Generated by Django 5.1.4 on 2026-06-01 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0007_add_assigned_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeClockShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clock_in_at", models.DateTimeField(db_index=True)),
                (
                    "clock_out_at",
                    models.DateTimeField(
                        blank=True, help_text="NULL while the shift is open.", null=True
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "auto_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Closed automatically because it was left open too long.",
                    ),
                ),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when an admin corrects the times.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_timeclock_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeclock_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Clock Shift",
                "verbose_name_plural": "Time Clock Shifts",
                "ordering": ["-clock_in_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeClockBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_start_at", models.DateTimeField(db_index=True)),
                (
                    "break_end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL while the break is in progress.",
                        null=True,
                    ),
                ),
                (
                    "auto_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Closed automatically because the shift was clocked out while on break.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="ops.timeclockshift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Clock Break",
                "verbose_name_plural": "Time Clock Breaks",
                "ordering": ["break_start_at"],
            },
        ),
        migrations.AddIndex(
            model_name="timeclockshift",
            index=models.Index(
                fields=["user", "-clock_in_at"], name="idx_tcshift_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="timeclockshift",
            index=models.Index(
                condition=models.Q(("clock_out_at__isnull", True)),
                fields=["clock_out_at"],
                name="idx_tcshift_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeclockshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clock_out_at__isnull", True)),
                fields=("user",),
                name="uniq_open_shift_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="timeclockbreak",
            index=models.Index(
                fields=["shift", "break_start_at"], name="idx_tcbreak_shift"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeclockbreak",
            constraint=models.UniqueConstraint(
                condition=models.Q(("break_end_at__isnull", True)),
                fields=("shift",),
                name="uniq_open_break_per_shift",
            ),
        ),
    ]
