# Generated by Django 5.1.4 on 2026-06-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0008_add_timeclock_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationaltask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("payment_chase", "Unpaid Reservations"),
                    ("flight_verify", "Flight Verification"),
                    ("driver_conflict", "Driver Conflict"),
                    ("driver_assign", "Driver Assignment"),
                    ("confirmation_texts", "Confirmation Texts"),
                    ("contact_form", "Contact Us"),
                    ("afterhours_fee", "After-Hours Fee"),
                    ("manual", "Manual Task"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
