# Generated by Django 5.1.4 on 2026-06-01 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0009_alter_operationaltask_task_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="First day this override applies."),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Last day; blank = single day.", null=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("custom_hours", "Custom hours"),
                            ("note", "Note only"),
                        ],
                        default="off",
                        max_length=16,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Eastern wall-clock; for custom_hours.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Eastern wall-clock; for custom_hours.",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staff_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Schedule Override",
                "verbose_name_plural": "Staff Schedule Overrides",
                "ordering": ["date", "user"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="idx_staffov_user_date"),
                    models.Index(
                        fields=["user", "date", "end_date"], name="idx_staffov_range"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffWeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("is_working", models.BooleanField(default=True)),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Eastern wall-clock; null when off.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Eastern wall-clock; null when off.",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedule_rows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Weekly Schedule",
                "verbose_name_plural": "Staff Weekly Schedules",
                "ordering": ["user", "day_of_week"],
                "indexes": [
                    models.Index(
                        fields=["user", "day_of_week"], name="idx_staffwk_user_day"
                    )
                ],
                "unique_together": {("user", "day_of_week")},
            },
        ),
    ]
