# Generated by Django 5.1.4 on 2026-07-26 20:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_alter_staffactivity_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOnCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The calendar date whose early hours (default 12 AM–6 AM) this covers.')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), help_text='Eastern wall-clock; on-call window start.')),
                ('end_time', models.TimeField(default=datetime.time(6, 0), help_text='Eastern wall-clock; on-call window end (same day, no midnight cross).')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_oncall_shifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff On-Call',
                'verbose_name_plural': 'Staff On-Call',
                'ordering': ['date', 'user'],
                'indexes': [models.Index(fields=['date'], name='idx_oncall_date'), models.Index(fields=['user', 'date'], name='idx_oncall_user_date')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
