# Generated by Django 5.1.4 on 2026-08-17 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_staffoncall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_staff_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='denial_reason',
            field=models.CharField(blank=True, default='', help_text='Shown to the dispatcher when a request is declined.', max_length=200),
        ),
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='reason',
            field=models.CharField(blank=True, choices=[('pto', 'PTO / vacation'), ('sick', 'Sick'), ('personal', 'Personal'), ('appointment', 'Appointment'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='', help_text="Why the time off — only meaningful for 'off' entries.", max_length=16),
        ),
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='requested_by_staff',
            field=models.BooleanField(default=False, help_text='True when the dispatcher submitted this themselves.'),
        ),
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='role',
            field=models.CharField(blank=True, choices=[('opener', 'Opener'), ('mid', 'Mid-day'), ('closer', 'Closer'), ('both', 'Opener + Closer')], default='', help_text='One-off assigned duty for these dates. Blank = keep the recurring role.', max_length=12),
        ),
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending review'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='approved', help_text="Only 'approved' rows change anyone's schedule.", max_length=12),
        ),
        migrations.AddField(
            model_name='staffweeklyschedule',
            name='role',
            field=models.CharField(blank=True, choices=[('opener', 'Opener'), ('mid', 'Mid-day'), ('closer', 'Closer'), ('both', 'Opener + Closer')], default='', help_text='Assigned duty for this shift. Blank = derive from hours.', max_length=12),
        ),
        migrations.AddIndex(
            model_name='staffscheduleoverride',
            index=models.Index(fields=['status', 'date'], name='idx_staffov_status_date'),
        ),
    ]
