# Generated by Django 5.1.4 on 2026-08-17 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_staff_roles_and_timeoff_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffExtraShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For a weekly split shift. Leave blank for a one-off date.', null=True)),
                ('date', models.DateField(blank=True, db_index=True, help_text='For a one-off extra shift. Leave blank for a recurring weekday.', null=True)),
                ('start_time', models.TimeField(help_text='Eastern wall-clock.')),
                ('end_time', models.TimeField(help_text='Eastern wall-clock; may cross midnight.')),
                ('role', models.CharField(blank=True, choices=[('opener', 'Opener'), ('mid', 'Mid-day'), ('closer', 'Closer'), ('both', 'Opener + Closer')], default='', help_text='Assigned duty for this shift (an evening half often closes).', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_extra_shifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Extra Shift',
                'verbose_name_plural': 'Staff Extra Shifts',
                'ordering': ['user', 'day_of_week', 'date', 'start_time'],
                'indexes': [models.Index(fields=['user', 'day_of_week'], name='idx_staffextra_user_dow'), models.Index(fields=['user', 'date'], name='idx_staffextra_user_date')],
            },
        ),
    ]
