# Generated by Django 5.1.4 on 2026-09-01 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_staffextrashift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffscheduleoverride',
            name='location',
            field=models.CharField(blank=True, choices=[('office', 'In office'), ('remote', 'Work from home')], default='', help_text='One-off work location for these dates (e.g. in office on a usual WFH day). Blank = keep the weekly setting.', max_length=10),
        ),
        migrations.AddField(
            model_name='staffweeklyschedule',
            name='location',
            field=models.CharField(blank=True, choices=[('office', 'In office'), ('remote', 'Work from home')], default='', help_text='Where they work this weekday (office / WFH). Blank = not tracked.', max_length=10),
        ),
        migrations.AddField(
            model_name='timeclockshift',
            name='approval_reason',
            field=models.CharField(blank=True, default='', help_text='Why the clock-in was flagged (shown to the admin).', max_length=200),
        ),
        migrations.AddField(
            model_name='timeclockshift',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='', help_text='Only set for unscheduled clock-ins. Blank = no approval needed.', max_length=10),
        ),
        migrations.AddField(
            model_name='timeclockshift',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeclockshift',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved or denied the unscheduled clock-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_timeclock_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeclockshift',
            name='unscheduled',
            field=models.BooleanField(default=False, help_text="Clock-in fell outside this staffer's planned schedule."),
        ),
        migrations.AddIndex(
            model_name='timeclockshift',
            index=models.Index(condition=models.Q(('approval_status', 'pending')), fields=['approval_status'], name='idx_tcshift_pending'),
        ),
    ]
