# Generated by Django 5.1.4 on 2026-09-01 20:42
#
# The company has no PTO, so the "pto" reason goes away. Existing rows are
# converted to "vacation" (same rename the drivers side made in
# drivers/0026_remove_pto_reason) so old time off keeps a readable label.

from django.db import migrations, models


def pto_to_vacation(apps, schema_editor):
    Override = apps.get_model("ops", "StaffScheduleOverride")
    Override.objects.filter(reason="pto").update(reason="vacation")


def vacation_to_pto(apps, schema_editor):
    Override = apps.get_model("ops", "StaffScheduleOverride")
    Override.objects.filter(reason="vacation").update(reason="pto")


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_staffscheduleoverride_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffscheduleoverride',
            name='reason',
            field=models.CharField(blank=True, choices=[('vacation', 'Vacation'), ('sick', 'Sick'), ('personal', 'Personal'), ('appointment', 'Appointment'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='', help_text="Why the time off — only meaningful for 'off' entries.", max_length=16),
        ),
        migrations.RunPython(pto_to_vacation, vacation_to_pto),
    ]
