# Generated by Django 5.1.4 on 2026-09-01 21:27
#
# Unscheduled clock-ins no longer open a shift that waits for approval — they
# file a TimeClockRequest, and the clock only starts once the admin approves
# AND the staffer punches. Shifts flagged "pending" under the short-lived
# flag-after-the-fact flow are grandfathered to "approved": the hours were
# genuinely worked, and denying by migration would be wrong.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_pending_shifts(apps, schema_editor):
    Shift = apps.get_model("ops", "TimeClockShift")
    Shift.objects.filter(approval_status="pending").update(approval_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_alter_staffscheduleoverride_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(grandfather_pending_shifts, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TimeClockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', help_text='Why the punch was outside the schedule (shown to the admin).', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved — not yet used'), ('denied', 'Denied'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', help_text='Shown to the staffer when a request is denied.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_timeclock_requests', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, help_text='The shift this grant opened, once used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='ops.timeclockshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeclock_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Clock Request',
                'verbose_name_plural': 'Time Clock Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='idx_tcreq_user_time'), models.Index(condition=models.Q(('status', 'pending')), fields=['status'], name='idx_tcreq_pending')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='uniq_pending_tcrequest_per_user')],
            },
        ),
    ]
