# Generated by Django 5.1.4 on 2026-09-12 21:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_timeclockrequest'),
        ('reservations', '0129_legclientmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_safe_target', models.TimeField(default=datetime.time(7, 15), help_text='Eastern wall-clock. The board is safe to operate by this time.')),
                ('open_complete_target', models.TimeField(default=datetime.time(8, 0), help_text='Eastern wall-clock. Opening is fully done by this time.')),
                ('close_target', models.TimeField(blank=True, default=datetime.time(21, 0), help_text='Eastern wall-clock target for finishing the close. Blank = untimed.', null=True)),
                ('open_system_rows', models.JSONField(blank=True, default=list, help_text='System row keys shown on Open Shift. Blank = the built-in default.')),
                ('close_system_rows', models.JSONField(blank=True, default=list, help_text='System row keys shown on Close Shift. Blank = the built-in default.')),
                ('human_rows', models.JSONField(blank=True, default=list, help_text='Human-verified row keys, both shifts. Blank = the built-in default.')),
                ('summary_intro', models.CharField(blank=True, default='', help_text='Optional first line prepended to the pasteable completion message.', max_length=200)),
            ],
            options={
                'verbose_name': 'Shift Settings',
                'verbose_name_plural': 'Shift Settings',
            },
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='action_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('task_claimed', 'Task Claimed'), ('task_completed', 'Task Completed'), ('task_snoozed', 'Task Snoozed'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('comm_logged', 'Communication Logged'), ('flight_matched', 'Flight Time Matched'), ('shift_opened', 'Shift Checklist Opened'), ('shift_row_confirmed', 'Checklist Row Confirmed'), ('shift_exception', 'Shift Exception Raised'), ('shift_completed', 'Shift Checklist Completed'), ('shift_reopened', 'Shift Checklist Reopened')], max_length=30),
        ),
        migrations.CreateModel(
            name='ShiftChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text="The shift's own calendar day (Eastern).")),
                ('kind', models.CharField(choices=[('open', 'Open Shift'), ('close', 'Close Shift')], max_length=5)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('board_safe_at', models.DateTimeField(blank=True, help_text='Stamped when every system row is clear or documented and carried notes are owned.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_count', models.PositiveSmallIntegerField(default=0)),
                ('targets', models.JSONField(blank=True, default=dict)),
                ('counts_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_checklists_completed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_checklists_opened', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_checklists_reopened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Checklist',
                'verbose_name_plural': 'Shift Checklists',
                'ordering': ['-date', 'kind'],
                'permissions': [('review_checklists', 'Can review shift checklist history'), ('reopen_checklist', 'Can reopen a completed shift checklist'), ('edit_exception_owner', 'Can change who owns a shift exception')],
            },
        ),
        migrations.CreateModel(
            name='ShiftChecklistRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=24)),
                ('kind', models.CharField(choices=[('system', 'System-verified'), ('human', 'Human-verified')], max_length=6)),
                ('state', models.CharField(choices=[('open', 'Outstanding'), ('clear', 'Clear'), ('documented', 'Documented exception')], default='open', max_length=12)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('last_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ops.shiftchecklist')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_rows_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Checklist Row',
                'verbose_name_plural': 'Shift Checklist Rows',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField(help_text='What is outstanding.')),
                ('next_action', models.CharField(help_text='What happens next.', max_length=200)),
                ('next_action_at', models.DateTimeField(blank=True, help_text='When the next action is due, if it has a time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=200)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_exceptions_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('carried_from', models.ForeignKey(blank=True, help_text='The exception on the previous shift this one continues.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to', to='ops.shiftexception')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='ops.shiftchecklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_exceptions_created', to=settings.AUTH_USER_MODEL)),
                ('keoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_exceptions', to='reservations.legkeoi')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_exceptions', to='reservations.leg')),
                ('owner', models.ForeignKey(help_text='The person who owns it. Never blank — that is the whole point.', on_delete=django.db.models.deletion.PROTECT, related_name='shift_exceptions_owned', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='ops.shiftchecklistrow')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_exceptions', to='ops.operationaltask')),
            ],
            options={
                'verbose_name': 'Shift Exception',
                'verbose_name_plural': 'Shift Exceptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftchecklist',
            index=models.Index(fields=['-date', 'kind'], name='idx_shiftlist_date_kind'),
        ),
        migrations.AddConstraint(
            model_name='shiftchecklist',
            constraint=models.UniqueConstraint(fields=('date', 'kind'), name='uniq_shift_checklist_per_day'),
        ),
        migrations.AddConstraint(
            model_name='shiftchecklistrow',
            constraint=models.UniqueConstraint(fields=('checklist', 'key'), name='uniq_shift_row_per_checklist'),
        ),
        migrations.AddIndex(
            model_name='shiftexception',
            index=models.Index(fields=['checklist'], name='idx_shiftexc_checklist'),
        ),
        migrations.AddIndex(
            model_name='shiftexception',
            index=models.Index(condition=models.Q(('resolved_at__isnull', True)), fields=['resolved_at'], name='idx_shiftexc_open'),
        ),
    ]
