# Generated by Django 5.1.4 on 2026-09-12 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_shiftsettings_alter_staffactivity_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsettings',
            name='board_safe_minutes',
            field=models.PositiveSmallIntegerField(default=45, help_text='Opener SOP: minutes from starting the open to a safe board. 0 = wall-clock only.'),
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='open_complete_minutes',
            field=models.PositiveSmallIntegerField(default=90, help_text='Opener SOP: minutes from starting the open to a finished open. 0 = wall-clock only.'),
        ),
        migrations.AlterField(
            model_name='shiftsettings',
            name='board_safe_target',
            field=models.TimeField(default=datetime.time(7, 15), help_text='Eastern wall-clock backstop. The board is safe by this time however late the open started.'),
        ),
        migrations.AlterField(
            model_name='shiftsettings',
            name='open_complete_target',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Eastern wall-clock backstop. Opening is fully done by this time.'),
        ),
    ]
