# Generated by Django 5.1.4 on 2026-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_shiftsettings_board_safe_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftsettings',
            name='human_rows',
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='close_human_rows',
            field=models.JSONField(blank=True, default=list, help_text='Human-verified row keys on Close Shift. Blank = the built-in default.'),
        ),
        migrations.AddField(
            model_name='shiftsettings',
            name='open_human_rows',
            field=models.JSONField(blank=True, default=list, help_text='Human-verified row keys on Open Shift. Blank = the built-in default.'),
        ),
    ]
