# Generated by Django 5.1.4 on 2026-09-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_remove_shiftsettings_human_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactivity',
            name='action_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('task_claimed', 'Task Claimed'), ('task_completed', 'Task Completed'), ('task_snoozed', 'Task Snoozed'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('comm_logged', 'Communication Logged'), ('flight_matched', 'Flight Time Matched'), ('afterhours_settled', 'After-Hours Fee Settled'), ('shift_opened', 'Shift Checklist Opened'), ('shift_row_confirmed', 'Checklist Row Confirmed'), ('shift_exception', 'Shift Exception Raised'), ('shift_completed', 'Shift Checklist Completed'), ('shift_reopened', 'Shift Checklist Reopened')], max_length=30),
        ),
    ]
