# Generated by Django 5.1.4 on 2026-10-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_close_possible_duplicate_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftchecklist',
            options={'ordering': ['-date', 'kind'], 'permissions': [('review_checklists', 'Can review shift checklist history'), ('reopen_checklist', 'Can reopen a completed shift checklist'), ('edit_exception_owner', 'Can change who owns a shift exception'), ('view_team', 'Can see who is on shift and the staffing board')], 'verbose_name': 'Shift Checklist', 'verbose_name_plural': 'Shift Checklists'},
        ),
    ]
